<?php
/** Generated by scripts/build_st1704_wordpress_publication_operator_v2.py. */
if (! defined('ABSPATH')) {
    exit;
}

final class RAOS_ST1704_Publication_Bindings_V2
{
    const SCHEMA = 'RAOS_ST1704_PUBLICATION_BINDINGS_V2';
    const CATEGORY_NAME = '暮らしの道具';
    const CATEGORY_CONTRACT = 'KURASHINO_DOGU_SINGLE_V1';
    const ARTICLES_JSON = '{"st1704-anker-solix-c300-c800-c1000-differences":"anker-solix-c300-c800-c1000-differences","st1704-compact-robot-vacuum-shortlist":"compact-robot-vacuum-shortlist","st1704-countertop-dishwasher-for-small-households":"countertop-dishwasher-for-small-households","st1704-portable-power-station-guide":"portable-power-station-guide"}';
    const ARTICLES_SHA256 = '264e7fec00e5e4d59086d010700beb8ce2540c343f0519ea517a5e9df168db14';

    public static function articles()
    {
        if (! hash_equals(
            self::ARTICLES_SHA256,
            hash('sha256', self::ARTICLES_JSON)
        )) {
            return array();
        }
        $articles = json_decode(self::ARTICLES_JSON, true);
        if (! is_array($articles) || count($articles) !== 4) {
            return array();
        }
        foreach ($articles as $article_id => $slug) {
            if (! is_string($article_id) || ! is_string($slug)
                || preg_match('/\A[a-z0-9-]+\z/D', $article_id) !== 1
                || preg_match('/\A[a-z0-9-]+\z/D', $slug) !== 1) {
                return array();
            }
        }
        return $articles;
    }
}
