required-version = ">=0.12.1,<0.13"
no-sources = true
python-downloads = "manual"
python-preference = "only-managed"
prerelease = "disallow"
resolution = "highest"
exclude-newer = "2026-08-01T16:50:16Z"
index-strategy = "first-index"
keyring-provider = "disabled"
link-mode = "copy"

[[index]]
name = "pypi"
url = "https://pypi.org/simple"
default = true
