# Generated by repo://scripts/build_st1503_compute_edge.py; do not edit.
check "activation_and_bindings_remain_disabled" {
  assert {
    condition     = var.activation_enabled == false && var.production_apply_authorized == false && var.selected_provider_schema == null && var.selected_provider_plugin == null && var.selected_account_or_project == null && var.selected_region == null && var.selected_state_backend == null && var.selected_credential_source == null
    error_message = "Activation and physical provider bindings must remain disabled."
  }
}

check "physical_selections_remain_empty" {
  assert {
    condition     = length(var.selected_network_segments) == 0 && length(var.selected_domain_names) == 0 && length(var.selected_host_names) == 0 && length(var.selected_dns_certificate_references) == 0 && length(var.selected_image_digests) == 0 && length(var.selected_workload_identity_references) == 0 && length(var.selected_secret_references) == 0 && length(var.selected_waf_rule_definitions) == 0 && length(var.selected_rate_limit_thresholds) == 0 && length(var.selected_health_endpoint_bindings) == 0 && length(var.supplied_gate_evidence) == 0
    error_message = "Physical compute-edge selections require a reviewed successor contract."
  }
}

check "logical_component_inventory_is_exact" {
  assert {
    condition     = length(local.logical_components) == 37 && length(local.logical_edges) == 53
    error_message = "The closed logical compute-edge graph inventory cannot drift."
  }
}

check "public_entry_is_edge_only" {
  assert {
    condition     = alltrue([for component in values(local.logical_components) : !component.publicly_addressable || contains(["edge_public", "edge_admin", "dns_tls_public", "dns_tls_admin"], component.component_id)]) && alltrue([for id in ["edge_public", "edge_admin"] : local.logical_components[id].edge_mediated && local.logical_components[id].waf_required && local.logical_components[id].rate_limit_required])
    error_message = "Only DNS/TLS and managed WAF edge declarations may be publicly addressable."
  }
}

check "origins_and_data_plane_remain_private" {
  assert {
    condition     = alltrue([for component in values(local.logical_components) : component.direct_data_plane_access == false]) && alltrue([for id in ["workload_public_web", "workload_admin_web", "workload_core_api", "workload_worker_pool"] : local.logical_components[id].publicly_addressable == false && local.logical_components[id].private_origin == true])
    error_message = "Workloads, origins, and the data plane must remain private."
  }
}

check "surface_boundaries_are_distinct" {
  assert {
    condition     = local.surface_policies.public.public_projection_only == true && local.surface_policies.admin.shared_cache_allowed == false && local.surface_policies.internal.shared_cache_allowed == false && local.surface_policies.public.cookie_boundary == "DISTINCT" && local.surface_policies.admin.cookie_boundary == "DISTINCT" && local.surface_policies.public.csp_boundary == "DISTINCT" && local.surface_policies.admin.csp_boundary == "DISTINCT"
    error_message = "Public, Admin, and Internal cache, cookie, CSP, identity, and data boundaries must remain distinct."
  }
}

check "images_are_immutable_and_provenanced" {
  assert {
    condition     = alltrue([for id in ["workload_public_web", "workload_admin_web", "workload_core_api", "workload_worker_pool"] : local.logical_components[id].immutable_image_required && local.logical_components[id].digest_selection_required && local.logical_components[id].signed_provenance_required && local.logical_components[id].sbom_required && local.logical_components[id].image_scan_required])
    error_message = "Every workload requires digest-selected images, provenance, SBOM, and scanning."
  }
}

check "identity_secrets_and_egress_are_closed" {
  assert {
    condition     = alltrue([for component in values(local.logical_components) : component.secret_material_present == false && component.transport_encryption_required == true]) && alltrue([for id in ["workload_public_web", "workload_admin_web", "workload_core_api", "workload_worker_pool"] : local.logical_components[id].controlled_egress_required == true])
    error_message = "Secret material is forbidden and every workload requires controlled encrypted egress."
  }
}

check "health_semantics_are_distinct" {
  assert {
    condition     = alltrue([for health in values(local.health_contracts) : health.liveness.purpose == "PROCESS_ONLY" && health.liveness.external_provider_dependency == "FORBIDDEN" && health.liveness.database_dependency == "FORBIDDEN" && health.readiness.purpose == "DEPENDENCY_AND_MIGRATION_READINESS" && health.readiness.generic_http_200_inference == "FORBIDDEN" && health.liveness.endpoint_path == null && health.readiness.endpoint_path == null])
    error_message = "Liveness is process-only; readiness must cover dependencies and migration compatibility without invented endpoints."
  }
}

check "waf_and_rate_limits_are_distinct" {
  assert {
    condition     = alltrue([for id in ["waf_public", "waf_admin"] : local.logical_components[id].waf_required && local.logical_components[id].rate_limit_required]) && alltrue([for id in ["rate_limit_public", "rate_limit_admin"] : local.logical_components[id].rate_limit_required])
    error_message = "Public and Admin require distinct WAF and rate-limit declarations."
  }
}

check "observability_canary_and_rollback_are_required" {
  assert {
    condition     = alltrue([for component in values(local.logical_components) : component.observability_required]) && local.logical_components.canary_release_boundary.canary_required && local.logical_components.canary_release_boundary.rollback_required && local.logical_components.rollback_boundary.rollback_required && local.successor_activation_port.complete_gate_evidence == false
    error_message = "Observability and human-gated canary/rollback requirements cannot be weakened."
  }
}

check "permissions_are_wildcard_free_and_actions_zero" {
  assert {
    condition     = alltrue(flatten([for permissions in values(local.identity_permissions) : [for permission in permissions : permission != "*" && !endswith(permission, ":*") && !endswith(permission, ".*")]])) && alltrue([for count in values(local.execution_boundary.planned_actions) : count == 0])
    error_message = "Logical identities must be wildcard-free and infrastructure actions must remain zero."
  }
}
