# Generated by repo://scripts/build_st1503_compute_edge.py; do not edit.
locals {
  reference_architecture = {
    provider = "AWS_REFERENCE_ONLY"
    region   = "ap-northeast-1_REFERENCE_ONLY"
    selected = false
    services = [
      "ECS",
      "Fargate",
      "ECR",
      "ALB",
      "CloudFront",
      "WAF",
      "Route53",
      "ACM",
    ]
  }
  logical_components = {
    registry_supply_chain = {
      component_id = "registry_supply_chain"
      kind         = "IMMUTABLE_IMAGE_SUPPLY_CHAIN"
      reference_services = [
        "ECR",
      ]
      trust_boundary                  = "CONTROL"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = false
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = true
      digest_selection_required       = true
      signed_provenance_required      = true
      sbom_required                   = true
      image_scan_required             = true
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    workload_public_web = {
      component_id = "workload_public_web"
      kind         = "ISOLATED_WORKLOAD"
      reference_services = [
        "ECS",
        "Fargate",
      ]
      trust_boundary                  = "PUBLIC"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = true
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = false
      controlled_egress_required      = true
      transport_encryption_required   = true
      immutable_image_required        = true
      digest_selection_required       = true
      signed_provenance_required      = true
      sbom_required                   = true
      image_scan_required             = true
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = true
      rollback_required               = true
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    workload_admin_web = {
      component_id = "workload_admin_web"
      kind         = "ISOLATED_WORKLOAD"
      reference_services = [
        "ECS",
        "Fargate",
      ]
      trust_boundary                  = "ADMIN"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = true
      service_identity_required       = false
      controlled_egress_required      = true
      transport_encryption_required   = true
      immutable_image_required        = true
      digest_selection_required       = true
      signed_provenance_required      = true
      sbom_required                   = true
      image_scan_required             = true
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = true
      rollback_required               = true
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    workload_core_api = {
      component_id = "workload_core_api"
      kind         = "ISOLATED_WORKLOAD"
      reference_services = [
        "ECS",
        "Fargate",
      ]
      trust_boundary                  = "INTERNAL"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = true
      controlled_egress_required      = true
      transport_encryption_required   = true
      immutable_image_required        = true
      digest_selection_required       = true
      signed_provenance_required      = true
      sbom_required                   = true
      image_scan_required             = true
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = true
      rollback_required               = true
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    workload_worker_pool = {
      component_id = "workload_worker_pool"
      kind         = "ISOLATED_WORKLOAD"
      reference_services = [
        "ECS",
        "Fargate",
      ]
      trust_boundary                  = "INTERNAL"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = true
      controlled_egress_required      = true
      transport_encryption_required   = true
      immutable_image_required        = true
      digest_selection_required       = true
      signed_provenance_required      = true
      sbom_required                   = true
      image_scan_required             = true
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = true
      rollback_required               = true
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    edge_public = {
      component_id = "edge_public"
      kind         = "MANAGED_EDGE"
      reference_services = [
        "CloudFront",
        "WAF",
      ]
      trust_boundary                  = "PUBLIC"
      publicly_addressable            = true
      edge_mediated                   = true
      private_origin                  = true
      public_projection_only          = true
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = false
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = true
      rate_limit_required             = true
      shared_cache_allowed            = true
      observability_required          = true
      canary_required                 = true
      rollback_required               = true
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    edge_admin = {
      component_id = "edge_admin"
      kind         = "MANAGED_EDGE"
      reference_services = [
        "CloudFront",
        "WAF",
      ]
      trust_boundary                  = "ADMIN"
      publicly_addressable            = true
      edge_mediated                   = true
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = true
      service_identity_required       = false
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = true
      rate_limit_required             = true
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = true
      rollback_required               = true
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    ingress_public = {
      component_id = "ingress_public"
      kind         = "PRIVATE_AUTHENTICATED_ORIGIN_INGRESS"
      reference_services = [
        "ALB",
      ]
      trust_boundary                  = "PUBLIC"
      publicly_addressable            = false
      edge_mediated                   = true
      private_origin                  = true
      public_projection_only          = true
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = false
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    ingress_admin = {
      component_id = "ingress_admin"
      kind         = "PRIVATE_AUTHENTICATED_ORIGIN_INGRESS"
      reference_services = [
        "ALB",
      ]
      trust_boundary                  = "ADMIN"
      publicly_addressable            = false
      edge_mediated                   = true
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = true
      service_identity_required       = false
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    ingress_internal = {
      component_id = "ingress_internal"
      kind         = "PRIVATE_SERVICE_INGRESS"
      reference_services = [
        "ALB",
      ]
      trust_boundary                  = "INTERNAL"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = true
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    dns_tls_public = {
      component_id = "dns_tls_public"
      kind         = "DNS_TLS_CERTIFICATE_LIFECYCLE"
      reference_services = [
        "Route53",
        "ACM",
      ]
      trust_boundary                  = "PUBLIC"
      publicly_addressable            = true
      edge_mediated                   = true
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = false
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    dns_tls_admin = {
      component_id = "dns_tls_admin"
      kind         = "DNS_TLS_CERTIFICATE_LIFECYCLE"
      reference_services = [
        "Route53",
        "ACM",
      ]
      trust_boundary                  = "ADMIN"
      publicly_addressable            = true
      edge_mediated                   = true
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = true
      service_identity_required       = false
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    waf_public = {
      component_id = "waf_public"
      kind         = "WAF_ATTACK_POLICY"
      reference_services = [
        "WAF",
      ]
      trust_boundary                  = "PUBLIC"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = false
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = true
      rate_limit_required             = true
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    rate_limit_public = {
      component_id = "rate_limit_public"
      kind         = "DISTINCT_RATE_LIMIT_POLICY"
      reference_services = [
        "WAF",
      ]
      trust_boundary                  = "PUBLIC"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = false
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = true
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    cache_public = {
      component_id = "cache_public"
      kind         = "DISTINCT_CACHE_COOKIE_CSP_POLICY"
      reference_services = [
        "CloudFront",
      ]
      trust_boundary                  = "PUBLIC"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = true
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = false
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = true
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    waf_admin = {
      component_id = "waf_admin"
      kind         = "WAF_ATTACK_POLICY"
      reference_services = [
        "WAF",
      ]
      trust_boundary                  = "ADMIN"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = false
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = true
      rate_limit_required             = true
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    rate_limit_admin = {
      component_id = "rate_limit_admin"
      kind         = "DISTINCT_RATE_LIMIT_POLICY"
      reference_services = [
        "WAF",
      ]
      trust_boundary                  = "ADMIN"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = false
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = true
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    cache_admin = {
      component_id = "cache_admin"
      kind         = "DISTINCT_CACHE_COOKIE_CSP_POLICY"
      reference_services = [
        "CloudFront",
      ]
      trust_boundary                  = "ADMIN"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = true
      service_identity_required       = false
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    identity_public_web = {
      component_id                    = "identity_public_web"
      kind                            = "LEAST_PRIVILEGE_WORKLOAD_IDENTITY"
      reference_services              = []
      trust_boundary                  = "PUBLIC"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = false
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    egress_public_web = {
      component_id                    = "egress_public_web"
      kind                            = "CONTROLLED_DESTINATION_EGRESS_POLICY"
      reference_services              = []
      trust_boundary                  = "PUBLIC"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = false
      controlled_egress_required      = true
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    liveness_public_web = {
      component_id                    = "liveness_public_web"
      kind                            = "PROCESS_LIVENESS_CONTRACT"
      reference_services              = []
      trust_boundary                  = "PUBLIC"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = false
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "PROCESS_ONLY"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    readiness_public_web = {
      component_id                    = "readiness_public_web"
      kind                            = "DEPENDENCY_MIGRATION_READINESS_CONTRACT"
      reference_services              = []
      trust_boundary                  = "PUBLIC"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = false
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "DEPENDENCY_AND_MIGRATION_READINESS"
      external_dependency_in_liveness = false
    }
    identity_admin_web = {
      component_id                    = "identity_admin_web"
      kind                            = "LEAST_PRIVILEGE_WORKLOAD_IDENTITY"
      reference_services              = []
      trust_boundary                  = "ADMIN"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = true
      service_identity_required       = false
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    egress_admin_web = {
      component_id                    = "egress_admin_web"
      kind                            = "CONTROLLED_DESTINATION_EGRESS_POLICY"
      reference_services              = []
      trust_boundary                  = "ADMIN"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = false
      controlled_egress_required      = true
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    liveness_admin_web = {
      component_id                    = "liveness_admin_web"
      kind                            = "PROCESS_LIVENESS_CONTRACT"
      reference_services              = []
      trust_boundary                  = "ADMIN"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = false
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "PROCESS_ONLY"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    readiness_admin_web = {
      component_id                    = "readiness_admin_web"
      kind                            = "DEPENDENCY_MIGRATION_READINESS_CONTRACT"
      reference_services              = []
      trust_boundary                  = "ADMIN"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = false
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "DEPENDENCY_AND_MIGRATION_READINESS"
      external_dependency_in_liveness = false
    }
    identity_core_api = {
      component_id                    = "identity_core_api"
      kind                            = "LEAST_PRIVILEGE_WORKLOAD_IDENTITY"
      reference_services              = []
      trust_boundary                  = "INTERNAL"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = true
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    egress_core_api = {
      component_id                    = "egress_core_api"
      kind                            = "CONTROLLED_DESTINATION_EGRESS_POLICY"
      reference_services              = []
      trust_boundary                  = "INTERNAL"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = false
      controlled_egress_required      = true
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    liveness_core_api = {
      component_id                    = "liveness_core_api"
      kind                            = "PROCESS_LIVENESS_CONTRACT"
      reference_services              = []
      trust_boundary                  = "INTERNAL"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = false
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "PROCESS_ONLY"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    readiness_core_api = {
      component_id                    = "readiness_core_api"
      kind                            = "DEPENDENCY_MIGRATION_READINESS_CONTRACT"
      reference_services              = []
      trust_boundary                  = "INTERNAL"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = false
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "DEPENDENCY_AND_MIGRATION_READINESS"
      external_dependency_in_liveness = false
    }
    identity_worker_pool = {
      component_id                    = "identity_worker_pool"
      kind                            = "LEAST_PRIVILEGE_WORKLOAD_IDENTITY"
      reference_services              = []
      trust_boundary                  = "INTERNAL"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = true
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    egress_worker_pool = {
      component_id                    = "egress_worker_pool"
      kind                            = "CONTROLLED_DESTINATION_EGRESS_POLICY"
      reference_services              = []
      trust_boundary                  = "INTERNAL"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = false
      controlled_egress_required      = true
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    liveness_worker_pool = {
      component_id                    = "liveness_worker_pool"
      kind                            = "PROCESS_LIVENESS_CONTRACT"
      reference_services              = []
      trust_boundary                  = "INTERNAL"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = false
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "PROCESS_ONLY"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    readiness_worker_pool = {
      component_id                    = "readiness_worker_pool"
      kind                            = "DEPENDENCY_MIGRATION_READINESS_CONTRACT"
      reference_services              = []
      trust_boundary                  = "INTERNAL"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = false
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "DEPENDENCY_AND_MIGRATION_READINESS"
      external_dependency_in_liveness = false
    }
    observability_boundary = {
      component_id                    = "observability_boundary"
      kind                            = "LOG_METRIC_TRACE_SECURITY_TELEMETRY"
      reference_services              = []
      trust_boundary                  = "CONTROL"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = false
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = false
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    canary_release_boundary = {
      component_id                    = "canary_release_boundary"
      kind                            = "HUMAN_APPROVED_BOUNDED_CANARY"
      reference_services              = []
      trust_boundary                  = "CONTROL"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = false
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = true
      rollback_required               = true
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
    rollback_boundary = {
      component_id                    = "rollback_boundary"
      kind                            = "HUMAN_APPROVED_IMMUTABLE_ROLLBACK"
      reference_services              = []
      trust_boundary                  = "CONTROL"
      publicly_addressable            = false
      edge_mediated                   = false
      private_origin                  = true
      public_projection_only          = false
      direct_data_plane_access        = false
      approved_identity_required      = false
      service_identity_required       = false
      controlled_egress_required      = false
      transport_encryption_required   = true
      immutable_image_required        = false
      digest_selection_required       = false
      signed_provenance_required      = false
      sbom_required                   = false
      image_scan_required             = false
      secret_material_present         = false
      waf_required                    = false
      rate_limit_required             = false
      shared_cache_allowed            = false
      observability_required          = true
      canary_required                 = false
      rollback_required               = true
      liveness_purpose                = "NOT_APPLICABLE"
      readiness_purpose               = "NOT_APPLICABLE"
      external_dependency_in_liveness = false
    }
  }
  logical_edges = [
    {
      from         = "registry_supply_chain"
      to           = "workload_public_web"
      relationship = "SUPPLIES_IMMUTABLE_IMAGE"
    },
    {
      from         = "identity_public_web"
      to           = "workload_public_web"
      relationship = "AUTHORIZES"
    },
    {
      from         = "egress_public_web"
      to           = "workload_public_web"
      relationship = "CONTROLS_EGRESS"
    },
    {
      from         = "liveness_public_web"
      to           = "workload_public_web"
      relationship = "PROBES_PROCESS_ONLY"
    },
    {
      from         = "readiness_public_web"
      to           = "workload_public_web"
      relationship = "PROBES_DEPENDENCY_AND_MIGRATION"
    },
    {
      from         = "observability_boundary"
      to           = "workload_public_web"
      relationship = "OBSERVES"
    },
    {
      from         = "canary_release_boundary"
      to           = "workload_public_web"
      relationship = "GATES_PROMOTION"
    },
    {
      from         = "rollback_boundary"
      to           = "workload_public_web"
      relationship = "RESTORES_IMMUTABLE_RELEASE"
    },
    {
      from         = "registry_supply_chain"
      to           = "workload_admin_web"
      relationship = "SUPPLIES_IMMUTABLE_IMAGE"
    },
    {
      from         = "identity_admin_web"
      to           = "workload_admin_web"
      relationship = "AUTHORIZES"
    },
    {
      from         = "egress_admin_web"
      to           = "workload_admin_web"
      relationship = "CONTROLS_EGRESS"
    },
    {
      from         = "liveness_admin_web"
      to           = "workload_admin_web"
      relationship = "PROBES_PROCESS_ONLY"
    },
    {
      from         = "readiness_admin_web"
      to           = "workload_admin_web"
      relationship = "PROBES_DEPENDENCY_AND_MIGRATION"
    },
    {
      from         = "observability_boundary"
      to           = "workload_admin_web"
      relationship = "OBSERVES"
    },
    {
      from         = "canary_release_boundary"
      to           = "workload_admin_web"
      relationship = "GATES_PROMOTION"
    },
    {
      from         = "rollback_boundary"
      to           = "workload_admin_web"
      relationship = "RESTORES_IMMUTABLE_RELEASE"
    },
    {
      from         = "registry_supply_chain"
      to           = "workload_core_api"
      relationship = "SUPPLIES_IMMUTABLE_IMAGE"
    },
    {
      from         = "identity_core_api"
      to           = "workload_core_api"
      relationship = "AUTHORIZES"
    },
    {
      from         = "egress_core_api"
      to           = "workload_core_api"
      relationship = "CONTROLS_EGRESS"
    },
    {
      from         = "liveness_core_api"
      to           = "workload_core_api"
      relationship = "PROBES_PROCESS_ONLY"
    },
    {
      from         = "readiness_core_api"
      to           = "workload_core_api"
      relationship = "PROBES_DEPENDENCY_AND_MIGRATION"
    },
    {
      from         = "observability_boundary"
      to           = "workload_core_api"
      relationship = "OBSERVES"
    },
    {
      from         = "canary_release_boundary"
      to           = "workload_core_api"
      relationship = "GATES_PROMOTION"
    },
    {
      from         = "rollback_boundary"
      to           = "workload_core_api"
      relationship = "RESTORES_IMMUTABLE_RELEASE"
    },
    {
      from         = "registry_supply_chain"
      to           = "workload_worker_pool"
      relationship = "SUPPLIES_IMMUTABLE_IMAGE"
    },
    {
      from         = "identity_worker_pool"
      to           = "workload_worker_pool"
      relationship = "AUTHORIZES"
    },
    {
      from         = "egress_worker_pool"
      to           = "workload_worker_pool"
      relationship = "CONTROLS_EGRESS"
    },
    {
      from         = "liveness_worker_pool"
      to           = "workload_worker_pool"
      relationship = "PROBES_PROCESS_ONLY"
    },
    {
      from         = "readiness_worker_pool"
      to           = "workload_worker_pool"
      relationship = "PROBES_DEPENDENCY_AND_MIGRATION"
    },
    {
      from         = "observability_boundary"
      to           = "workload_worker_pool"
      relationship = "OBSERVES"
    },
    {
      from         = "canary_release_boundary"
      to           = "workload_worker_pool"
      relationship = "GATES_PROMOTION"
    },
    {
      from         = "rollback_boundary"
      to           = "workload_worker_pool"
      relationship = "RESTORES_IMMUTABLE_RELEASE"
    },
    {
      from         = "dns_tls_public"
      to           = "edge_public"
      relationship = "TERMINATES_CONTROLLED_TLS"
    },
    {
      from         = "waf_public"
      to           = "edge_public"
      relationship = "PROTECTS"
    },
    {
      from         = "rate_limit_public"
      to           = "edge_public"
      relationship = "RATE_LIMITS"
    },
    {
      from         = "cache_public"
      to           = "edge_public"
      relationship = "GOVERNS_CACHE_COOKIE_CSP"
    },
    {
      from         = "edge_public"
      to           = "ingress_public"
      relationship = "ROUTES_TO_PRIVATE_ORIGIN"
    },
    {
      from         = "observability_boundary"
      to           = "edge_public"
      relationship = "OBSERVES"
    },
    {
      from         = "canary_release_boundary"
      to           = "edge_public"
      relationship = "GATES_PROMOTION"
    },
    {
      from         = "rollback_boundary"
      to           = "edge_public"
      relationship = "RESTORES_IMMUTABLE_RELEASE"
    },
    {
      from         = "dns_tls_admin"
      to           = "edge_admin"
      relationship = "TERMINATES_CONTROLLED_TLS"
    },
    {
      from         = "waf_admin"
      to           = "edge_admin"
      relationship = "PROTECTS"
    },
    {
      from         = "rate_limit_admin"
      to           = "edge_admin"
      relationship = "RATE_LIMITS"
    },
    {
      from         = "cache_admin"
      to           = "edge_admin"
      relationship = "GOVERNS_CACHE_COOKIE_CSP"
    },
    {
      from         = "edge_admin"
      to           = "ingress_admin"
      relationship = "ROUTES_TO_PRIVATE_ORIGIN"
    },
    {
      from         = "observability_boundary"
      to           = "edge_admin"
      relationship = "OBSERVES"
    },
    {
      from         = "canary_release_boundary"
      to           = "edge_admin"
      relationship = "GATES_PROMOTION"
    },
    {
      from         = "rollback_boundary"
      to           = "edge_admin"
      relationship = "RESTORES_IMMUTABLE_RELEASE"
    },
    {
      from         = "ingress_public"
      to           = "workload_public_web"
      relationship = "TARGETS"
    },
    {
      from         = "ingress_admin"
      to           = "workload_admin_web"
      relationship = "TARGETS"
    },
    {
      from         = "ingress_internal"
      to           = "workload_core_api"
      relationship = "TARGETS"
    },
    {
      from         = "workload_admin_web"
      to           = "ingress_internal"
      relationship = "CALLS_PRIVATE_CORE_API"
    },
    {
      from         = "workload_worker_pool"
      to           = "egress_worker_pool"
      relationship = "USES_CONTROLLED_PROVIDER_EGRESS"
    },
  ]
  identity_permissions = {
    identity_public_web = [
      "public_projection.read",
      "telemetry.write",
    ]
    identity_admin_web = [
      "core_api.admin.invoke",
      "telemetry.write",
    ]
    identity_core_api = [
      "data_plane.command",
      "object.metadata.read",
      "queue.send",
      "telemetry.write",
    ]
    identity_worker_pool = [
      "data_plane.job",
      "object.artifact.read",
      "object.artifact.write",
      "provider.egress.invoke",
      "queue.consume",
      "telemetry.write",
    ]
    identity_edge_origin = [
      "origin.admin.invoke",
      "origin.public.invoke",
    ]
  }
  health_contracts = {
    public_web = {
      liveness = {
        purpose                      = "PROCESS_ONLY"
        external_provider_dependency = "FORBIDDEN"
        database_dependency          = "FORBIDDEN"
        generic_http_200_inference   = "FORBIDDEN"
        endpoint_path                = null
        listener_port                = null
        matcher                      = null
      }
      readiness = {
        purpose = "DEPENDENCY_AND_MIGRATION_READINESS"
        required_checks = [
          "REQUIRED_CONFIGURATION",
          "SCHEMA_COMPATIBILITY",
          "DEPENDENCY_AVAILABILITY",
          "KILL_SWITCH_CACHE",
        ]
        generic_http_200_inference = "FORBIDDEN"
        bounded_failure_behavior   = "REQUIRED"
        endpoint_path              = null
        listener_port              = null
        matcher                    = null
      }
    }
    admin_web = {
      liveness = {
        purpose                      = "PROCESS_ONLY"
        external_provider_dependency = "FORBIDDEN"
        database_dependency          = "FORBIDDEN"
        generic_http_200_inference   = "FORBIDDEN"
        endpoint_path                = null
        listener_port                = null
        matcher                      = null
      }
      readiness = {
        purpose = "DEPENDENCY_AND_MIGRATION_READINESS"
        required_checks = [
          "REQUIRED_CONFIGURATION",
          "SCHEMA_COMPATIBILITY",
          "DEPENDENCY_AVAILABILITY",
          "KILL_SWITCH_CACHE",
        ]
        generic_http_200_inference = "FORBIDDEN"
        bounded_failure_behavior   = "REQUIRED"
        endpoint_path              = null
        listener_port              = null
        matcher                    = null
      }
    }
    core_api = {
      liveness = {
        purpose                      = "PROCESS_ONLY"
        external_provider_dependency = "FORBIDDEN"
        database_dependency          = "FORBIDDEN"
        generic_http_200_inference   = "FORBIDDEN"
        endpoint_path                = null
        listener_port                = null
        matcher                      = null
      }
      readiness = {
        purpose = "DEPENDENCY_AND_MIGRATION_READINESS"
        required_checks = [
          "REQUIRED_CONFIGURATION",
          "SCHEMA_COMPATIBILITY",
          "DEPENDENCY_AVAILABILITY",
          "KILL_SWITCH_CACHE",
        ]
        generic_http_200_inference = "FORBIDDEN"
        bounded_failure_behavior   = "REQUIRED"
        endpoint_path              = null
        listener_port              = null
        matcher                    = null
      }
    }
    worker_pool = {
      liveness = {
        purpose                      = "PROCESS_ONLY"
        external_provider_dependency = "FORBIDDEN"
        database_dependency          = "FORBIDDEN"
        generic_http_200_inference   = "FORBIDDEN"
        endpoint_path                = null
        listener_port                = null
        matcher                      = null
      }
      readiness = {
        purpose = "DEPENDENCY_AND_MIGRATION_READINESS"
        required_checks = [
          "REQUIRED_CONFIGURATION",
          "SCHEMA_COMPATIBILITY",
          "DEPENDENCY_AVAILABILITY",
          "KILL_SWITCH_CACHE",
        ]
        generic_http_200_inference = "FORBIDDEN"
        bounded_failure_behavior   = "REQUIRED"
        endpoint_path              = null
        listener_port              = null
        matcher                    = null
      }
    }
  }
  surface_policies = {
    public = {
      trust_boundary                    = "PUBLIC"
      public_projection_only            = true
      shared_cache_allowed              = true
      cookie_boundary                   = "DISTINCT"
      csp_boundary                      = "DISTINCT"
      authentication                    = "NOT_APPLICABLE"
      direct_internal_data_plane_access = "FORBIDDEN"
    }
    admin = {
      trust_boundary                    = "ADMIN"
      public_projection_only            = false
      shared_cache_allowed              = false
      cookie_boundary                   = "DISTINCT"
      csp_boundary                      = "DISTINCT"
      authentication                    = "APPROVED_IDENTITY_REQUIRED_NOT_CONFIGURED"
      direct_internal_data_plane_access = "PRIVATE_CORE_API_ONLY"
    }
    internal = {
      trust_boundary                    = "INTERNAL"
      public_projection_only            = false
      shared_cache_allowed              = false
      cookie_boundary                   = "NOT_APPLICABLE"
      csp_boundary                      = "NOT_APPLICABLE"
      authentication                    = "SERVICE_IDENTITY_REQUIRED_NOT_CONFIGURED"
      direct_internal_data_plane_access = "LEAST_PRIVILEGE_ONLY"
    }
  }
  successor_activation_port = {
    classification                        = "CLOSED_PHYSICAL_COMPUTE_EDGE_ACTIVATION_PORT"
    current_revision_activation           = "FORBIDDEN"
    successor_contract_revision_required  = true
    selected_provider_schema              = null
    selected_provider_plugin              = null
    selected_account_or_project           = null
    selected_region                       = null
    selected_state_backend                = null
    selected_credential_source            = null
    selected_network_segments             = []
    selected_domain_names                 = []
    selected_host_names                   = []
    selected_dns_certificate_references   = []
    selected_image_digests                = []
    selected_workload_identity_references = []
    selected_secret_references            = []
    selected_waf_rule_definitions         = []
    selected_rate_limit_thresholds        = []
    selected_health_endpoint_bindings     = []
    required_gate_evidence = [
      "OD-002_SITE_DOMAIN_RESOLVED",
      "OD-009_BUDGET_AND_CAP_RESOLVED",
      "OD-010_ADMIN_IDENTITY_PROVIDER_RESOLVED",
      "OD-011_ALERT_CHANNEL_AND_ESCALATION_RESOLVED",
      "OD-013_REGION_RESIDENCY_RESOLVED",
      "OD-015_ACCOUNT_CREDENTIAL_EVIDENCE",
      "TST-026_FORMAL_SECURITY_EVIDENCE",
      "TST-027_FORMAL_STAGING_PERFORMANCE_LOAD_EVIDENCE",
      "PROVIDER_SCHEMA_PLUGIN_AND_DISTRIBUTION_PROVENANCE",
      "PRIVATE_NETWORK_ACCOUNT_AND_ORIGIN_ISOLATION_EVIDENCE",
      "IMMUTABLE_IMAGE_DIGEST_SIGNATURE_SBOM_AND_SCAN_EVIDENCE",
      "LEAST_PRIVILEGE_WORKLOAD_IDENTITY_SECRET_AND_EGRESS_REVIEW",
      "DNS_TLS_WAF_RATE_LIMIT_AND_ORIGIN_AUTHENTICATION_EVIDENCE",
      "DISTINCT_LIVENESS_READINESS_AND_MIGRATION_FAILURE_EVIDENCE",
      "OBSERVABILITY_ALERT_OWNER_RUNBOOK_AND_CAPACITY_EVIDENCE",
      "HUMAN_APPROVED_CANARY_PROMOTION_ROLLBACK_AND_RELEASE_EVIDENCE",
    ]
    supplied_gate_evidence            = []
    complete_gate_evidence            = false
    provider_binding                  = "FORBIDDEN_IN_CURRENT_REVISION"
    physical_resource_materialization = "FORBIDDEN_IN_CURRENT_REVISION"
    infrastructure_plan               = "FORBIDDEN"
    infrastructure_apply              = "FORBIDDEN"
  }
  execution_boundary = {
    activation_enabled          = false
    production_apply_authorized = false
    planned_actions = {
      create   = 0
      update   = 0
      delete   = 0
      deploy   = 0
      promote  = 0
      rollback = 0
      route    = 0
      scale    = 0
    }
  }
}
