# Generated by repo://scripts/build_st1503_compute_edge.py; do not edit.
output "reference_architecture" {
  description = "Canonical AWS reference metadata; never a selected provider binding."
  value       = local.reference_architecture
}

output "logical_components" {
  description = "Provider-schema-free logical compute and edge declarations."
  value       = local.logical_components
}

output "logical_edges" {
  description = "Deterministic isolation, routing, identity, health, and release edges."
  value       = local.logical_edges
}

output "identity_permissions" {
  description = "Wildcard-free logical workload permission sets."
  value       = local.identity_permissions
}

output "health_contracts" {
  description = "Distinct logical liveness and readiness semantics with no physical endpoint."
  value       = local.health_contracts
}

output "surface_policies" {
  description = "Distinct Public, Admin, and Internal trust and cache policies."
  value       = local.surface_policies
}

output "activation_boundary" {
  description = "Closed successor activation port and zero-action execution boundary."
  value = {
    successor = local.successor_activation_port
    execution = local.execution_boundary
  }
}
