# Generated by repo://scripts/build_st1503_compute_edge.py; do not edit.
variable "activation_enabled" {
  description = "Current ST-1503 revision keeps this successor binding unset."
  type        = bool
  default     = false

  validation {
    condition     = var.activation_enabled == false
    error_message = "Physical compute-edge activation requires a successor contract and external evidence."
  }
}

variable "production_apply_authorized" {
  description = "Current ST-1503 revision keeps this successor binding unset."
  type        = bool
  default     = false

  validation {
    condition     = var.production_apply_authorized == false
    error_message = "Physical compute-edge activation requires a successor contract and external evidence."
  }
}

variable "selected_provider_schema" {
  description = "Current ST-1503 revision keeps this successor binding unset."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition     = var.selected_provider_schema == null
    error_message = "Physical compute-edge activation requires a successor contract and external evidence."
  }
}

variable "selected_provider_plugin" {
  description = "Current ST-1503 revision keeps this successor binding unset."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition     = var.selected_provider_plugin == null
    error_message = "Physical compute-edge activation requires a successor contract and external evidence."
  }
}

variable "selected_account_or_project" {
  description = "Current ST-1503 revision keeps this successor binding unset."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition     = var.selected_account_or_project == null
    error_message = "Physical compute-edge activation requires a successor contract and external evidence."
  }
}

variable "selected_region" {
  description = "Current ST-1503 revision keeps this successor binding unset."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition     = var.selected_region == null
    error_message = "Physical compute-edge activation requires a successor contract and external evidence."
  }
}

variable "selected_state_backend" {
  description = "Current ST-1503 revision keeps this successor binding unset."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition     = var.selected_state_backend == null
    error_message = "Physical compute-edge activation requires a successor contract and external evidence."
  }
}

variable "selected_credential_source" {
  description = "Current ST-1503 revision keeps this successor binding unset."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition     = var.selected_credential_source == null
    error_message = "Physical compute-edge activation requires a successor contract and external evidence."
  }
}

variable "selected_network_segments" {
  description = "Current ST-1503 revision keeps this successor binding unset."
  type        = list(string)
  default     = []

  validation {
    condition     = length(var.selected_network_segments) == 0
    error_message = "Physical compute-edge activation requires a successor contract and external evidence."
  }
}

variable "selected_domain_names" {
  description = "Current ST-1503 revision keeps this successor binding unset."
  type        = list(string)
  default     = []

  validation {
    condition     = length(var.selected_domain_names) == 0
    error_message = "Physical compute-edge activation requires a successor contract and external evidence."
  }
}

variable "selected_host_names" {
  description = "Current ST-1503 revision keeps this successor binding unset."
  type        = list(string)
  default     = []

  validation {
    condition     = length(var.selected_host_names) == 0
    error_message = "Physical compute-edge activation requires a successor contract and external evidence."
  }
}

variable "selected_dns_certificate_references" {
  description = "Current ST-1503 revision keeps this successor binding unset."
  type        = list(string)
  default     = []

  validation {
    condition     = length(var.selected_dns_certificate_references) == 0
    error_message = "Physical compute-edge activation requires a successor contract and external evidence."
  }
}

variable "selected_image_digests" {
  description = "Current ST-1503 revision keeps this successor binding unset."
  type        = list(string)
  default     = []

  validation {
    condition     = length(var.selected_image_digests) == 0
    error_message = "Physical compute-edge activation requires a successor contract and external evidence."
  }
}

variable "selected_workload_identity_references" {
  description = "Current ST-1503 revision keeps this successor binding unset."
  type        = list(string)
  default     = []

  validation {
    condition     = length(var.selected_workload_identity_references) == 0
    error_message = "Physical compute-edge activation requires a successor contract and external evidence."
  }
}

variable "selected_secret_references" {
  description = "Current ST-1503 revision keeps this successor binding unset."
  type        = list(string)
  default     = []

  validation {
    condition     = length(var.selected_secret_references) == 0
    error_message = "Physical compute-edge activation requires a successor contract and external evidence."
  }
}

variable "selected_waf_rule_definitions" {
  description = "Current ST-1503 revision keeps this successor binding unset."
  type        = list(string)
  default     = []

  validation {
    condition     = length(var.selected_waf_rule_definitions) == 0
    error_message = "Physical compute-edge activation requires a successor contract and external evidence."
  }
}

variable "selected_rate_limit_thresholds" {
  description = "Current ST-1503 revision keeps this successor binding unset."
  type        = list(number)
  default     = []

  validation {
    condition     = length(var.selected_rate_limit_thresholds) == 0
    error_message = "Physical compute-edge activation requires a successor contract and external evidence."
  }
}

variable "selected_health_endpoint_bindings" {
  description = "Current ST-1503 revision keeps this successor binding unset."
  type        = list(string)
  default     = []

  validation {
    condition     = length(var.selected_health_endpoint_bindings) == 0
    error_message = "Physical compute-edge activation requires a successor contract and external evidence."
  }
}

variable "supplied_gate_evidence" {
  description = "Current ST-1503 revision keeps this successor binding unset."
  type        = set(string)
  default     = []

  validation {
    condition     = length(var.supplied_gate_evidence) == 0
    error_message = "Physical compute-edge activation requires a successor contract and external evidence."
  }
}
