# Generated by repo://scripts/build_st1501_terraform_foundation.py; do not edit.
check "execution_is_disabled" {
  assert {
    condition     = var.activation_enabled == false && var.production_apply_authorized == false
    error_message = "Activation and Production apply authority must remain disabled."
  }
}

check "all_infrastructure_bindings_are_unset" {
  assert {
    condition = alltrue([
      for value in values(local.selected_configuration) : value == null
    ])
    error_message = "All provider, account, region, plugin, backend, and credential bindings must remain unset."
  }
}

check "capability_admission_is_closed" {
  assert {
    condition     = length(var.capability_mappings) == 0 && local.admission_boundary.eligible == false
    error_message = "Capability mappings require complete successor evidence and approval."
  }
}

check "planned_actions_are_zero" {
  assert {
    condition = alltrue([
      for count in values(local.execution_boundary.planned_actions) : count == 0
    ])
    error_message = "Validation-only HCL cannot plan infrastructure actions."
  }
}
