# Generated by repo://scripts/build_st1501_terraform_foundation.py; do not edit.
locals {
  reference_architecture = {
    cloud               = "AWS"
    region              = "ap-northeast-1"
    classification      = "CURRENT_CANONICAL_REFERENCE_ARCHITECTURE_ONLY"
    inherited_from      = "INT-DEC-007"
    reference_only      = true
    selected_binding    = false
    admission_shortcut  = false
    evidence_substitute = false
  }

  required_capability_ids = [
    "iac_toolchain_and_plugin_provenance",
    "remote_state_integrity_and_recovery",
    "environment_tenant_isolation",
    "network_segmentation_and_traffic_control",
    "workload_identity_and_secret_boundary",
    "observability_audit_and_drift_detection",
    "infrastructure_backup_restore_and_recovery",
    "cost_budget_alert_and_stop_controls",
    "region_and_data_residency",
    "human_approved_change_and_rollback",
  ]

  selected_configuration = {
    profile_id         = var.selected_profile_id
    profile_kind       = var.selected_profile_kind
    provider_name      = var.selected_provider_name
    account_or_project = var.selected_account_or_project
    primary_region     = var.selected_primary_region
    backup_region      = var.selected_backup_region
    provider_plugin    = var.selected_provider_plugin
    state_backend      = var.selected_state_backend
    credential_source  = var.credential_source
  }

  admission_boundary = {
    status                     = "NOT_EVALUATED"
    eligible                   = false
    required_capability_ids    = local.required_capability_ids
    configured_mapping_count   = length(var.capability_mappings)
    complete_mapping           = false
    implicit_binding           = "FORBIDDEN"
    provider_label_as_evidence = "FORBIDDEN"
  }

  execution_boundary = {
    activation_enabled          = var.activation_enabled
    production_apply_authorized = var.production_apply_authorized
    provider_calls              = "FORBIDDEN"
    external_writes             = "FORBIDDEN"
    planned_actions = {
      create = 0
      update = 0
      delete = 0
    }
  }
}
