# Generated by repo://scripts/build_st1501_terraform_foundation.py; do not edit.
output "reference_architecture" {
  description = "Canonical AWS Tokyo reference metadata; never a selected binding."
  value       = local.reference_architecture
}

output "foundation_admission" {
  description = "Fail-closed provider-neutral capability admission state."
  value       = local.admission_boundary
}

output "selected_configuration" {
  description = "All fields remain null in this validation-only module revision."
  value       = local.selected_configuration
}

output "execution_boundary" {
  description = "Disabled execution authority and exact zero action counts."
  value       = local.execution_boundary
}
