# Generated by repo://scripts/build_st1501_terraform_foundation.py; do not edit.
variable "activation_enabled" {
  description = "Must remain false while OD-013 and Production approval are unresolved."
  type        = bool
  default     = false

  validation {
    condition     = var.activation_enabled == false
    error_message = "ST-1501 activation must remain disabled."
  }
}

variable "selected_profile_id" {
  description = "No foundation profile may be selected by this module revision."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition     = var.selected_profile_id == null
    error_message = "A selected profile requires a successor contract and approval."
  }
}

variable "selected_profile_kind" {
  description = "No provider kind may be selected by this module revision."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition     = var.selected_profile_kind == null
    error_message = "A selected profile kind requires a successor contract and approval."
  }
}

variable "selected_provider_name" {
  description = "No infrastructure provider may be selected by this module revision."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition     = var.selected_provider_name == null
    error_message = "A provider selection requires a successor contract and approval."
  }
}

variable "selected_account_or_project" {
  description = "No account, project, or tenant may be selected by this module revision."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition     = var.selected_account_or_project == null
    error_message = "An account, project, or tenant requires distinct approval."
  }
}

variable "selected_primary_region" {
  description = "The AWS Tokyo reference is metadata and is never a selected region."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition     = var.selected_primary_region == null
    error_message = "A primary region requires OD-013 approval."
  }
}

variable "selected_backup_region" {
  description = "No backup region may be selected while OD-013 is unresolved."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition     = var.selected_backup_region == null
    error_message = "A backup region requires OD-013 approval."
  }
}

variable "selected_provider_plugin" {
  description = "The validation-only module requires and selects no provider plugin."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition     = var.selected_provider_plugin == null
    error_message = "A provider plugin requires a successor resource module."
  }
}

variable "selected_state_backend" {
  description = "No local or remote state backend is selected by this module revision."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition     = var.selected_state_backend == null
    error_message = "A state backend requires separate security and recovery evidence."
  }
}

variable "credential_source" {
  description = "Validation never accepts or inherits an infrastructure credential source."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition     = var.credential_source == null
    error_message = "Credential access is forbidden in the validation-only module."
  }
}

variable "capability_mappings" {
  description = "Mappings remain empty until a successor contract supplies complete evidence."
  type = map(object({
    implementation_ref = string
    evidence_refs      = set(string)
  }))
  default = {}

  validation {
    condition     = length(var.capability_mappings) == 0
    error_message = "Capability mappings require a successor contract and equivalent evidence."
  }
}

variable "production_apply_authorized" {
  description = "Repository-local validation can never grant Production apply authority."
  type        = bool
  default     = false

  validation {
    condition     = var.production_apply_authorized == false
    error_message = "Production apply requires a separate human-gated release action."
  }
}
