"""Executable HCL, toolchain provenance, and offline admission tests for ST-1501."""

from __future__ import annotations

import copy
import json
import subprocess
from pathlib import Path
from typing import Any

import pytest

from scripts import build_st1501_terraform_foundation as generator


REPOSITORY_ROOT = Path(__file__).resolve().parents[2]


def _validate(document: dict[str, Any]) -> generator.FoundationModel:
    return generator.validate_contract(document, REPOSITORY_ROOT)


def test_toolchain_and_hcl_contracts_are_exact_and_provider_neutral(
    foundation_model: generator.FoundationModel,
) -> None:
    assert (
        foundation_model.toolchain.definition == generator.EXPECTED_VALIDATION_TOOLCHAIN
    )
    assert foundation_model.hcl_module.definition == generator.EXPECTED_HCL_MODULE
    assert foundation_model.toolchain.definition["validation_boundary"] == {
        "binary_acquisition": "EXPLICIT_ONLINE_MAINTENANCE_ONLY",
        "normal_check_network_access": "FORBIDDEN",
        "network_namespace": "REQUIRED",
        "initialization": "FORBIDDEN",
        "provider_installation": "FORBIDDEN",
        "provider_plugins": [],
        "module_downloads": "FORBIDDEN",
        "backend_access": "FORBIDDEN",
        "credential_inheritance": "FORBIDDEN",
        "repository_writes": "FORBIDDEN",
        "allowed_commands": list(generator.VALIDATION_COMMANDS),
        "forbidden_commands": list(generator.FORBIDDEN_TOOL_COMMANDS),
    }


def test_toolchain_lock_is_source_derived_and_grants_no_apply_authority(
    foundation_model: generator.FoundationModel,
) -> None:
    lock = json.loads((REPOSITORY_ROOT / generator.TOOLCHAIN_LOCK_PATH).read_bytes())
    assert lock == json.loads(generator.render_toolchain_lock(foundation_model))
    assert lock["toolchain"] == generator.EXPECTED_VALIDATION_TOOLCHAIN
    assert lock["module"] == {
        "path": "infra/terraform/foundation",
        "required_version": "= 1.15.9",
        "provider_requirements": [],
        "provider_lock": "ABSENT_BY_DESIGN_NO_PROVIDER_REQUIRED_OR_SELECTED",
        "backend": "ABSENT",
        "resources": [],
    }
    assert set(lock["authority_boundary"].values()) == {
        "FORBIDDEN",
        "NOT_EXECUTED",
    }


def test_generated_hcl_bundle_matches_closed_file_and_block_inventory(
    foundation_model: generator.FoundationModel,
) -> None:
    bundle = generator.render_hcl_bundle(foundation_model)
    generator.validate_hcl_bundle(bundle)
    assert tuple(bundle) == generator.HCL_PATHS
    for relative, content in bundle.items():
        assert (REPOSITORY_ROOT / relative).read_bytes() == content
        observed = tuple(
            generator.HCL_TOP_LEVEL_BLOCK_PATTERN.findall(content.decode("utf-8"))
        )
        assert observed == generator.HCL_ALLOWED_BLOCKS_BY_FILE[relative.name]
    assert b"hashicorp/aws" not in b"".join(bundle.values())
    assert b'provider "' not in b"".join(bundle.values())
    assert b'resource "' not in b"".join(bundle.values())
    assert b'backend "' not in b"".join(bundle.values())


@pytest.mark.parametrize(
    "hostile_block",
    (
        'provider "aws" {}',
        'resource "aws_s3_bucket" "hostile" {}',
        'data "aws_caller_identity" "hostile" {}',
        'module "hostile" {}',
        'backend "s3" {}',
        "cloud {}",
        "import {}",
    ),
)
def test_hcl_policy_rejects_provider_backend_resource_and_import_blocks(
    foundation_model: generator.FoundationModel, hostile_block: str
) -> None:
    bundle = generator.render_hcl_bundle(foundation_model)
    relative = generator.HCL_PATHS[-1]
    hostile = bundle[relative] + f"\n{hostile_block}\n".encode()
    with pytest.raises(generator.FoundationContractError) as captured:
        generator.validate_hcl_file_policy(relative, hostile)
    assert captured.value.code == "HCL_FORBIDDEN_BLOCK"


@pytest.mark.parametrize(
    "fragment",
    (
        "local-exec",
        "remote-exec",
        "terraform_remote_state",
        "registry.terraform.io/",
        "hashicorp/aws",
        "http://",
    ),
)
def test_hcl_policy_rejects_forbidden_provider_or_execution_fragments(
    foundation_model: generator.FoundationModel, fragment: str
) -> None:
    bundle = generator.render_hcl_bundle(foundation_model)
    relative = generator.HCL_PATHS[-1]
    hostile = bundle[relative].replace(
        b"# Generated by",
        f"# {fragment}\n# Generated by".encode(),
        1,
    )
    with pytest.raises(generator.FoundationContractError) as captured:
        generator.validate_hcl_file_policy(relative, hostile)
    assert captured.value.code == "HCL_FORBIDDEN_OPERATION"


def test_hcl_policy_rejects_file_inventory_and_tool_version_drift(
    foundation_model: generator.FoundationModel,
) -> None:
    bundle = generator.render_hcl_bundle(foundation_model)
    missing = dict(bundle)
    missing.pop(generator.HCL_PATHS[-1])
    with pytest.raises(generator.FoundationContractError) as captured:
        generator.validate_hcl_bundle(missing)
    assert captured.value.code == "HCL_FILE_INVENTORY_DRIFT"

    versions = generator.HCL_PATHS[0]
    drifted = bundle[versions].replace(b"= 1.15.9", b"= 1.15.8")
    with pytest.raises(generator.FoundationContractError) as captured:
        generator.validate_hcl_file_policy(versions, drifted)
    assert captured.value.code == "HCL_TOOL_VERSION_DRIFT"


@pytest.mark.parametrize(
    ("section", "field", "value"),
    (
        ("iac_validation_toolchain", "version", "1.15.8"),
        (
            "iac_validation_toolchain",
            "required_version_constraint",
            ">= 1.15.9",
        ),
        ("hcl_foundation_module", "provider_requirements", ["aws"]),
        ("hcl_foundation_module", "resource_blocks", ["aws_s3_bucket"]),
        ("hcl_foundation_module", "backend_blocks", ["s3"]),
        ("hcl_foundation_module", "default_disabled", False),
    ),
)
def test_toolchain_and_hcl_policy_contract_mutations_fail_closed(
    contract_document: dict[str, Any], section: str, field: str, value: object
) -> None:
    document = copy.deepcopy(contract_document)
    document[section][field] = value
    with pytest.raises(generator.FoundationContractError):
        _validate(document)


def test_toolchain_integrity_and_network_policy_mutations_fail_closed(
    contract_document: dict[str, Any],
) -> None:
    digest_drift = copy.deepcopy(contract_document)
    digest_drift["iac_validation_toolchain"]["official_release"][
        "extracted_binary_sha256"
    ] = "0" * 64
    with pytest.raises(generator.FoundationContractError) as captured:
        _validate(digest_drift)
    assert captured.value.code == "FIXED_VALUE_VIOLATION"

    network_drift = copy.deepcopy(contract_document)
    network_drift["iac_validation_toolchain"]["validation_boundary"][
        "normal_check_network_access"
    ] = "ALLOWED"
    with pytest.raises(generator.FoundationContractError) as captured:
        _validate(network_drift)
    assert captured.value.code == "FIXED_VALUE_VIOLATION"

    command_drift = copy.deepcopy(contract_document)
    command_drift["iac_validation_toolchain"]["validation_boundary"][
        "allowed_commands"
    ].append("plan")
    with pytest.raises(generator.FoundationContractError) as captured:
        _validate(command_drift)
    assert captured.value.code == "FIXED_VALUE_VIOLATION"


@pytest.mark.parametrize(
    "arguments",
    (
        ("init",),
        ("plan",),
        ("apply", "-auto-approve"),
        ("destroy",),
        ("validate",),
        ("fmt", "-write=true"),
    ),
)
def test_native_runner_rejects_every_non_allowlisted_command_before_execution(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path, arguments: tuple[str, ...]
) -> None:
    def unexpected_run(*_args: object, **_kwargs: object) -> None:
        raise AssertionError("subprocess must not run for a forbidden command")

    monkeypatch.setattr(generator.subprocess, "run", unexpected_run)
    with pytest.raises(generator.FoundationContractError) as captured:
        generator._native_command(
            Path("/usr/bin/unshare"),
            Path("/verified/terraform"),
            arguments,
            working_directory=tmp_path,
            data_directory=tmp_path,
        )
    assert captured.value.code == "NATIVE_VALIDATOR_COMMAND_FORBIDDEN"


def test_native_runner_uses_exact_network_namespace_command_and_closed_env(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    observed: dict[str, object] = {}

    def fake_run(
        command: tuple[str, ...], **kwargs: object
    ) -> subprocess.CompletedProcess[bytes]:
        observed["command"] = command
        observed.update(kwargs)
        return subprocess.CompletedProcess(command, 0, stdout=b"{}", stderr=b"")

    monkeypatch.setattr(generator.subprocess, "run", fake_run)
    output = generator._native_command(
        Path("/usr/bin/unshare"),
        Path("/verified/terraform"),
        ("version", "-json"),
        working_directory=tmp_path,
        data_directory=tmp_path / "data",
    )
    assert output == b"{}"
    assert observed["command"] == (
        "/usr/bin/unshare",
        "--user",
        "--map-root-user",
        "--net",
        "--",
        "/verified/terraform",
        "version",
        "-json",
    )
    assert observed["cwd"] == tmp_path
    assert observed["check"] is False
    assert observed["capture_output"] is True
    assert observed["timeout"] == 30
    assert observed["env"] == {
        "CHECKPOINT_DISABLE": "1",
        "LANG": "C.UTF-8",
        "LC_ALL": "C.UTF-8",
        "TF_DATA_DIR": str(tmp_path / "data"),
        "TF_IN_AUTOMATION": "1",
        "TF_INPUT": "0",
        "TF_REGISTRY_CLIENT_TIMEOUT": "1",
        "TF_REGISTRY_DISCOVERY_RETRY": "0",
    }


def test_native_runner_rejects_alternate_namespace_runner_before_execution(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    monkeypatch.setattr(
        generator.subprocess,
        "run",
        lambda *_args, **_kwargs: pytest.fail("unexpected subprocess"),
    )
    with pytest.raises(generator.FoundationContractError) as captured:
        generator._native_command(
            Path("/tmp/unshare"),
            Path("/verified/terraform"),
            ("version", "-json"),
            working_directory=tmp_path,
            data_directory=tmp_path,
        )
    assert captured.value.code == "NETWORK_NAMESPACE_RUNNER_FORBIDDEN"


def test_native_validation_rejects_unpinned_binary_before_execution(
    monkeypatch: pytest.MonkeyPatch, tmp_path: Path
) -> None:
    binary = tmp_path / "terraform"
    binary.write_bytes(b"not-the-pinned-validator")
    monkeypatch.setattr(
        generator.subprocess,
        "run",
        lambda *_args, **_kwargs: pytest.fail("unexpected subprocess"),
    )
    with pytest.raises(generator.FoundationContractError) as captured:
        generator.verify_native_hcl(REPOSITORY_ROOT, binary)
    assert captured.value.code == "NATIVE_VALIDATOR_DIGEST_MISMATCH"


def test_normal_check_never_invokes_native_runner(
    monkeypatch: pytest.MonkeyPatch,
) -> None:
    monkeypatch.setattr(
        generator.subprocess,
        "run",
        lambda *_args, **_kwargs: pytest.fail("normal check invoked subprocess"),
    )
    generator.build(REPOSITORY_ROOT, check=True)
