-- Generated by scripts/build_st0307_migration_fixtures.py; do not edit.
-- Source: changes/st-0307/contracts/migration-upgrade-fixtures.v1.yaml
-- Command: uv run --locked --no-sync --no-env-file python scripts/build_st0307_migration_fixtures.py
-- Fixture: ST0307-V01-JOB-ALIGNMENT
-- Apply boundary: {"completed_forward_checkpoints":[],"production_revision":null,"source_kind":"UPSTREAM_BASELINE_MEMBER","source_ref":"docs/upstream/RAOS_03_data_model_package_v0.1.zip#sql/RAOS_03_001_baseline_v0.1.sql"}
-- Synthetic test data only. Disposable PostgreSQL 18.4 database only.
-- This file is not an Alembic revision and must never enter the production runner.

BEGIN;
DO $st0307$
BEGIN
    IF current_setting('server_version_num')::integer <> 180004 THEN
        RAISE EXCEPTION 'ST-0307 requires PostgreSQL server_version_num 180004';
    END IF;
END
$st0307$;

INSERT INTO ops.job (
    display_id, job_type, queue_name, status, completed_at,
    created_by_actor_type
)
VALUES
    ('ST0307-JOB-PENDING', 'ops.st0307_job_alignment.v1', 'st0307', 'PENDING', NULL, 'SYSTEM'),
    ('ST0307-JOB-READY', 'ops.st0307_job_alignment.v1', 'st0307', 'READY', NULL, 'SYSTEM'),
    ('ST0307-JOB-RUNNING', 'ops.st0307_job_alignment.v1', 'st0307', 'RUNNING', NULL, 'SYSTEM'),
    ('ST0307-JOB-SUCCEEDED', 'ops.st0307_job_alignment.v1', 'st0307', 'SUCCEEDED', TIMESTAMPTZ '2026-08-05 00:00:00+00', 'SYSTEM'),
    ('ST0307-JOB-FAILED', 'ops.st0307_job_alignment.v1', 'st0307', 'FAILED', TIMESTAMPTZ '2026-08-05 00:01:00+00', 'SYSTEM'),
    ('ST0307-JOB-CANCELLED', 'ops.st0307_job_alignment.v1', 'st0307', 'CANCELLED', TIMESTAMPTZ '2026-08-05 00:02:00+00', 'SYSTEM'),
    ('ST0307-JOB-QUARANTINED', 'ops.st0307_job_alignment.v1', 'st0307', 'QUARANTINED', TIMESTAMPTZ '2026-08-05 00:03:00+00', 'SYSTEM');

COMMIT;
