-- Generated by scripts/build_st0307_migration_fixtures.py; do not edit.
-- Source: changes/st-0307/contracts/migration-upgrade-fixtures.v1.yaml
-- Command: uv run --locked --no-sync --no-env-file python scripts/build_st0307_migration_fixtures.py
-- Fixture: ST0307-V02-AI-ALIGNMENT
-- Apply boundary: {"completed_forward_checkpoints":["202607300001","202607300002","202607300003","202607300004","202607300005"],"production_revision":null,"source_kind":"FINALIZED_ALIGNMENT_CHECKPOINT_STATE","source_ref":"changes/st-0002/manifest.yaml"}
-- Synthetic test data only. Disposable PostgreSQL 18.4 database only.
-- This file is not an Alembic revision and must never enter the production runner.

BEGIN;
DO $st0307$
BEGIN
    IF current_setting('server_version_num')::integer <> 180004 THEN
        RAISE EXCEPTION 'ST-0307 requires PostgreSQL server_version_num 180004';
    END IF;
END
$st0307$;

INSERT INTO iam.principal (
    id, display_id, principal_type, status, display_name
)
VALUES (
    '00000000-0000-7000-8000-000000000307',
    'PRN-ST0307-LEGACY-AUTHOR', 'USER', 'ACTIVE',
    'Synthetic legacy prompt author'
);

SET LOCAL session_replication_role = replica;

INSERT INTO ai.ai_job (
    display_id, ops_job_id, task_definition_id, article_plan_id,
    source_packet_version_id, prompt_version_id, output_schema_version_id,
    model_route_version_id, status, max_cost_jpy, completed_at
)
VALUES
    ('AIJ-ST0307-PENDING', uuidv7(), uuidv7(), uuidv7(), uuidv7(), uuidv7(), uuidv7(), uuidv7(), 'PENDING', 100, NULL),
    ('AIJ-ST0307-FAILED', uuidv7(), uuidv7(), uuidv7(), uuidv7(), uuidv7(), uuidv7(), uuidv7(), 'FAILED', 100, TIMESTAMPTZ '2026-08-05 00:10:00+00'),
    ('AIJ-ST0307-BLOCKED', uuidv7(), uuidv7(), uuidv7(), uuidv7(), uuidv7(), uuidv7(), uuidv7(), 'BLOCKED', 100, TIMESTAMPTZ '2026-08-05 00:11:00+00');

INSERT INTO ai.prompt_version (
    display_id, task_definition_id, prompt_code, version_no,
    git_path, git_commit_sha, template_sha256, status
)
VALUES (
    'PRM-ST0307-REJECTED', uuidv7(), 'PROMPT-ST0307-REJECTED', 1,
    'prompts/st0307-rejected.md', repeat('c', 40), repeat('d', 64),
    'REJECTED'
);

SET LOCAL session_replication_role = origin;
COMMIT;
