"""Install the exact ST-0303 IAM/OPS table contract.

Revision ID: 202608030003
Revises: 202608030002
Create Date: 2026-08-03

RAOS metadata:
- story: ST-0303
- requirement IDs: FR-019, FR-020
- architecture: MIG-001 SLICE-004/SLICE-005/SLICE-007 IAM/OPS subset
- runner version: 1.2.0
- server version: 180004
- risk class: B (additive tables, constraints, indexes, and triggers)
- estimated lock: additive catalog DDL; guarded ACCESS EXCLUSIVE on downgrade
- backfill job: none
- rollback category: reversible only while all 17 owned tables are empty; RESTRICT
"""

from __future__ import annotations

from collections.abc import Sequence

from alembic import op


revision: str = "202608030003"
down_revision: str | None = "202608030002"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


UPGRADE_STATEMENTS: tuple[str, ...] = (
    "SET LOCAL search_path = pg_catalog",
    "SET LOCAL TIME ZONE 'UTC'",
    "CREATE TABLE ops.object_artifact (\n    id pg_catalog.uuid DEFAULT pg_catalog.uuidv7() NOT NULL,\n    display_id pg_catalog.text NOT NULL,\n    artifact_kind pg_catalog.text NOT NULL,\n    storage_provider pg_catalog.text DEFAULT 's3' NOT NULL,\n    bucket_name pg_catalog.text NOT NULL,\n    object_key pg_catalog.text NOT NULL,\n    object_version pg_catalog.text,\n    content_type pg_catalog.text NOT NULL,\n    byte_size pg_catalog.int8 NOT NULL,\n    sha256 pg_catalog.text NOT NULL,\n    encryption_state pg_catalog.text NOT NULL,\n    retention_class pg_catalog.text NOT NULL,\n    is_immutable pg_catalog.bool DEFAULT true NOT NULL,\n    source_system pg_catalog.text NOT NULL,\n    acquired_at pg_catalog.timestamptz,\n    created_by_principal_id pg_catalog.uuid,\n    metadata pg_catalog.jsonb DEFAULT '{}'::jsonb NOT NULL,\n    created_at pg_catalog.timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    CONSTRAINT pk_ops_object_artifact PRIMARY KEY (id),\n    CONSTRAINT uq_ops_object_artifact_display_id UNIQUE (display_id),\n    CONSTRAINT ck_ops_object_artifact_kind CHECK (artifact_kind IN ('raw_provider_response', 'raw_primary_source', 'source_snapshot', 'source_packet', 'ai_input', 'ai_output', 'publication_snapshot', 'revenue_original', 'revenue_rejects', 'audit_export', 'quality_report', 'diff', 'import_report', 'other')),\n    CONSTRAINT ck_ops_object_artifact_size CHECK (byte_size >= 0),\n    CONSTRAINT ck_ops_object_artifact_sha CHECK (sha256 ~ '^[0-9a-f]{64}$'),\n    CONSTRAINT ck_ops_object_artifact_enc CHECK (encryption_state IN ('SSE_KMS', 'SSE_S3', 'LOCAL_DEV')),\n    CONSTRAINT ck_ops_object_artifact_meta CHECK (pg_catalog.jsonb_typeof(metadata) = 'object')\n)",
    "COMMENT ON TABLE ops.object_artifact IS 'S3互換Object Storage上の原本・入力・出力・公開Snapshotを登録する不変レジストリ。'",
    "COMMENT ON COLUMN ops.object_artifact.id IS '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'",
    "COMMENT ON COLUMN ops.object_artifact.display_id IS 'OBJ-接頭辞を持つアプリケーション生成の不変表示ID。'",
    "COMMENT ON COLUMN ops.object_artifact.artifact_kind IS 'raw_provider_response、source_snapshot、source_packet、ai_input、ai_output、publication_snapshot、revenue_original、audit_export等。'",
    "COMMENT ON COLUMN ops.object_artifact.storage_provider IS 'storage provider'",
    "COMMENT ON COLUMN ops.object_artifact.bucket_name IS 'bucket name'",
    "COMMENT ON COLUMN ops.object_artifact.object_key IS 'object key'",
    "COMMENT ON COLUMN ops.object_artifact.object_version IS 'Object VersioningのVersion ID。ローカル環境ではNULL可。'",
    "COMMENT ON COLUMN ops.object_artifact.content_type IS 'content type'",
    "COMMENT ON COLUMN ops.object_artifact.byte_size IS 'byte size'",
    "COMMENT ON COLUMN ops.object_artifact.sha256 IS 'sha256'",
    "COMMENT ON COLUMN ops.object_artifact.encryption_state IS 'encryption state'",
    "COMMENT ON COLUMN ops.object_artifact.retention_class IS 'retention class'",
    "COMMENT ON COLUMN ops.object_artifact.is_immutable IS 'is immutable'",
    "COMMENT ON COLUMN ops.object_artifact.source_system IS 'source system'",
    "COMMENT ON COLUMN ops.object_artifact.acquired_at IS 'acquired at'",
    "COMMENT ON COLUMN ops.object_artifact.created_by_principal_id IS '作成操作を行ったIAM Principal。'",
    "COMMENT ON COLUMN ops.object_artifact.metadata IS 'Objectタグ、parser、provider request ID等。秘密・原本文は含めない。'",
    "COMMENT ON COLUMN ops.object_artifact.created_at IS 'レコード作成時刻。UTCのtimestamptz。'",
    "REVOKE ALL ON TABLE ops.object_artifact FROM PUBLIC",
    "CREATE TABLE ops.job (\n    id pg_catalog.uuid DEFAULT pg_catalog.uuidv7() NOT NULL,\n    display_id pg_catalog.text NOT NULL,\n    job_type pg_catalog.text NOT NULL,\n    queue_name pg_catalog.text NOT NULL,\n    status pg_catalog.text DEFAULT 'REQUESTED' NOT NULL,\n    priority pg_catalog.int2 DEFAULT 50 NOT NULL,\n    idempotency_key pg_catalog.text,\n    site_id pg_catalog.uuid,\n    aggregate_type pg_catalog.text,\n    aggregate_id pg_catalog.uuid,\n    payload pg_catalog.jsonb DEFAULT '{}'::jsonb NOT NULL,\n    payload_artifact_id pg_catalog.uuid,\n    scheduled_at pg_catalog.timestamptz,\n    available_at pg_catalog.timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    started_at pg_catalog.timestamptz,\n    completed_at pg_catalog.timestamptz,\n    max_attempts pg_catalog.int2 DEFAULT 5 NOT NULL,\n    attempt_count pg_catalog.int2 DEFAULT 0 NOT NULL,\n    lease_owner pg_catalog.text,\n    lease_expires_at pg_catalog.timestamptz,\n    correlation_id pg_catalog.uuid DEFAULT pg_catalog.uuidv7() NOT NULL,\n    causation_id pg_catalog.uuid,\n    parent_job_id pg_catalog.uuid,\n    budget_jpy pg_catalog.int8,\n    created_by_actor_type pg_catalog.text NOT NULL,\n    created_by_actor_id pg_catalog.uuid,\n    last_error_class pg_catalog.text,\n    last_error_code pg_catalog.text,\n    last_error_message pg_catalog.text,\n    created_at pg_catalog.timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    updated_at pg_catalog.timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    lock_version pg_catalog.int8 DEFAULT 0 NOT NULL,\n    job_version pg_catalog.int2 DEFAULT 1 NOT NULL,\n    deadline_at pg_catalog.timestamptz,\n    cancel_requested_at pg_catalog.timestamptz,\n    CONSTRAINT pk_ops_job PRIMARY KEY (id),\n    CONSTRAINT uq_ops_job_display_id UNIQUE (display_id),\n    CONSTRAINT ck_ops_job_status CHECK (status IN ('REQUESTED', 'QUEUED', 'RUNNING', 'SUCCEEDED', 'FAILED_RETRYABLE', 'RETRY_SCHEDULED', 'FAILED_TERMINAL', 'QUARANTINED', 'CANCELLED', 'EXPIRED')),\n    CONSTRAINT ck_ops_job_priority CHECK (priority BETWEEN 0 AND 100),\n    CONSTRAINT ck_ops_job_attempts CHECK (max_attempts BETWEEN 1 AND 50 AND attempt_count BETWEEN 0 AND max_attempts),\n    CONSTRAINT ck_ops_job_budget CHECK (budget_jpy IS NULL OR budget_jpy >= 0),\n    CONSTRAINT ck_ops_job_payload CHECK (pg_catalog.jsonb_typeof(payload) = 'object'),\n    CONSTRAINT ck_ops_job_lease_pair CHECK ((lease_owner IS NULL) = (lease_expires_at IS NULL)),\n    CONSTRAINT ck_ops_job_completion CHECK (status NOT IN ('SUCCEEDED', 'FAILED_TERMINAL', 'QUARANTINED', 'CANCELLED', 'EXPIRED') OR completed_at IS NOT NULL),\n    CONSTRAINT ck_ops_job_version CHECK (lock_version >= 0),\n    CONSTRAINT ck_ops_job_version_positive CHECK (job_version >= 1),\n    CONSTRAINT ck_ops_job_deadline_order CHECK (deadline_at IS NULL OR deadline_at > created_at),\n    CONSTRAINT ck_ops_job_cancel_request CHECK (cancel_requested_at IS NULL OR status <> 'SUCCEEDED')\n)",
    "COMMENT ON TABLE ops.job IS '非同期作業の業務上の正本。Scheduler、API、Eventから作成され、Attemptとは分離する。'",
    "COMMENT ON COLUMN ops.job.id IS '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'",
    "COMMENT ON COLUMN ops.job.display_id IS 'JOB-接頭辞を持つアプリケーション生成の不変表示ID。'",
    "COMMENT ON COLUMN ops.job.job_type IS 'job type'",
    "COMMENT ON COLUMN ops.job.queue_name IS 'queue name'",
    "COMMENT ON COLUMN ops.job.status IS '業務状態を示す安定Enum文字列。'",
    "COMMENT ON COLUMN ops.job.priority IS 'priority'",
    "COMMENT ON COLUMN ops.job.idempotency_key IS 'idempotency key'",
    "COMMENT ON COLUMN ops.job.site_id IS '対象サイト。MVPは1サイトだが将来の複数サイトを識別可能にする。'",
    "COMMENT ON COLUMN ops.job.aggregate_type IS 'aggregate type'",
    "COMMENT ON COLUMN ops.job.aggregate_id IS 'aggregate id'",
    "COMMENT ON COLUMN ops.job.payload IS '小さなCommand payload。大容量入力はpayload_artifact_idへ分離する。'",
    "COMMENT ON COLUMN ops.job.payload_artifact_id IS 'payload artifact id'",
    "COMMENT ON COLUMN ops.job.scheduled_at IS 'scheduled at'",
    "COMMENT ON COLUMN ops.job.available_at IS 'available at'",
    "COMMENT ON COLUMN ops.job.started_at IS 'started at'",
    "COMMENT ON COLUMN ops.job.completed_at IS 'completed at'",
    "COMMENT ON COLUMN ops.job.max_attempts IS 'max attempts'",
    "COMMENT ON COLUMN ops.job.attempt_count IS 'attempt count'",
    "COMMENT ON COLUMN ops.job.lease_owner IS 'lease owner'",
    "COMMENT ON COLUMN ops.job.lease_expires_at IS 'lease expires at'",
    "COMMENT ON COLUMN ops.job.correlation_id IS '要求・Job・Eventを横断して追跡するCorrelation ID。'",
    "COMMENT ON COLUMN ops.job.causation_id IS 'この事実を直接発生させたCommand/Event/Job ID。'",
    "COMMENT ON COLUMN ops.job.parent_job_id IS 'parent job id'",
    "COMMENT ON COLUMN ops.job.budget_jpy IS 'budget jpy'",
    "COMMENT ON COLUMN ops.job.created_by_actor_type IS 'created by actor type'",
    "COMMENT ON COLUMN ops.job.created_by_actor_id IS 'created by actor id'",
    "COMMENT ON COLUMN ops.job.last_error_class IS 'last error class'",
    "COMMENT ON COLUMN ops.job.last_error_code IS 'last error code'",
    "COMMENT ON COLUMN ops.job.last_error_message IS 'last error message'",
    "COMMENT ON COLUMN ops.job.created_at IS 'レコード作成時刻。UTCのtimestamptz。'",
    "COMMENT ON COLUMN ops.job.updated_at IS '最終更新時刻。UTCのtimestamptz。'",
    "COMMENT ON COLUMN ops.job.lock_version IS '楽観的排他制御用の単調増加Version。'",
    "COMMENT ON COLUMN ops.job.job_version IS 'Version of the Job message/payload contract; distinct from lock_version.'",
    "COMMENT ON COLUMN ops.job.deadline_at IS 'Deadline after which an eligible active Job may expire.'",
    "COMMENT ON COLUMN ops.job.cancel_requested_at IS 'Timestamp of a cooperative cancellation request.'",
    "REVOKE ALL ON TABLE ops.job FROM PUBLIC",
    "CREATE TABLE ops.job_attempt (\n    id pg_catalog.uuid DEFAULT pg_catalog.uuidv7() NOT NULL,\n    job_id pg_catalog.uuid NOT NULL,\n    attempt_no pg_catalog.int2 NOT NULL,\n    status pg_catalog.text NOT NULL,\n    worker_id pg_catalog.text NOT NULL,\n    handler_version pg_catalog.text NOT NULL,\n    started_at pg_catalog.timestamptz NOT NULL,\n    completed_at pg_catalog.timestamptz,\n    provider_request_id pg_catalog.text,\n    input_artifact_id pg_catalog.uuid,\n    output_artifact_id pg_catalog.uuid,\n    error_class pg_catalog.text,\n    error_code pg_catalog.text,\n    error_message pg_catalog.text,\n    retry_after_at pg_catalog.timestamptz,\n    metrics pg_catalog.jsonb DEFAULT '{}'::jsonb NOT NULL,\n    created_at pg_catalog.timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    CONSTRAINT pk_ops_job_attempt PRIMARY KEY (id),\n    CONSTRAINT uq_ops_job_attempt_no UNIQUE (job_id, attempt_no),\n    CONSTRAINT ck_ops_job_attempt_status CHECK (status IN ('RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED', 'TIMED_OUT')),\n    CONSTRAINT ck_ops_job_attempt_no CHECK (attempt_no >= 1),\n    CONSTRAINT ck_ops_job_attempt_metrics CHECK (pg_catalog.jsonb_typeof(metrics) = 'object'),\n    CONSTRAINT ck_ops_job_attempt_end CHECK (status = 'RUNNING' OR completed_at IS NOT NULL)\n)",
    "COMMENT ON TABLE ops.job_attempt IS 'Jobの各実行Attemptを追記保存し、Retry、Provider call、入出力Artifact、失敗原因を再現可能にする。'",
    "COMMENT ON COLUMN ops.job_attempt.id IS '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'",
    "COMMENT ON COLUMN ops.job_attempt.job_id IS '非同期Job。'",
    "COMMENT ON COLUMN ops.job_attempt.attempt_no IS 'attempt no'",
    "COMMENT ON COLUMN ops.job_attempt.status IS '業務状態を示す安定Enum文字列。'",
    "COMMENT ON COLUMN ops.job_attempt.worker_id IS 'worker id'",
    "COMMENT ON COLUMN ops.job_attempt.handler_version IS 'handler version'",
    "COMMENT ON COLUMN ops.job_attempt.started_at IS 'started at'",
    "COMMENT ON COLUMN ops.job_attempt.completed_at IS 'completed at'",
    "COMMENT ON COLUMN ops.job_attempt.provider_request_id IS 'provider request id'",
    "COMMENT ON COLUMN ops.job_attempt.input_artifact_id IS 'input artifact id'",
    "COMMENT ON COLUMN ops.job_attempt.output_artifact_id IS 'output artifact id'",
    "COMMENT ON COLUMN ops.job_attempt.error_class IS 'error class'",
    "COMMENT ON COLUMN ops.job_attempt.error_code IS 'error code'",
    "COMMENT ON COLUMN ops.job_attempt.error_message IS 'error message'",
    "COMMENT ON COLUMN ops.job_attempt.retry_after_at IS 'retry after at'",
    "COMMENT ON COLUMN ops.job_attempt.metrics IS 'Duration、row count、provider quota等の低カーディナリティ指標。'",
    "COMMENT ON COLUMN ops.job_attempt.created_at IS 'レコード作成時刻。UTCのtimestamptz。'",
    "REVOKE ALL ON TABLE ops.job_attempt FROM PUBLIC",
    "CREATE TABLE ops.outbox_event (\n    id pg_catalog.uuid DEFAULT pg_catalog.uuidv7() NOT NULL,\n    event_type pg_catalog.text NOT NULL,\n    event_version pg_catalog.int4 DEFAULT 1 NOT NULL,\n    producer pg_catalog.text NOT NULL,\n    aggregate_type pg_catalog.text NOT NULL,\n    aggregate_id pg_catalog.uuid NOT NULL,\n    aggregate_version pg_catalog.int8 NOT NULL,\n    correlation_id pg_catalog.uuid NOT NULL,\n    causation_id pg_catalog.uuid,\n    actor_type pg_catalog.text NOT NULL,\n    actor_id pg_catalog.uuid,\n    payload pg_catalog.jsonb DEFAULT '{}'::jsonb NOT NULL,\n    payload_schema_hash pg_catalog.text NOT NULL,\n    status pg_catalog.text DEFAULT 'PENDING' NOT NULL,\n    available_at pg_catalog.timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    published_at pg_catalog.timestamptz,\n    publish_attempts pg_catalog.int2 DEFAULT 0 NOT NULL,\n    last_error pg_catalog.text,\n    created_at pg_catalog.timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    CONSTRAINT pk_ops_outbox_event PRIMARY KEY (id),\n    CONSTRAINT ck_ops_outbox_event_version CHECK (event_version >= 1 AND aggregate_version >= 0),\n    CONSTRAINT ck_ops_outbox_payload CHECK (pg_catalog.jsonb_typeof(payload) = 'object'),\n    CONSTRAINT ck_ops_outbox_hash CHECK (payload_schema_hash ~ '^[0-9a-f]{64}$'),\n    CONSTRAINT ck_ops_outbox_status CHECK (status IN ('PENDING', 'DISPATCHING', 'PUBLISHED', 'FAILED', 'DEAD')),\n    CONSTRAINT ck_ops_outbox_attempts CHECK (publish_attempts >= 0),\n    CONSTRAINT ck_ops_outbox_published CHECK (status <> 'PUBLISHED' OR published_at IS NOT NULL)\n)",
    "COMMENT ON TABLE ops.outbox_event IS '業務TransactionとEvent発行を原子的に接続するTransactional Outbox。'",
    "COMMENT ON COLUMN ops.outbox_event.id IS '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'",
    "COMMENT ON COLUMN ops.outbox_event.event_type IS 'event type'",
    "COMMENT ON COLUMN ops.outbox_event.event_version IS 'event version'",
    "COMMENT ON COLUMN ops.outbox_event.producer IS 'producer'",
    "COMMENT ON COLUMN ops.outbox_event.aggregate_type IS 'aggregate type'",
    "COMMENT ON COLUMN ops.outbox_event.aggregate_id IS 'aggregate id'",
    "COMMENT ON COLUMN ops.outbox_event.aggregate_version IS 'aggregate version'",
    "COMMENT ON COLUMN ops.outbox_event.correlation_id IS '要求・Job・Eventを横断して追跡するCorrelation ID。'",
    "COMMENT ON COLUMN ops.outbox_event.causation_id IS 'この事実を直接発生させたCommand/Event/Job ID。'",
    "COMMENT ON COLUMN ops.outbox_event.actor_type IS 'actor type'",
    "COMMENT ON COLUMN ops.outbox_event.actor_id IS 'actor id'",
    "COMMENT ON COLUMN ops.outbox_event.payload IS 'Version付きEvent payload。秘密・大容量原本を含めない。'",
    "COMMENT ON COLUMN ops.outbox_event.payload_schema_hash IS 'payload schema hash'",
    "COMMENT ON COLUMN ops.outbox_event.status IS '業務状態を示す安定Enum文字列。'",
    "COMMENT ON COLUMN ops.outbox_event.available_at IS 'available at'",
    "COMMENT ON COLUMN ops.outbox_event.published_at IS 'published at'",
    "COMMENT ON COLUMN ops.outbox_event.publish_attempts IS 'publish attempts'",
    "COMMENT ON COLUMN ops.outbox_event.last_error IS 'last error'",
    "COMMENT ON COLUMN ops.outbox_event.created_at IS 'レコード作成時刻。UTCのtimestamptz。'",
    "REVOKE ALL ON TABLE ops.outbox_event FROM PUBLIC",
    "CREATE TABLE ops.inbox_receipt (\n    id pg_catalog.uuid DEFAULT pg_catalog.uuidv7() NOT NULL,\n    consumer_name pg_catalog.text NOT NULL,\n    handler_version pg_catalog.text NOT NULL,\n    event_id pg_catalog.uuid NOT NULL,\n    status pg_catalog.text NOT NULL,\n    received_at pg_catalog.timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    processed_at pg_catalog.timestamptz,\n    result_hash pg_catalog.text,\n    error_code pg_catalog.text,\n    created_at pg_catalog.timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    CONSTRAINT pk_ops_inbox_receipt PRIMARY KEY (id),\n    CONSTRAINT uq_ops_inbox_receipt UNIQUE (consumer_name, handler_version, event_id),\n    CONSTRAINT ck_ops_inbox_status CHECK (status IN ('PROCESSING', 'PROCESSED', 'FAILED', 'IGNORED')),\n    CONSTRAINT ck_ops_inbox_hash CHECK (result_hash IS NULL OR result_hash ~ '^[0-9a-f]{64}$'),\n    CONSTRAINT ck_ops_inbox_processed CHECK (status = 'PROCESSING' OR processed_at IS NOT NULL)\n)",
    "COMMENT ON TABLE ops.inbox_receipt IS 'Consumer単位でEvent処理済みを記録し、at-least-once配送の重複を無害化する。'",
    "COMMENT ON COLUMN ops.inbox_receipt.id IS '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'",
    "COMMENT ON COLUMN ops.inbox_receipt.consumer_name IS 'consumer name'",
    "COMMENT ON COLUMN ops.inbox_receipt.handler_version IS 'handler version'",
    "COMMENT ON COLUMN ops.inbox_receipt.event_id IS 'event id'",
    "COMMENT ON COLUMN ops.inbox_receipt.status IS '業務状態を示す安定Enum文字列。'",
    "COMMENT ON COLUMN ops.inbox_receipt.received_at IS 'received at'",
    "COMMENT ON COLUMN ops.inbox_receipt.processed_at IS 'processed at'",
    "COMMENT ON COLUMN ops.inbox_receipt.result_hash IS 'result hash'",
    "COMMENT ON COLUMN ops.inbox_receipt.error_code IS 'error code'",
    "COMMENT ON COLUMN ops.inbox_receipt.created_at IS 'レコード作成時刻。UTCのtimestamptz。'",
    "REVOKE ALL ON TABLE ops.inbox_receipt FROM PUBLIC",
    "CREATE TABLE ops.idempotency_record (\n    id pg_catalog.uuid DEFAULT pg_catalog.uuidv7() NOT NULL,\n    actor_fingerprint pg_catalog.text NOT NULL,\n    route_key pg_catalog.text NOT NULL,\n    idempotency_key pg_catalog.text NOT NULL,\n    request_hash pg_catalog.text NOT NULL,\n    status pg_catalog.text DEFAULT 'IN_PROGRESS' NOT NULL,\n    response_status pg_catalog.int4,\n    response_body pg_catalog.jsonb,\n    response_artifact_id pg_catalog.uuid,\n    resource_type pg_catalog.text,\n    resource_id pg_catalog.uuid,\n    expires_at pg_catalog.timestamptz NOT NULL,\n    completed_at pg_catalog.timestamptz,\n    created_at pg_catalog.timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    CONSTRAINT pk_ops_idempotency_record PRIMARY KEY (id),\n    CONSTRAINT uq_ops_idempotency UNIQUE (actor_fingerprint, route_key, idempotency_key),\n    CONSTRAINT ck_ops_idem_request_hash CHECK (request_hash ~ '^[0-9a-f]{64}$'),\n    CONSTRAINT ck_ops_idem_status CHECK (status IN ('IN_PROGRESS', 'COMPLETED', 'FAILED')),\n    CONSTRAINT ck_ops_idem_response CHECK (status = 'IN_PROGRESS' OR response_status IS NOT NULL),\n    CONSTRAINT ck_ops_idem_expiry CHECK (expires_at > created_at),\n    CONSTRAINT ck_ops_idem_response_body CHECK (response_body IS NULL OR pg_catalog.jsonb_typeof(response_body) = 'object')\n)",
    "COMMENT ON TABLE ops.idempotency_record IS 'HTTP Command等の二重送信を検出し、同じKey＋同じpayloadへ同じ結果を返す。'",
    "COMMENT ON COLUMN ops.idempotency_record.id IS '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'",
    "COMMENT ON COLUMN ops.idempotency_record.actor_fingerprint IS 'actor fingerprint'",
    "COMMENT ON COLUMN ops.idempotency_record.route_key IS 'route key'",
    "COMMENT ON COLUMN ops.idempotency_record.idempotency_key IS 'idempotency key'",
    "COMMENT ON COLUMN ops.idempotency_record.request_hash IS 'request hash'",
    "COMMENT ON COLUMN ops.idempotency_record.status IS '業務状態を示す安定Enum文字列。'",
    "COMMENT ON COLUMN ops.idempotency_record.response_status IS 'response status'",
    "COMMENT ON COLUMN ops.idempotency_record.response_body IS '小さな再送応答。大きい応答はArtifactへ保存。'",
    "COMMENT ON COLUMN ops.idempotency_record.response_artifact_id IS 'response artifact id'",
    "COMMENT ON COLUMN ops.idempotency_record.resource_type IS 'resource type'",
    "COMMENT ON COLUMN ops.idempotency_record.resource_id IS 'resource id'",
    "COMMENT ON COLUMN ops.idempotency_record.expires_at IS 'expires at'",
    "COMMENT ON COLUMN ops.idempotency_record.completed_at IS 'completed at'",
    "COMMENT ON COLUMN ops.idempotency_record.created_at IS 'レコード作成時刻。UTCのtimestamptz。'",
    "REVOKE ALL ON TABLE ops.idempotency_record FROM PUBLIC",
    "CREATE TABLE ops.audit_event (\n    id pg_catalog.uuid DEFAULT pg_catalog.uuidv7() NOT NULL,\n    occurred_at pg_catalog.timestamptz NOT NULL,\n    actor_type pg_catalog.text NOT NULL,\n    actor_id pg_catalog.uuid,\n    action pg_catalog.text NOT NULL,\n    target_type pg_catalog.text NOT NULL,\n    target_id pg_catalog.uuid,\n    outcome pg_catalog.text NOT NULL,\n    severity pg_catalog.text DEFAULT 'INFO' NOT NULL,\n    correlation_id pg_catalog.uuid NOT NULL,\n    request_id pg_catalog.text,\n    before_hash pg_catalog.text,\n    after_hash pg_catalog.text,\n    details pg_catalog.jsonb DEFAULT '{}'::jsonb NOT NULL,\n    created_at pg_catalog.timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    CONSTRAINT pk_ops_audit_event PRIMARY KEY (id),\n    CONSTRAINT ck_ops_audit_actor CHECK (actor_type IN ('USER', 'SERVICE', 'SCHEDULE', 'SYSTEM', 'ANONYMOUS')),\n    CONSTRAINT ck_ops_audit_outcome CHECK (outcome IN ('SUCCESS', 'DENIED', 'FAILED', 'NOOP')),\n    CONSTRAINT ck_ops_audit_severity CHECK (severity IN ('INFO', 'NOTICE', 'WARNING', 'CRITICAL')),\n    CONSTRAINT ck_ops_audit_before_hash CHECK (before_hash IS NULL OR before_hash ~ '^[0-9a-f]{64}$'),\n    CONSTRAINT ck_ops_audit_after_hash CHECK (after_hash IS NULL OR after_hash ~ '^[0-9a-f]{64}$'),\n    CONSTRAINT ck_ops_audit_details CHECK (pg_catalog.jsonb_typeof(details) = 'object')\n)",
    "COMMENT ON TABLE ops.audit_event IS '管理操作・自動化操作・権限変更・公開・Kill Switch等を追記記録する監査正本。'",
    "COMMENT ON COLUMN ops.audit_event.id IS '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'",
    "COMMENT ON COLUMN ops.audit_event.occurred_at IS 'occurred at'",
    "COMMENT ON COLUMN ops.audit_event.actor_type IS 'actor type'",
    "COMMENT ON COLUMN ops.audit_event.actor_id IS 'actor id'",
    "COMMENT ON COLUMN ops.audit_event.action IS 'action'",
    "COMMENT ON COLUMN ops.audit_event.target_type IS 'target type'",
    "COMMENT ON COLUMN ops.audit_event.target_id IS 'target id'",
    "COMMENT ON COLUMN ops.audit_event.outcome IS 'outcome'",
    "COMMENT ON COLUMN ops.audit_event.severity IS 'severity'",
    "COMMENT ON COLUMN ops.audit_event.correlation_id IS '要求・Job・Eventを横断して追跡するCorrelation ID。'",
    "COMMENT ON COLUMN ops.audit_event.request_id IS 'request id'",
    "COMMENT ON COLUMN ops.audit_event.before_hash IS 'before hash'",
    "COMMENT ON COLUMN ops.audit_event.after_hash IS 'after hash'",
    "COMMENT ON COLUMN ops.audit_event.details IS '差分要約、理由、Policy/Prompt版。秘密、原文、raw IPは含めない。'",
    "COMMENT ON COLUMN ops.audit_event.created_at IS 'レコード作成時刻。UTCのtimestamptz。'",
    "REVOKE ALL ON TABLE ops.audit_event FROM PUBLIC",
    "CREATE TABLE iam.principal (\n    id pg_catalog.uuid DEFAULT pg_catalog.uuidv7() NOT NULL,\n    display_id pg_catalog.text NOT NULL,\n    principal_type pg_catalog.text NOT NULL,\n    status pg_catalog.text DEFAULT 'ACTIVE' NOT NULL,\n    display_name pg_catalog.text NOT NULL,\n    deactivated_at pg_catalog.timestamptz,\n    deactivation_reason pg_catalog.text,\n    created_at pg_catalog.timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    updated_at pg_catalog.timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    lock_version pg_catalog.int8 DEFAULT 0 NOT NULL,\n    CONSTRAINT pk_iam_principal PRIMARY KEY (id),\n    CONSTRAINT uq_iam_principal_display UNIQUE (display_id),\n    CONSTRAINT ck_iam_principal_type CHECK (principal_type IN ('USER', 'SERVICE')),\n    CONSTRAINT ck_iam_principal_status CHECK (status IN ('ACTIVE', 'SUSPENDED', 'DEACTIVATED')),\n    CONSTRAINT ck_iam_principal_deactivation CHECK (status <> 'DEACTIVATED' OR deactivated_at IS NOT NULL),\n    CONSTRAINT ck_iam_principal_version CHECK (lock_version >= 0)\n)",
    "COMMENT ON TABLE iam.principal IS '管理ユーザーとService Principalを共通IDで表すIAM Root。PasswordやSecretは保持しない。'",
    "COMMENT ON COLUMN iam.principal.id IS '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'",
    "COMMENT ON COLUMN iam.principal.display_id IS 'PRN-接頭辞を持つアプリケーション生成の不変表示ID。'",
    "COMMENT ON COLUMN iam.principal.principal_type IS 'principal type'",
    "COMMENT ON COLUMN iam.principal.status IS '業務状態を示す安定Enum文字列。'",
    "COMMENT ON COLUMN iam.principal.display_name IS 'display name'",
    "COMMENT ON COLUMN iam.principal.deactivated_at IS 'deactivated at'",
    "COMMENT ON COLUMN iam.principal.deactivation_reason IS 'deactivation reason'",
    "COMMENT ON COLUMN iam.principal.created_at IS 'レコード作成時刻。UTCのtimestamptz。'",
    "COMMENT ON COLUMN iam.principal.updated_at IS '最終更新時刻。UTCのtimestamptz。'",
    "COMMENT ON COLUMN iam.principal.lock_version IS '楽観的排他制御用の単調増加Version。'",
    "REVOKE ALL ON TABLE iam.principal FROM PUBLIC",
    "CREATE TABLE ops.runtime_setting_version (\n    id pg_catalog.uuid DEFAULT pg_catalog.uuidv7() NOT NULL,\n    setting_key pg_catalog.text NOT NULL,\n    scope_type pg_catalog.text NOT NULL,\n    scope_id pg_catalog.uuid,\n    version_no pg_catalog.int4 NOT NULL,\n    setting_class pg_catalog.text NOT NULL,\n    value pg_catalog.jsonb DEFAULT '{}'::jsonb NOT NULL,\n    value_sha256 pg_catalog.text NOT NULL,\n    status pg_catalog.text NOT NULL,\n    effective_from pg_catalog.timestamptz,\n    effective_to pg_catalog.timestamptz,\n    created_by_principal_id pg_catalog.uuid NOT NULL,\n    approved_by_principal_id pg_catalog.uuid,\n    approval_reason pg_catalog.text,\n    created_at pg_catalog.timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    CONSTRAINT pk_ops_runtime_setting_version PRIMARY KEY (id),\n    CONSTRAINT uq_ops_setting_version UNIQUE (setting_key, scope_type, scope_id, version_no),\n    CONSTRAINT ck_ops_setting_scope CHECK (scope_type IN ('GLOBAL', 'SITE', 'CATEGORY', 'ARTICLE', 'PROVIDER', 'TASK')),\n    CONSTRAINT ck_ops_setting_scope_id CHECK ((scope_type = 'GLOBAL' AND scope_id IS NULL) OR (scope_type <> 'GLOBAL' AND scope_id IS NOT NULL)),\n    CONSTRAINT ck_ops_setting_version CHECK (version_no >= 1),\n    CONSTRAINT ck_ops_setting_class CHECK (setting_class IN ('FEATURE_FLAG', 'THRESHOLD', 'PROVIDER', 'FRESHNESS', 'BUDGET', 'UI', 'OTHER')),\n    CONSTRAINT ck_ops_setting_no_secret CHECK (setting_class <> 'SECRET'),\n    CONSTRAINT ck_ops_setting_value CHECK (pg_catalog.jsonb_typeof(value) = 'object'),\n    CONSTRAINT ck_ops_setting_hash CHECK (value_sha256 ~ '^[0-9a-f]{64}$'),\n    CONSTRAINT ck_ops_setting_status CHECK (status IN ('DRAFT', 'ACTIVE', 'RETIRED', 'REJECTED')),\n    CONSTRAINT ck_ops_setting_window CHECK (effective_to IS NULL OR effective_from IS NULL OR effective_to > effective_from)\n)",
    "COMMENT ON TABLE ops.runtime_setting_version IS 'Feature Flag、閾値、Provider version、SLA等の非秘密設定をVersion管理する。'",
    "COMMENT ON COLUMN ops.runtime_setting_version.id IS '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'",
    "COMMENT ON COLUMN ops.runtime_setting_version.setting_key IS 'setting key'",
    "COMMENT ON COLUMN ops.runtime_setting_version.scope_type IS 'scope type'",
    "COMMENT ON COLUMN ops.runtime_setting_version.scope_id IS 'scope id'",
    "COMMENT ON COLUMN ops.runtime_setting_version.version_no IS 'Aggregate内で1から増加する不変Version番号。'",
    "COMMENT ON COLUMN ops.runtime_setting_version.setting_class IS 'setting class'",
    "COMMENT ON COLUMN ops.runtime_setting_version.value IS 'value'",
    "COMMENT ON COLUMN ops.runtime_setting_version.value_sha256 IS 'value sha256'",
    "COMMENT ON COLUMN ops.runtime_setting_version.status IS '業務状態を示す安定Enum文字列。'",
    "COMMENT ON COLUMN ops.runtime_setting_version.effective_from IS '設定・関係が有効になる時刻。'",
    "COMMENT ON COLUMN ops.runtime_setting_version.effective_to IS '設定・関係の有効終了時刻。NULLは終了未定。'",
    "COMMENT ON COLUMN ops.runtime_setting_version.created_by_principal_id IS '作成操作を行ったIAM Principal。'",
    "COMMENT ON COLUMN ops.runtime_setting_version.approved_by_principal_id IS 'approved by principal id'",
    "COMMENT ON COLUMN ops.runtime_setting_version.approval_reason IS 'approval reason'",
    "COMMENT ON COLUMN ops.runtime_setting_version.created_at IS 'レコード作成時刻。UTCのtimestamptz。'",
    "REVOKE ALL ON TABLE ops.runtime_setting_version FROM PUBLIC",
    "CREATE TABLE iam.user_account (\n    principal_id pg_catalog.uuid NOT NULL,\n    oidc_issuer pg_catalog.text NOT NULL,\n    oidc_subject pg_catalog.text NOT NULL,\n    email pg_catalog.text,\n    email_verified pg_catalog.bool DEFAULT false NOT NULL,\n    mfa_required pg_catalog.bool DEFAULT true NOT NULL,\n    last_login_at pg_catalog.timestamptz,\n    last_mfa_at pg_catalog.timestamptz,\n    created_at pg_catalog.timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    CONSTRAINT pk_iam_user_account PRIMARY KEY (principal_id),\n    CONSTRAINT uq_iam_user_oidc UNIQUE (oidc_issuer, oidc_subject),\n    CONSTRAINT ck_iam_user_https_issuer CHECK (oidc_issuer ~ '^https://')\n)",
    "COMMENT ON TABLE iam.user_account IS 'OIDC UserのIssuer/Subject、表示用Email、MFA claim等をPrincipalへ紐付ける。'",
    "COMMENT ON COLUMN iam.user_account.principal_id IS 'principal id'",
    "COMMENT ON COLUMN iam.user_account.oidc_issuer IS 'oidc issuer'",
    "COMMENT ON COLUMN iam.user_account.oidc_subject IS 'oidc subject'",
    "COMMENT ON COLUMN iam.user_account.email IS 'email'",
    "COMMENT ON COLUMN iam.user_account.email_verified IS 'email verified'",
    "COMMENT ON COLUMN iam.user_account.mfa_required IS 'mfa required'",
    "COMMENT ON COLUMN iam.user_account.last_login_at IS 'last login at'",
    "COMMENT ON COLUMN iam.user_account.last_mfa_at IS 'last mfa at'",
    "COMMENT ON COLUMN iam.user_account.created_at IS 'レコード作成時刻。UTCのtimestamptz。'",
    "REVOKE ALL ON TABLE iam.user_account FROM PUBLIC",
    "CREATE TABLE iam.service_principal (\n    principal_id pg_catalog.uuid NOT NULL,\n    service_code pg_catalog.text NOT NULL,\n    workload_identity pg_catalog.text NOT NULL,\n    allowed_environment pg_catalog.text NOT NULL,\n    credential_rotated_at pg_catalog.timestamptz,\n    last_used_at pg_catalog.timestamptz,\n    created_at pg_catalog.timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    CONSTRAINT pk_iam_service_principal PRIMARY KEY (principal_id),\n    CONSTRAINT uq_iam_service_code UNIQUE (service_code),\n    CONSTRAINT uq_iam_service_workload UNIQUE (workload_identity, allowed_environment),\n    CONSTRAINT ck_iam_service_env CHECK (allowed_environment IN ('LOCAL', 'CI', 'STAGING', 'PRODUCTION'))\n)",
    "COMMENT ON TABLE iam.service_principal IS 'Worker、Dispatcher、CI等のWorkload IdentityをPrincipalへ紐付ける。Credential本体はSecrets Manager/OIDCに置く。'",
    "COMMENT ON COLUMN iam.service_principal.principal_id IS 'principal id'",
    "COMMENT ON COLUMN iam.service_principal.service_code IS 'service code'",
    "COMMENT ON COLUMN iam.service_principal.workload_identity IS 'workload identity'",
    "COMMENT ON COLUMN iam.service_principal.allowed_environment IS 'allowed environment'",
    "COMMENT ON COLUMN iam.service_principal.credential_rotated_at IS 'credential rotated at'",
    "COMMENT ON COLUMN iam.service_principal.last_used_at IS 'last used at'",
    "COMMENT ON COLUMN iam.service_principal.created_at IS 'レコード作成時刻。UTCのtimestamptz。'",
    "REVOKE ALL ON TABLE iam.service_principal FROM PUBLIC",
    "CREATE TABLE iam.role (\n    id pg_catalog.uuid DEFAULT pg_catalog.uuidv7() NOT NULL,\n    role_code pg_catalog.text NOT NULL,\n    name pg_catalog.text NOT NULL,\n    description pg_catalog.text NOT NULL,\n    is_system_role pg_catalog.bool DEFAULT true NOT NULL,\n    status pg_catalog.text DEFAULT 'ACTIVE' NOT NULL,\n    created_at pg_catalog.timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    CONSTRAINT pk_iam_role PRIMARY KEY (id),\n    CONSTRAINT uq_iam_role_code UNIQUE (role_code),\n    CONSTRAINT ck_iam_role_status CHECK (status IN ('ACTIVE', 'RETIRED'))\n)",
    "COMMENT ON TABLE iam.role IS 'RAOSアプリケーション内Roleの定義。DB Roleとは分離する。'",
    "COMMENT ON COLUMN iam.role.id IS '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'",
    "COMMENT ON COLUMN iam.role.role_code IS 'role code'",
    "COMMENT ON COLUMN iam.role.name IS 'name'",
    "COMMENT ON COLUMN iam.role.description IS 'description'",
    "COMMENT ON COLUMN iam.role.is_system_role IS 'is system role'",
    "COMMENT ON COLUMN iam.role.status IS '業務状態を示す安定Enum文字列。'",
    "COMMENT ON COLUMN iam.role.created_at IS 'レコード作成時刻。UTCのtimestamptz。'",
    "REVOKE ALL ON TABLE iam.role FROM PUBLIC",
    "CREATE TABLE iam.permission (\n    id pg_catalog.uuid DEFAULT pg_catalog.uuidv7() NOT NULL,\n    permission_code pg_catalog.text NOT NULL,\n    description pg_catalog.text NOT NULL,\n    risk_level pg_catalog.text NOT NULL,\n    status pg_catalog.text DEFAULT 'ACTIVE' NOT NULL,\n    created_at pg_catalog.timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    CONSTRAINT pk_iam_permission PRIMARY KEY (id),\n    CONSTRAINT uq_iam_permission_code UNIQUE (permission_code),\n    CONSTRAINT ck_iam_permission_risk CHECK (risk_level IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL')),\n    CONSTRAINT ck_iam_permission_status CHECK (status IN ('ACTIVE', 'RETIRED'))\n)",
    "COMMENT ON TABLE iam.permission IS 'API/Command単位の安定Permission code。'",
    "COMMENT ON COLUMN iam.permission.id IS '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'",
    "COMMENT ON COLUMN iam.permission.permission_code IS 'permission code'",
    "COMMENT ON COLUMN iam.permission.description IS 'description'",
    "COMMENT ON COLUMN iam.permission.risk_level IS 'risk level'",
    "COMMENT ON COLUMN iam.permission.status IS '業務状態を示す安定Enum文字列。'",
    "COMMENT ON COLUMN iam.permission.created_at IS 'レコード作成時刻。UTCのtimestamptz。'",
    "REVOKE ALL ON TABLE iam.permission FROM PUBLIC",
    "CREATE TABLE iam.role_permission (\n    role_id pg_catalog.uuid NOT NULL,\n    permission_id pg_catalog.uuid NOT NULL,\n    created_at pg_catalog.timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    CONSTRAINT pk_iam_role_permission PRIMARY KEY (role_id, permission_id)\n)",
    "COMMENT ON TABLE iam.role_permission IS 'RoleとPermissionの多対多対応。'",
    "COMMENT ON COLUMN iam.role_permission.role_id IS 'role id'",
    "COMMENT ON COLUMN iam.role_permission.permission_id IS 'permission id'",
    "COMMENT ON COLUMN iam.role_permission.created_at IS 'レコード作成時刻。UTCのtimestamptz。'",
    "REVOKE ALL ON TABLE iam.role_permission FROM PUBLIC",
    "CREATE TABLE iam.principal_role_assignment (\n    id pg_catalog.uuid DEFAULT pg_catalog.uuidv7() NOT NULL,\n    principal_id pg_catalog.uuid NOT NULL,\n    role_id pg_catalog.uuid NOT NULL,\n    scope_type pg_catalog.text NOT NULL,\n    scope_id pg_catalog.uuid,\n    valid_from pg_catalog.timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    valid_to pg_catalog.timestamptz,\n    assigned_by_principal_id pg_catalog.uuid NOT NULL,\n    assignment_reason pg_catalog.text NOT NULL,\n    revoked_at pg_catalog.timestamptz,\n    revoked_by_principal_id pg_catalog.uuid,\n    revocation_reason pg_catalog.text,\n    created_at pg_catalog.timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    CONSTRAINT pk_iam_principal_role_assignment PRIMARY KEY (id),\n    CONSTRAINT ck_iam_assignment_scope CHECK (scope_type IN ('GLOBAL', 'SITE', 'CATEGORY', 'ARTICLE')),\n    CONSTRAINT ck_iam_assignment_scope_id CHECK ((scope_type = 'GLOBAL' AND scope_id IS NULL) OR (scope_type <> 'GLOBAL' AND scope_id IS NOT NULL)),\n    CONSTRAINT ck_iam_assignment_window CHECK (valid_to IS NULL OR valid_to > valid_from),\n    CONSTRAINT ck_iam_assignment_revoke_pair CHECK ((revoked_at IS NULL) = (revoked_by_principal_id IS NULL))\n)",
    "COMMENT ON TABLE iam.principal_role_assignment IS 'Principalへglobal/site/category/article scopeのRoleを期限付き付与する。'",
    "COMMENT ON COLUMN iam.principal_role_assignment.id IS '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'",
    "COMMENT ON COLUMN iam.principal_role_assignment.principal_id IS 'principal id'",
    "COMMENT ON COLUMN iam.principal_role_assignment.role_id IS 'role id'",
    "COMMENT ON COLUMN iam.principal_role_assignment.scope_type IS 'scope type'",
    "COMMENT ON COLUMN iam.principal_role_assignment.scope_id IS 'scope id'",
    "COMMENT ON COLUMN iam.principal_role_assignment.valid_from IS 'valid from'",
    "COMMENT ON COLUMN iam.principal_role_assignment.valid_to IS 'valid to'",
    "COMMENT ON COLUMN iam.principal_role_assignment.assigned_by_principal_id IS 'assigned by principal id'",
    "COMMENT ON COLUMN iam.principal_role_assignment.assignment_reason IS 'assignment reason'",
    "COMMENT ON COLUMN iam.principal_role_assignment.revoked_at IS 'revoked at'",
    "COMMENT ON COLUMN iam.principal_role_assignment.revoked_by_principal_id IS 'revoked by principal id'",
    "COMMENT ON COLUMN iam.principal_role_assignment.revocation_reason IS 'revocation reason'",
    "COMMENT ON COLUMN iam.principal_role_assignment.created_at IS 'レコード作成時刻。UTCのtimestamptz。'",
    "REVOKE ALL ON TABLE iam.principal_role_assignment FROM PUBLIC",
    "CREATE TABLE iam.session_revocation (\n    id pg_catalog.uuid DEFAULT pg_catalog.uuidv7() NOT NULL,\n    principal_id pg_catalog.uuid NOT NULL,\n    oidc_issuer pg_catalog.text NOT NULL,\n    oidc_subject pg_catalog.text NOT NULL,\n    revoke_before pg_catalog.timestamptz NOT NULL,\n    reason pg_catalog.text NOT NULL,\n    created_by_principal_id pg_catalog.uuid NOT NULL,\n    expires_at pg_catalog.timestamptz,\n    created_at pg_catalog.timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    CONSTRAINT pk_iam_session_revocation PRIMARY KEY (id),\n    CONSTRAINT ck_iam_session_issuer CHECK (oidc_issuer ~ '^https://'),\n    CONSTRAINT ck_iam_session_expiry CHECK (expires_at IS NULL OR expires_at > revoke_before)\n)",
    "COMMENT ON TABLE iam.session_revocation IS 'PrincipalまたはOIDC Subjectのrevoke-beforeを保持し、既存Sessionを無効化する。'",
    "COMMENT ON COLUMN iam.session_revocation.id IS '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'",
    "COMMENT ON COLUMN iam.session_revocation.principal_id IS 'principal id'",
    "COMMENT ON COLUMN iam.session_revocation.oidc_issuer IS 'oidc issuer'",
    "COMMENT ON COLUMN iam.session_revocation.oidc_subject IS 'oidc subject'",
    "COMMENT ON COLUMN iam.session_revocation.revoke_before IS 'revoke before'",
    "COMMENT ON COLUMN iam.session_revocation.reason IS 'reason'",
    "COMMENT ON COLUMN iam.session_revocation.created_by_principal_id IS '作成操作を行ったIAM Principal。'",
    "COMMENT ON COLUMN iam.session_revocation.expires_at IS 'expires at'",
    "COMMENT ON COLUMN iam.session_revocation.created_at IS 'レコード作成時刻。UTCのtimestamptz。'",
    "REVOKE ALL ON TABLE iam.session_revocation FROM PUBLIC",
    "CREATE TABLE iam.break_glass_record (\n    id pg_catalog.uuid DEFAULT pg_catalog.uuidv7() NOT NULL,\n    display_id pg_catalog.text NOT NULL,\n    principal_id pg_catalog.uuid NOT NULL,\n    incident_id pg_catalog.uuid NOT NULL,\n    reason pg_catalog.text NOT NULL,\n    approved_by_principal_id pg_catalog.uuid NOT NULL,\n    permissions pg_catalog.jsonb DEFAULT '{}'::jsonb NOT NULL,\n    started_at pg_catalog.timestamptz NOT NULL,\n    expires_at pg_catalog.timestamptz NOT NULL,\n    ended_at pg_catalog.timestamptz,\n    end_reason pg_catalog.text,\n    created_at pg_catalog.timestamptz DEFAULT CURRENT_TIMESTAMP NOT NULL,\n    CONSTRAINT pk_iam_break_glass_record PRIMARY KEY (id),\n    CONSTRAINT uq_iam_break_glass_display UNIQUE (display_id),\n    CONSTRAINT ck_iam_break_glass_window CHECK (expires_at > started_at AND (ended_at IS NULL OR ended_at >= started_at)),\n    CONSTRAINT ck_iam_break_glass_permissions CHECK (pg_catalog.jsonb_typeof(permissions) = 'object')\n)",
    "COMMENT ON TABLE iam.break_glass_record IS '緊急権限の理由、Incident、承認、権限集合、有効期間、終了を記録する。'",
    "COMMENT ON COLUMN iam.break_glass_record.id IS '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'",
    "COMMENT ON COLUMN iam.break_glass_record.display_id IS 'BGA-接頭辞を持つアプリケーション生成の不変表示ID。'",
    "COMMENT ON COLUMN iam.break_glass_record.principal_id IS 'principal id'",
    "COMMENT ON COLUMN iam.break_glass_record.incident_id IS 'incident id'",
    "COMMENT ON COLUMN iam.break_glass_record.reason IS 'reason'",
    "COMMENT ON COLUMN iam.break_glass_record.approved_by_principal_id IS 'approved by principal id'",
    "COMMENT ON COLUMN iam.break_glass_record.permissions IS '緊急時に一時付与したPermission code集合。'",
    "COMMENT ON COLUMN iam.break_glass_record.started_at IS 'started at'",
    "COMMENT ON COLUMN iam.break_glass_record.expires_at IS 'expires at'",
    "COMMENT ON COLUMN iam.break_glass_record.ended_at IS 'ended at'",
    "COMMENT ON COLUMN iam.break_glass_record.end_reason IS 'end reason'",
    "COMMENT ON COLUMN iam.break_glass_record.created_at IS 'レコード作成時刻。UTCのtimestamptz。'",
    "REVOKE ALL ON TABLE iam.break_glass_record FROM PUBLIC",
    "ALTER TABLE ops.job ADD CONSTRAINT fk_ops_job_payload_artifact_id FOREIGN KEY (payload_artifact_id) REFERENCES ops.object_artifact (id) ON DELETE RESTRICT NOT DEFERRABLE",
    "ALTER TABLE ops.job ADD CONSTRAINT fk_ops_job_parent_job_id FOREIGN KEY (parent_job_id) REFERENCES ops.job (id) ON DELETE SET NULL NOT DEFERRABLE",
    "ALTER TABLE ops.job_attempt ADD CONSTRAINT fk_ops_job_attempt_job_id FOREIGN KEY (job_id) REFERENCES ops.job (id) ON DELETE RESTRICT NOT DEFERRABLE",
    "ALTER TABLE ops.job_attempt ADD CONSTRAINT fk_ops_job_attempt_input_artifact_id FOREIGN KEY (input_artifact_id) REFERENCES ops.object_artifact (id) ON DELETE RESTRICT NOT DEFERRABLE",
    "ALTER TABLE ops.job_attempt ADD CONSTRAINT fk_ops_job_attempt_output_artifact_id FOREIGN KEY (output_artifact_id) REFERENCES ops.object_artifact (id) ON DELETE RESTRICT NOT DEFERRABLE",
    "ALTER TABLE ops.idempotency_record ADD CONSTRAINT fk_ops_idempotency_record_response_artifact_id FOREIGN KEY (response_artifact_id) REFERENCES ops.object_artifact (id) ON DELETE RESTRICT NOT DEFERRABLE",
    "ALTER TABLE ops.runtime_setting_version ADD CONSTRAINT fk_ops_runtime_setting_version_created_by_principal_id FOREIGN KEY (created_by_principal_id) REFERENCES iam.principal (id) ON DELETE RESTRICT NOT DEFERRABLE",
    "ALTER TABLE ops.runtime_setting_version ADD CONSTRAINT fk_ops_runtime_setting_version_approved_by_principal_id FOREIGN KEY (approved_by_principal_id) REFERENCES iam.principal (id) ON DELETE RESTRICT NOT DEFERRABLE",
    "ALTER TABLE iam.user_account ADD CONSTRAINT fk_iam_user_account_principal_id FOREIGN KEY (principal_id) REFERENCES iam.principal (id) ON DELETE RESTRICT NOT DEFERRABLE",
    "ALTER TABLE iam.service_principal ADD CONSTRAINT fk_iam_service_principal_principal_id FOREIGN KEY (principal_id) REFERENCES iam.principal (id) ON DELETE RESTRICT NOT DEFERRABLE",
    "ALTER TABLE iam.role_permission ADD CONSTRAINT fk_iam_role_permission_role_id FOREIGN KEY (role_id) REFERENCES iam.role (id) ON DELETE RESTRICT NOT DEFERRABLE",
    "ALTER TABLE iam.role_permission ADD CONSTRAINT fk_iam_role_permission_permission_id FOREIGN KEY (permission_id) REFERENCES iam.permission (id) ON DELETE RESTRICT NOT DEFERRABLE",
    "ALTER TABLE iam.principal_role_assignment ADD CONSTRAINT fk_iam_principal_role_assignment_principal_id FOREIGN KEY (principal_id) REFERENCES iam.principal (id) ON DELETE RESTRICT NOT DEFERRABLE",
    "ALTER TABLE iam.principal_role_assignment ADD CONSTRAINT fk_iam_principal_role_assignment_role_id FOREIGN KEY (role_id) REFERENCES iam.role (id) ON DELETE RESTRICT NOT DEFERRABLE",
    "ALTER TABLE iam.principal_role_assignment ADD CONSTRAINT fk_iam_principal_role_assignment_assigned_by_principal_id FOREIGN KEY (assigned_by_principal_id) REFERENCES iam.principal (id) ON DELETE RESTRICT NOT DEFERRABLE",
    "ALTER TABLE iam.principal_role_assignment ADD CONSTRAINT fk_iam_principal_role_assignment_revoked_by_principal_id FOREIGN KEY (revoked_by_principal_id) REFERENCES iam.principal (id) ON DELETE RESTRICT NOT DEFERRABLE",
    "ALTER TABLE iam.session_revocation ADD CONSTRAINT fk_iam_session_revocation_principal_id FOREIGN KEY (principal_id) REFERENCES iam.principal (id) ON DELETE RESTRICT NOT DEFERRABLE",
    "ALTER TABLE iam.session_revocation ADD CONSTRAINT fk_iam_session_revocation_created_by_principal_id FOREIGN KEY (created_by_principal_id) REFERENCES iam.principal (id) ON DELETE RESTRICT NOT DEFERRABLE",
    "ALTER TABLE iam.break_glass_record ADD CONSTRAINT fk_iam_break_glass_record_principal_id FOREIGN KEY (principal_id) REFERENCES iam.principal (id) ON DELETE RESTRICT NOT DEFERRABLE",
    "ALTER TABLE iam.break_glass_record ADD CONSTRAINT fk_iam_break_glass_record_approved_by_principal_id FOREIGN KEY (approved_by_principal_id) REFERENCES iam.principal (id) ON DELETE RESTRICT NOT DEFERRABLE",
    "CREATE UNIQUE INDEX uq_ops_object_artifact_location ON ops.object_artifact USING btree (bucket_name, object_key, object_version) NULLS NOT DISTINCT",
    "CREATE INDEX ix_ops_object_artifact_sha ON ops.object_artifact USING btree (sha256)",
    "CREATE INDEX ix_ops_object_artifact_kind_created ON ops.object_artifact USING btree (artifact_kind, created_at)",
    "CREATE UNIQUE INDEX uq_ops_job_idempotency ON ops.job USING btree (job_type, idempotency_key) WHERE idempotency_key IS NOT NULL",
    "CREATE INDEX ix_ops_job_ready ON ops.job USING btree (queue_name, priority, available_at) WHERE status IN ('REQUESTED','QUEUED','RETRY_SCHEDULED')",
    "CREATE INDEX ix_ops_job_lease ON ops.job USING btree (lease_expires_at) WHERE status = 'RUNNING'",
    "CREATE INDEX ix_ops_job_aggregate ON ops.job USING btree (aggregate_type, aggregate_id)",
    "CREATE INDEX ix_ops_job_correlation ON ops.job USING btree (correlation_id)",
    "CREATE INDEX ix_ops_job_payload_artifact_id ON ops.job USING btree (payload_artifact_id)",
    "COMMENT ON INDEX ops.ix_ops_job_payload_artifact_id IS 'Foreign key lookup and parent delete/update check.'",
    "CREATE INDEX ix_ops_job_parent_job_id ON ops.job USING btree (parent_job_id)",
    "COMMENT ON INDEX ops.ix_ops_job_parent_job_id IS 'Foreign key lookup and parent delete/update check.'",
    "CREATE INDEX ix_ops_job_site_id ON ops.job USING btree (site_id)",
    "COMMENT ON INDEX ops.ix_ops_job_site_id IS 'Foreign key lookup and parent delete/update check.'",
    "CREATE INDEX ix_ops_job_deadline_active ON ops.job USING btree (deadline_at) WHERE deadline_at IS NOT NULL AND status IN ('REQUESTED','QUEUED','RUNNING','FAILED_RETRYABLE','RETRY_SCHEDULED')",
    "CREATE INDEX ix_ops_job_attempt_started ON ops.job_attempt USING btree (started_at)",
    "CREATE INDEX ix_ops_job_attempt_status ON ops.job_attempt USING btree (status, started_at)",
    "CREATE INDEX ix_ops_job_attempt_input_artifact_id ON ops.job_attempt USING btree (input_artifact_id)",
    "COMMENT ON INDEX ops.ix_ops_job_attempt_input_artifact_id IS 'Foreign key lookup and parent delete/update check.'",
    "CREATE INDEX ix_ops_job_attempt_output_artifact_id ON ops.job_attempt USING btree (output_artifact_id)",
    "COMMENT ON INDEX ops.ix_ops_job_attempt_output_artifact_id IS 'Foreign key lookup and parent delete/update check.'",
    "CREATE INDEX ix_ops_outbox_ready ON ops.outbox_event USING btree (status, available_at) WHERE status IN ('PENDING','FAILED')",
    "CREATE INDEX ix_ops_outbox_aggregate ON ops.outbox_event USING btree (aggregate_type, aggregate_id, aggregate_version)",
    "CREATE INDEX ix_ops_outbox_correlation ON ops.outbox_event USING btree (correlation_id)",
    "CREATE INDEX ix_ops_outbox_created_brin ON ops.outbox_event USING brin (created_at)",
    "CREATE INDEX ix_ops_inbox_event ON ops.inbox_receipt USING btree (event_id)",
    "CREATE INDEX ix_ops_inbox_received ON ops.inbox_receipt USING btree (received_at)",
    "CREATE INDEX ix_ops_idempotency_expiry ON ops.idempotency_record USING btree (expires_at)",
    "CREATE INDEX ix_ops_idempotency_record_response_artifact_id ON ops.idempotency_record USING btree (response_artifact_id)",
    "COMMENT ON INDEX ops.ix_ops_idempotency_record_response_artifact_id IS 'Foreign key lookup and parent delete/update check.'",
    "CREATE INDEX ix_ops_audit_occurred ON ops.audit_event USING btree (occurred_at)",
    "CREATE INDEX ix_ops_audit_actor ON ops.audit_event USING btree (actor_type, actor_id, occurred_at)",
    "CREATE INDEX ix_ops_audit_target ON ops.audit_event USING btree (target_type, target_id, occurred_at)",
    "CREATE INDEX ix_ops_audit_corr ON ops.audit_event USING btree (correlation_id)",
    "CREATE INDEX ix_ops_audit_occurred_brin ON ops.audit_event USING brin (occurred_at)",
    "CREATE INDEX ix_iam_principal_status ON iam.principal USING btree (status, principal_type)",
    "CREATE UNIQUE INDEX uq_ops_setting_active ON ops.runtime_setting_version USING btree (setting_key, scope_type, scope_id) NULLS NOT DISTINCT WHERE status = 'ACTIVE'",
    "CREATE INDEX ix_ops_setting_lookup ON ops.runtime_setting_version USING btree (setting_key, status, effective_from)",
    "CREATE INDEX ix_ops_runtime_setting_version_created_by_principal_id ON ops.runtime_setting_version USING btree (created_by_principal_id)",
    "COMMENT ON INDEX ops.ix_ops_runtime_setting_version_created_by_principal_id IS 'Foreign key lookup and parent delete/update check.'",
    "CREATE INDEX ix_ops_runtime_setting_version_approved_by_principal_id ON ops.runtime_setting_version USING btree (approved_by_principal_id)",
    "COMMENT ON INDEX ops.ix_ops_runtime_setting_version_approved_by_principal_id IS 'Foreign key lookup and parent delete/update check.'",
    "CREATE INDEX ix_iam_user_email_lower ON iam.user_account USING btree (pg_catalog.lower(email)) WHERE email IS NOT NULL",
    "CREATE INDEX ix_iam_role_permission_permission_id ON iam.role_permission USING btree (permission_id)",
    "COMMENT ON INDEX iam.ix_iam_role_permission_permission_id IS 'Foreign key lookup and parent delete/update check.'",
    "CREATE UNIQUE INDEX uq_iam_assignment_active ON iam.principal_role_assignment USING btree (principal_id, role_id, scope_type, scope_id) NULLS NOT DISTINCT WHERE revoked_at IS NULL",
    "CREATE INDEX ix_iam_assignment_lookup ON iam.principal_role_assignment USING btree (principal_id, scope_type, scope_id, valid_from)",
    "CREATE INDEX ix_iam_principal_role_assignment_role_id ON iam.principal_role_assignment USING btree (role_id)",
    "COMMENT ON INDEX iam.ix_iam_principal_role_assignment_role_id IS 'Foreign key lookup and parent delete/update check.'",
    "CREATE INDEX ix_iam_principal_role_assignment_assigned_by_principal_id ON iam.principal_role_assignment USING btree (assigned_by_principal_id)",
    "COMMENT ON INDEX iam.ix_iam_principal_role_assignment_assigned_by_principal_id IS 'Foreign key lookup and parent delete/update check.'",
    "CREATE INDEX ix_iam_principal_role_assignment_revoked_by_principal_id ON iam.principal_role_assignment USING btree (revoked_by_principal_id)",
    "COMMENT ON INDEX iam.ix_iam_principal_role_assignment_revoked_by_principal_id IS 'Foreign key lookup and parent delete/update check.'",
    "CREATE INDEX ix_iam_session_revocation_lookup ON iam.session_revocation USING btree (oidc_issuer, oidc_subject, revoke_before)",
    "CREATE INDEX ix_iam_session_revocation_principal_id ON iam.session_revocation USING btree (principal_id)",
    "COMMENT ON INDEX iam.ix_iam_session_revocation_principal_id IS 'Foreign key lookup and parent delete/update check.'",
    "CREATE INDEX ix_iam_session_revocation_created_by_principal_id ON iam.session_revocation USING btree (created_by_principal_id)",
    "COMMENT ON INDEX iam.ix_iam_session_revocation_created_by_principal_id IS 'Foreign key lookup and parent delete/update check.'",
    "CREATE INDEX ix_iam_break_glass_active ON iam.break_glass_record USING btree (expires_at) WHERE ended_at IS NULL",
    "CREATE INDEX ix_iam_break_glass_record_principal_id ON iam.break_glass_record USING btree (principal_id)",
    "COMMENT ON INDEX iam.ix_iam_break_glass_record_principal_id IS 'Foreign key lookup and parent delete/update check.'",
    "CREATE INDEX ix_iam_break_glass_record_incident_id ON iam.break_glass_record USING btree (incident_id)",
    "COMMENT ON INDEX iam.ix_iam_break_glass_record_incident_id IS 'Foreign key lookup and parent delete/update check.'",
    "CREATE INDEX ix_iam_break_glass_record_approved_by_principal_id ON iam.break_glass_record USING btree (approved_by_principal_id)",
    "COMMENT ON INDEX iam.ix_iam_break_glass_record_approved_by_principal_id IS 'Foreign key lookup and parent delete/update check.'",
    "CREATE FUNCTION ops.touch_mutable_row()\nRETURNS pg_catalog.trigger\nLANGUAGE plpgsql\nVOLATILE\nSECURITY INVOKER\nSET search_path = pg_catalog\nAS $raos_st0303_touch$BEGIN\n    IF NEW IS DISTINCT FROM OLD THEN\n        NEW.updated_at := pg_catalog.statement_timestamp();\n        NEW.lock_version := OLD.lock_version + 1;\n    END IF;\n    RETURN NEW;\nEND;$raos_st0303_touch$",
    "REVOKE ALL ON FUNCTION ops.touch_mutable_row() FROM PUBLIC",
    "COMMENT ON FUNCTION ops.touch_mutable_row() IS 'Mutable rows receive a statement timestamp and monotonic lock version only when row values change.'",
    "CREATE FUNCTION ops.reject_immutable_mutation()\nRETURNS pg_catalog.trigger\nLANGUAGE plpgsql\nVOLATILE\nSECURITY INVOKER\nSET search_path = pg_catalog\nAS $raos_st0303_immutable$BEGIN\n    IF pg_catalog.current_setting('raos.allow_immutable_maintenance', true) = 'on'\n       AND pg_catalog.pg_has_role(current_user, 'raos_migrator', 'MEMBER') THEN\n        IF TG_OP = 'DELETE' THEN\n            RETURN OLD;\n        END IF;\n        RETURN NEW;\n    END IF;\n    RAISE EXCEPTION USING\n        ERRCODE = '55000',\n        MESSAGE = 'RAOS immutable table mutation is forbidden';\nEND;$raos_st0303_immutable$",
    "REVOKE ALL ON FUNCTION ops.reject_immutable_mutation() FROM PUBLIC",
    "COMMENT ON FUNCTION ops.reject_immutable_mutation() IS 'Reject normal UPDATE and DELETE on hard-immutable tables; permit only an explicit migrator maintenance session.'",
    "CREATE TRIGGER trg_ops_job_touch BEFORE UPDATE ON ops.job FOR EACH ROW EXECUTE FUNCTION ops.touch_mutable_row()",
    "COMMENT ON TRIGGER trg_ops_job_touch ON ops.job IS 'Maintain ops.job updated_at and lock_version for changed rows.'",
    "CREATE TRIGGER trg_iam_principal_touch BEFORE UPDATE ON iam.principal FOR EACH ROW EXECUTE FUNCTION ops.touch_mutable_row()",
    "COMMENT ON TRIGGER trg_iam_principal_touch ON iam.principal IS 'Maintain iam.principal updated_at and lock_version for changed rows.'",
    "CREATE TRIGGER trg_ops_object_artifact_immutable BEFORE UPDATE OR DELETE ON ops.object_artifact FOR EACH ROW EXECUTE FUNCTION ops.reject_immutable_mutation()",
    "COMMENT ON TRIGGER trg_ops_object_artifact_immutable ON ops.object_artifact IS 'Reject normal mutation of the object artifact registry.'",
    "CREATE TRIGGER trg_ops_audit_event_immutable BEFORE UPDATE OR DELETE ON ops.audit_event FOR EACH ROW EXECUTE FUNCTION ops.reject_immutable_mutation()",
    "COMMENT ON TRIGGER trg_ops_audit_event_immutable ON ops.audit_event IS 'Reject normal mutation of the audit event ledger.'",
)


DOWNGRADE_STATEMENTS: tuple[str, ...] = (
    "SET LOCAL search_path = pg_catalog",
    "SET LOCAL TIME ZONE 'UTC'",
    "LOCK TABLE ops.object_artifact, ops.job, ops.job_attempt, ops.outbox_event, ops.inbox_receipt, ops.idempotency_record, ops.audit_event, iam.principal, ops.runtime_setting_version, iam.user_account, iam.service_principal, iam.role, iam.permission, iam.role_permission, iam.principal_role_assignment, iam.session_revocation, iam.break_glass_record IN ACCESS EXCLUSIVE MODE",
    "DO $raos_st0303_downgrade$\nDECLARE\n    nonempty_tables pg_catalog.text[] := ARRAY[]::pg_catalog.text[];\nBEGIN\n    IF EXISTS (SELECT 1 FROM ops.object_artifact LIMIT 1) THEN\n        nonempty_tables := pg_catalog.array_append(nonempty_tables, 'ops.object_artifact');\n    END IF;\n    IF EXISTS (SELECT 1 FROM ops.job LIMIT 1) THEN\n        nonempty_tables := pg_catalog.array_append(nonempty_tables, 'ops.job');\n    END IF;\n    IF EXISTS (SELECT 1 FROM ops.job_attempt LIMIT 1) THEN\n        nonempty_tables := pg_catalog.array_append(nonempty_tables, 'ops.job_attempt');\n    END IF;\n    IF EXISTS (SELECT 1 FROM ops.outbox_event LIMIT 1) THEN\n        nonempty_tables := pg_catalog.array_append(nonempty_tables, 'ops.outbox_event');\n    END IF;\n    IF EXISTS (SELECT 1 FROM ops.inbox_receipt LIMIT 1) THEN\n        nonempty_tables := pg_catalog.array_append(nonempty_tables, 'ops.inbox_receipt');\n    END IF;\n    IF EXISTS (SELECT 1 FROM ops.idempotency_record LIMIT 1) THEN\n        nonempty_tables := pg_catalog.array_append(nonempty_tables, 'ops.idempotency_record');\n    END IF;\n    IF EXISTS (SELECT 1 FROM ops.audit_event LIMIT 1) THEN\n        nonempty_tables := pg_catalog.array_append(nonempty_tables, 'ops.audit_event');\n    END IF;\n    IF EXISTS (SELECT 1 FROM iam.principal LIMIT 1) THEN\n        nonempty_tables := pg_catalog.array_append(nonempty_tables, 'iam.principal');\n    END IF;\n    IF EXISTS (SELECT 1 FROM ops.runtime_setting_version LIMIT 1) THEN\n        nonempty_tables := pg_catalog.array_append(nonempty_tables, 'ops.runtime_setting_version');\n    END IF;\n    IF EXISTS (SELECT 1 FROM iam.user_account LIMIT 1) THEN\n        nonempty_tables := pg_catalog.array_append(nonempty_tables, 'iam.user_account');\n    END IF;\n    IF EXISTS (SELECT 1 FROM iam.service_principal LIMIT 1) THEN\n        nonempty_tables := pg_catalog.array_append(nonempty_tables, 'iam.service_principal');\n    END IF;\n    IF EXISTS (SELECT 1 FROM iam.role LIMIT 1) THEN\n        nonempty_tables := pg_catalog.array_append(nonempty_tables, 'iam.role');\n    END IF;\n    IF EXISTS (SELECT 1 FROM iam.permission LIMIT 1) THEN\n        nonempty_tables := pg_catalog.array_append(nonempty_tables, 'iam.permission');\n    END IF;\n    IF EXISTS (SELECT 1 FROM iam.role_permission LIMIT 1) THEN\n        nonempty_tables := pg_catalog.array_append(nonempty_tables, 'iam.role_permission');\n    END IF;\n    IF EXISTS (SELECT 1 FROM iam.principal_role_assignment LIMIT 1) THEN\n        nonempty_tables := pg_catalog.array_append(nonempty_tables, 'iam.principal_role_assignment');\n    END IF;\n    IF EXISTS (SELECT 1 FROM iam.session_revocation LIMIT 1) THEN\n        nonempty_tables := pg_catalog.array_append(nonempty_tables, 'iam.session_revocation');\n    END IF;\n    IF EXISTS (SELECT 1 FROM iam.break_glass_record LIMIT 1) THEN\n        nonempty_tables := pg_catalog.array_append(nonempty_tables, 'iam.break_glass_record');\n    END IF;\n    IF pg_catalog.cardinality(nonempty_tables) <> 0 THEN\n        RAISE EXCEPTION USING\n            ERRCODE = '55000',\n            MESSAGE = 'ST0303_DOWNGRADE_NONEMPTY';\n    END IF;\nEND\n$raos_st0303_downgrade$",
    "DROP TABLE iam.break_glass_record RESTRICT",
    "DROP TABLE iam.session_revocation RESTRICT",
    "DROP TABLE iam.principal_role_assignment RESTRICT",
    "DROP TABLE iam.role_permission RESTRICT",
    "DROP TABLE iam.permission RESTRICT",
    "DROP TABLE iam.role RESTRICT",
    "DROP TABLE iam.service_principal RESTRICT",
    "DROP TABLE iam.user_account RESTRICT",
    "DROP TABLE ops.runtime_setting_version RESTRICT",
    "DROP TABLE iam.principal RESTRICT",
    "DROP TABLE ops.audit_event RESTRICT",
    "DROP TABLE ops.idempotency_record RESTRICT",
    "DROP TABLE ops.inbox_receipt RESTRICT",
    "DROP TABLE ops.outbox_event RESTRICT",
    "DROP TABLE ops.job_attempt RESTRICT",
    "DROP TABLE ops.job RESTRICT",
    "DROP TABLE ops.object_artifact RESTRICT",
    "DROP FUNCTION ops.reject_immutable_mutation() RESTRICT",
    "DROP FUNCTION ops.touch_mutable_row() RESTRICT",
)


def upgrade() -> None:
    for statement in UPGRADE_STATEMENTS:
        op.execute(statement)


def downgrade() -> None:
    for statement in DOWNGRADE_STATEMENTS:
        op.execute(statement)
