# Generated by repo://scripts/build_st1502_data_services.py; do not edit.
check "execution_is_disabled" {
  assert {
    condition     = var.activation_enabled == false && var.production_apply_authorized == false
    error_message = "Activation and Production apply authority must remain disabled."
  }
}

check "bindings_and_gate_evidence_are_unset" {
  assert {
    condition = alltrue([
      var.selected_provider_schema == null,
      var.selected_provider_plugin == null,
      var.selected_account_or_project == null,
      var.selected_primary_region == null,
      var.selected_backup_region == null,
      var.selected_state_backend == null,
      var.credential_source == null,
      length(var.network_segment_ids) == 0,
      length(var.security_policy_bindings) == 0,
      var.selected_retention_policy_id == null,
      length(var.supplied_gate_evidence) == 0,
    ])
    error_message = "Provider, account, region, backend, credential, network, policy, retention, and evidence bindings remain unset."
  }
}

check "private_and_encrypted_data_services" {
  assert {
    condition = alltrue([
      for node in values(local.logical_resources) :
      node.public_access == false &&
      (node.persisted_data == false || node.encryption_at_rest == true) &&
      (node.network_interaction == false || node.transport_encryption == true)
    ])
    error_message = "Every persisted or interacting data service must remain private and encrypted."
  }
}

check "backup_and_immutability_declarations" {
  assert {
    condition = alltrue([
      for node in values(local.logical_resources) :
      (node.backup_required == false || node.backup_declared == true) &&
      (node.immutable_required == false || node.immutable_declared == true)
    ])
    error_message = "Required backup, PITR, version, and immutability declarations cannot be omitted."
  }
}

check "primary_queues_have_dlqs" {
  assert {
    condition = alltrue([
      for node_id in ["queue_ingestion", "queue_ai", "queue_quality", "queue_publication", "queue_freshness", "queue_analytics", "queue_notification"] :
      local.logical_resources[node_id].dlq_required == true &&
      local.logical_resources[node_id].dlq_declared == true &&
      length([for edge in local.logical_edges : edge if edge.from == node_id && edge.relationship == "REDRIVES_TO"]) == 1
    ])
    error_message = "Every primary queue requires exactly one declared DLQ relationship."
  }
}

check "secrets_and_keys_are_material_free_and_rotatable" {
  assert {
    condition = alltrue([
      for node in values(local.logical_resources) :
      node.contains_secret_material == false &&
      (node.key_rotation_required == false || node.key_rotation_declared == true)
    ])
    error_message = "Generated configuration cannot contain secret material or an unrotatable required key."
  }
}

check "iam_is_least_privilege_and_wildcard_free" {
  assert {
    condition = alltrue([
      for node in values(local.logical_resources) : node.least_privilege == true && node.wildcard_iam == false
      ]) && alltrue(flatten([
        for permissions in values(local.iam_permissions) : [
          for permission in permissions : permission != "*" && !endswith(permission, ":*") && !endswith(permission, ".*")
        ]
    ]))
    error_message = "Logical IAM permission sets must remain explicit and wildcard-free."
  }
}

check "logical_plan_has_zero_actions" {
  assert {
    condition = length(local.logical_resources) == 37 && alltrue([
      for count in values(local.execution_boundary.planned_actions) : count == 0
    ]) && local.successor_activation_port.complete_gate_evidence == false
    error_message = "The logical graph cannot plan or authorize physical infrastructure actions."
  }
}
