# Generated by repo://scripts/build_st1502_data_services.py; do not edit.
locals {
  reference_architecture = {
    cloud               = "AWS"
    region              = "ap-northeast-1"
    classification      = "CURRENT_CANONICAL_REFERENCE_ARCHITECTURE_ONLY"
    selected_binding    = false
    evidence_substitute = false
  }

  logical_resources = {
    relational_database = {
      kind                     = "RELATIONAL_DATABASE"
      reference_service        = "RDS"
      persisted_data           = true
      network_interaction      = true
      public_access            = false
      encryption_at_rest       = true
      transport_encryption     = true
      backup_required          = true
      backup_declared          = true
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    object_raw = {
      kind                     = "OBJECT_STORAGE"
      reference_service        = "S3"
      persisted_data           = true
      network_interaction      = true
      public_access            = false
      encryption_at_rest       = true
      transport_encryption     = true
      backup_required          = true
      backup_declared          = true
      immutable_required       = true
      immutable_declared       = true
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    object_publication = {
      kind                     = "OBJECT_STORAGE"
      reference_service        = "S3"
      persisted_data           = true
      network_interaction      = true
      public_access            = false
      encryption_at_rest       = true
      transport_encryption     = true
      backup_required          = true
      backup_declared          = true
      immutable_required       = true
      immutable_declared       = true
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    object_uploads_quarantine = {
      kind                     = "OBJECT_STORAGE"
      reference_service        = "S3"
      persisted_data           = true
      network_interaction      = true
      public_access            = false
      encryption_at_rest       = true
      transport_encryption     = true
      backup_required          = true
      backup_declared          = true
      immutable_required       = true
      immutable_declared       = true
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    object_exports = {
      kind                     = "OBJECT_STORAGE"
      reference_service        = "S3"
      persisted_data           = true
      network_interaction      = true
      public_access            = false
      encryption_at_rest       = true
      transport_encryption     = true
      backup_required          = true
      backup_declared          = true
      immutable_required       = true
      immutable_declared       = true
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    object_audit_logs = {
      kind                     = "OBJECT_STORAGE"
      reference_service        = "S3"
      persisted_data           = true
      network_interaction      = true
      public_access            = false
      encryption_at_rest       = true
      transport_encryption     = true
      backup_required          = true
      backup_declared          = true
      immutable_required       = true
      immutable_declared       = true
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    queue_ingestion = {
      kind                     = "PRIMARY_QUEUE"
      reference_service        = "SQS"
      persisted_data           = true
      network_interaction      = true
      public_access            = false
      encryption_at_rest       = true
      transport_encryption     = true
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = true
      dlq_declared             = true
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    queue_ai = {
      kind                     = "PRIMARY_QUEUE"
      reference_service        = "SQS"
      persisted_data           = true
      network_interaction      = true
      public_access            = false
      encryption_at_rest       = true
      transport_encryption     = true
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = true
      dlq_declared             = true
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    queue_quality = {
      kind                     = "PRIMARY_QUEUE"
      reference_service        = "SQS"
      persisted_data           = true
      network_interaction      = true
      public_access            = false
      encryption_at_rest       = true
      transport_encryption     = true
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = true
      dlq_declared             = true
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    queue_publication = {
      kind                     = "PRIMARY_QUEUE"
      reference_service        = "SQS"
      persisted_data           = true
      network_interaction      = true
      public_access            = false
      encryption_at_rest       = true
      transport_encryption     = true
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = true
      dlq_declared             = true
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    queue_freshness = {
      kind                     = "PRIMARY_QUEUE"
      reference_service        = "SQS"
      persisted_data           = true
      network_interaction      = true
      public_access            = false
      encryption_at_rest       = true
      transport_encryption     = true
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = true
      dlq_declared             = true
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    queue_analytics = {
      kind                     = "PRIMARY_QUEUE"
      reference_service        = "SQS"
      persisted_data           = true
      network_interaction      = true
      public_access            = false
      encryption_at_rest       = true
      transport_encryption     = true
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = true
      dlq_declared             = true
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    queue_notification = {
      kind                     = "PRIMARY_QUEUE"
      reference_service        = "SQS"
      persisted_data           = true
      network_interaction      = true
      public_access            = false
      encryption_at_rest       = true
      transport_encryption     = true
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = true
      dlq_declared             = true
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    queue_ingestion_dlq = {
      kind                     = "DEAD_LETTER_QUEUE"
      reference_service        = "SQS"
      persisted_data           = true
      network_interaction      = true
      public_access            = false
      encryption_at_rest       = true
      transport_encryption     = true
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    queue_ai_dlq = {
      kind                     = "DEAD_LETTER_QUEUE"
      reference_service        = "SQS"
      persisted_data           = true
      network_interaction      = true
      public_access            = false
      encryption_at_rest       = true
      transport_encryption     = true
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    queue_quality_dlq = {
      kind                     = "DEAD_LETTER_QUEUE"
      reference_service        = "SQS"
      persisted_data           = true
      network_interaction      = true
      public_access            = false
      encryption_at_rest       = true
      transport_encryption     = true
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    queue_publication_dlq = {
      kind                     = "DEAD_LETTER_QUEUE"
      reference_service        = "SQS"
      persisted_data           = true
      network_interaction      = true
      public_access            = false
      encryption_at_rest       = true
      transport_encryption     = true
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    queue_freshness_dlq = {
      kind                     = "DEAD_LETTER_QUEUE"
      reference_service        = "SQS"
      persisted_data           = true
      network_interaction      = true
      public_access            = false
      encryption_at_rest       = true
      transport_encryption     = true
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    queue_analytics_dlq = {
      kind                     = "DEAD_LETTER_QUEUE"
      reference_service        = "SQS"
      persisted_data           = true
      network_interaction      = true
      public_access            = false
      encryption_at_rest       = true
      transport_encryption     = true
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    queue_notification_dlq = {
      kind                     = "DEAD_LETTER_QUEUE"
      reference_service        = "SQS"
      persisted_data           = true
      network_interaction      = true
      public_access            = false
      encryption_at_rest       = true
      transport_encryption     = true
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    secret_metadata = {
      kind                     = "SECRET_METADATA_BOUNDARY"
      reference_service        = "Secrets Manager"
      persisted_data           = true
      network_interaction      = true
      public_access            = false
      encryption_at_rest       = true
      transport_encryption     = true
      backup_required          = true
      backup_declared          = true
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    kms_relational = {
      kind                     = "ENCRYPTION_KEY"
      reference_service        = "KMS"
      persisted_data           = false
      network_interaction      = true
      public_access            = false
      encryption_at_rest       = false
      transport_encryption     = true
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = true
      key_rotation_declared    = true
      least_privilege          = true
      wildcard_iam             = false
    }
    kms_object_storage = {
      kind                     = "ENCRYPTION_KEY"
      reference_service        = "KMS"
      persisted_data           = false
      network_interaction      = true
      public_access            = false
      encryption_at_rest       = false
      transport_encryption     = true
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = true
      key_rotation_declared    = true
      least_privilege          = true
      wildcard_iam             = false
    }
    kms_queue = {
      kind                     = "ENCRYPTION_KEY"
      reference_service        = "KMS"
      persisted_data           = false
      network_interaction      = true
      public_access            = false
      encryption_at_rest       = false
      transport_encryption     = true
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = true
      key_rotation_declared    = true
      least_privilege          = true
      wildcard_iam             = false
    }
    kms_secret_metadata = {
      kind                     = "ENCRYPTION_KEY"
      reference_service        = "KMS"
      persisted_data           = false
      network_interaction      = true
      public_access            = false
      encryption_at_rest       = false
      transport_encryption     = true
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = true
      key_rotation_declared    = true
      least_privilege          = true
      wildcard_iam             = false
    }
    backup_relational_pitr = {
      kind                     = "RECOVERY_DECLARATION"
      reference_service        = "LOGICAL"
      persisted_data           = false
      network_interaction      = false
      public_access            = false
      encryption_at_rest       = false
      transport_encryption     = false
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    backup_object_versions = {
      kind                     = "RECOVERY_DECLARATION"
      reference_service        = "LOGICAL"
      persisted_data           = false
      network_interaction      = false
      public_access            = false
      encryption_at_rest       = false
      transport_encryption     = false
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    backup_configuration = {
      kind                     = "RECOVERY_DECLARATION"
      reference_service        = "LOGICAL"
      persisted_data           = false
      network_interaction      = false
      public_access            = false
      encryption_at_rest       = false
      transport_encryption     = false
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    iam_db_workload = {
      kind                     = "IAM_PERMISSION_SET"
      reference_service        = "LOGICAL"
      persisted_data           = false
      network_interaction      = false
      public_access            = false
      encryption_at_rest       = false
      transport_encryption     = false
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    iam_object_writer = {
      kind                     = "IAM_PERMISSION_SET"
      reference_service        = "LOGICAL"
      persisted_data           = false
      network_interaction      = false
      public_access            = false
      encryption_at_rest       = false
      transport_encryption     = false
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    iam_object_reader = {
      kind                     = "IAM_PERMISSION_SET"
      reference_service        = "LOGICAL"
      persisted_data           = false
      network_interaction      = false
      public_access            = false
      encryption_at_rest       = false
      transport_encryption     = false
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    iam_queue_producer = {
      kind                     = "IAM_PERMISSION_SET"
      reference_service        = "LOGICAL"
      persisted_data           = false
      network_interaction      = false
      public_access            = false
      encryption_at_rest       = false
      transport_encryption     = false
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    iam_queue_consumer = {
      kind                     = "IAM_PERMISSION_SET"
      reference_service        = "LOGICAL"
      persisted_data           = false
      network_interaction      = false
      public_access            = false
      encryption_at_rest       = false
      transport_encryption     = false
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    iam_queue_redrive_operator = {
      kind                     = "IAM_PERMISSION_SET"
      reference_service        = "LOGICAL"
      persisted_data           = false
      network_interaction      = false
      public_access            = false
      encryption_at_rest       = false
      transport_encryption     = false
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    iam_secret_reader = {
      kind                     = "IAM_PERMISSION_SET"
      reference_service        = "LOGICAL"
      persisted_data           = false
      network_interaction      = false
      public_access            = false
      encryption_at_rest       = false
      transport_encryption     = false
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    iam_backup_operator = {
      kind                     = "IAM_PERMISSION_SET"
      reference_service        = "LOGICAL"
      persisted_data           = false
      network_interaction      = false
      public_access            = false
      encryption_at_rest       = false
      transport_encryption     = false
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
    iam_restore_operator = {
      kind                     = "IAM_PERMISSION_SET"
      reference_service        = "LOGICAL"
      persisted_data           = false
      network_interaction      = false
      public_access            = false
      encryption_at_rest       = false
      transport_encryption     = false
      backup_required          = false
      backup_declared          = false
      immutable_required       = false
      immutable_declared       = false
      dlq_required             = false
      dlq_declared             = false
      contains_secret_material = false
      key_rotation_required    = false
      key_rotation_declared    = false
      least_privilege          = true
      wildcard_iam             = false
    }
  }

  logical_edges = [
    { from = "relational_database", to = "kms_relational", relationship = "ENCRYPTED_BY" },
    { from = "object_raw", to = "kms_object_storage", relationship = "ENCRYPTED_BY" },
    { from = "object_publication", to = "kms_object_storage", relationship = "ENCRYPTED_BY" },
    { from = "object_uploads_quarantine", to = "kms_object_storage", relationship = "ENCRYPTED_BY" },
    { from = "object_exports", to = "kms_object_storage", relationship = "ENCRYPTED_BY" },
    { from = "object_audit_logs", to = "kms_object_storage", relationship = "ENCRYPTED_BY" },
    { from = "queue_ingestion", to = "kms_queue", relationship = "ENCRYPTED_BY" },
    { from = "queue_ai", to = "kms_queue", relationship = "ENCRYPTED_BY" },
    { from = "queue_quality", to = "kms_queue", relationship = "ENCRYPTED_BY" },
    { from = "queue_publication", to = "kms_queue", relationship = "ENCRYPTED_BY" },
    { from = "queue_freshness", to = "kms_queue", relationship = "ENCRYPTED_BY" },
    { from = "queue_analytics", to = "kms_queue", relationship = "ENCRYPTED_BY" },
    { from = "queue_notification", to = "kms_queue", relationship = "ENCRYPTED_BY" },
    { from = "queue_ingestion_dlq", to = "kms_queue", relationship = "ENCRYPTED_BY" },
    { from = "queue_ai_dlq", to = "kms_queue", relationship = "ENCRYPTED_BY" },
    { from = "queue_quality_dlq", to = "kms_queue", relationship = "ENCRYPTED_BY" },
    { from = "queue_publication_dlq", to = "kms_queue", relationship = "ENCRYPTED_BY" },
    { from = "queue_freshness_dlq", to = "kms_queue", relationship = "ENCRYPTED_BY" },
    { from = "queue_analytics_dlq", to = "kms_queue", relationship = "ENCRYPTED_BY" },
    { from = "queue_notification_dlq", to = "kms_queue", relationship = "ENCRYPTED_BY" },
    { from = "secret_metadata", to = "kms_secret_metadata", relationship = "ENCRYPTED_BY" },
    { from = "queue_ingestion", to = "queue_ingestion_dlq", relationship = "REDRIVES_TO" },
    { from = "queue_ai", to = "queue_ai_dlq", relationship = "REDRIVES_TO" },
    { from = "queue_quality", to = "queue_quality_dlq", relationship = "REDRIVES_TO" },
    { from = "queue_publication", to = "queue_publication_dlq", relationship = "REDRIVES_TO" },
    { from = "queue_freshness", to = "queue_freshness_dlq", relationship = "REDRIVES_TO" },
    { from = "queue_analytics", to = "queue_analytics_dlq", relationship = "REDRIVES_TO" },
    { from = "queue_notification", to = "queue_notification_dlq", relationship = "REDRIVES_TO" },
    { from = "backup_relational_pitr", to = "relational_database", relationship = "PROTECTS" },
    { from = "backup_object_versions", to = "object_raw", relationship = "PROTECTS" },
    { from = "backup_object_versions", to = "object_publication", relationship = "PROTECTS" },
    { from = "backup_object_versions", to = "object_uploads_quarantine", relationship = "PROTECTS" },
    { from = "backup_object_versions", to = "object_exports", relationship = "PROTECTS" },
    { from = "backup_object_versions", to = "object_audit_logs", relationship = "PROTECTS" },
    { from = "backup_configuration", to = "secret_metadata", relationship = "RECONSTRUCTS" },
    { from = "backup_configuration", to = "kms_relational", relationship = "RECONSTRUCTS" },
    { from = "backup_configuration", to = "kms_object_storage", relationship = "RECONSTRUCTS" },
    { from = "backup_configuration", to = "kms_queue", relationship = "RECONSTRUCTS" },
    { from = "backup_configuration", to = "kms_secret_metadata", relationship = "RECONSTRUCTS" },
    { from = "iam_db_workload", to = "relational_database", relationship = "AUTHORIZES" },
    { from = "iam_object_writer", to = "object_raw", relationship = "AUTHORIZES" },
    { from = "iam_object_writer", to = "object_publication", relationship = "AUTHORIZES" },
    { from = "iam_object_writer", to = "object_uploads_quarantine", relationship = "AUTHORIZES" },
    { from = "iam_object_writer", to = "object_exports", relationship = "AUTHORIZES" },
    { from = "iam_object_writer", to = "object_audit_logs", relationship = "AUTHORIZES" },
    { from = "iam_object_reader", to = "object_raw", relationship = "AUTHORIZES" },
    { from = "iam_object_reader", to = "object_publication", relationship = "AUTHORIZES" },
    { from = "iam_object_reader", to = "object_uploads_quarantine", relationship = "AUTHORIZES" },
    { from = "iam_object_reader", to = "object_exports", relationship = "AUTHORIZES" },
    { from = "iam_object_reader", to = "object_audit_logs", relationship = "AUTHORIZES" },
    { from = "iam_queue_producer", to = "queue_ingestion", relationship = "AUTHORIZES" },
    { from = "iam_queue_producer", to = "queue_ai", relationship = "AUTHORIZES" },
    { from = "iam_queue_producer", to = "queue_quality", relationship = "AUTHORIZES" },
    { from = "iam_queue_producer", to = "queue_publication", relationship = "AUTHORIZES" },
    { from = "iam_queue_producer", to = "queue_freshness", relationship = "AUTHORIZES" },
    { from = "iam_queue_producer", to = "queue_analytics", relationship = "AUTHORIZES" },
    { from = "iam_queue_producer", to = "queue_notification", relationship = "AUTHORIZES" },
    { from = "iam_queue_consumer", to = "queue_ingestion", relationship = "AUTHORIZES" },
    { from = "iam_queue_consumer", to = "queue_ai", relationship = "AUTHORIZES" },
    { from = "iam_queue_consumer", to = "queue_quality", relationship = "AUTHORIZES" },
    { from = "iam_queue_consumer", to = "queue_publication", relationship = "AUTHORIZES" },
    { from = "iam_queue_consumer", to = "queue_freshness", relationship = "AUTHORIZES" },
    { from = "iam_queue_consumer", to = "queue_analytics", relationship = "AUTHORIZES" },
    { from = "iam_queue_consumer", to = "queue_notification", relationship = "AUTHORIZES" },
    { from = "iam_queue_redrive_operator", to = "queue_ingestion", relationship = "AUTHORIZES" },
    { from = "iam_queue_redrive_operator", to = "queue_ai", relationship = "AUTHORIZES" },
    { from = "iam_queue_redrive_operator", to = "queue_quality", relationship = "AUTHORIZES" },
    { from = "iam_queue_redrive_operator", to = "queue_publication", relationship = "AUTHORIZES" },
    { from = "iam_queue_redrive_operator", to = "queue_freshness", relationship = "AUTHORIZES" },
    { from = "iam_queue_redrive_operator", to = "queue_analytics", relationship = "AUTHORIZES" },
    { from = "iam_queue_redrive_operator", to = "queue_notification", relationship = "AUTHORIZES" },
    { from = "iam_queue_redrive_operator", to = "queue_ingestion_dlq", relationship = "AUTHORIZES" },
    { from = "iam_queue_redrive_operator", to = "queue_ai_dlq", relationship = "AUTHORIZES" },
    { from = "iam_queue_redrive_operator", to = "queue_quality_dlq", relationship = "AUTHORIZES" },
    { from = "iam_queue_redrive_operator", to = "queue_publication_dlq", relationship = "AUTHORIZES" },
    { from = "iam_queue_redrive_operator", to = "queue_freshness_dlq", relationship = "AUTHORIZES" },
    { from = "iam_queue_redrive_operator", to = "queue_analytics_dlq", relationship = "AUTHORIZES" },
    { from = "iam_queue_redrive_operator", to = "queue_notification_dlq", relationship = "AUTHORIZES" },
    { from = "iam_secret_reader", to = "secret_metadata", relationship = "AUTHORIZES" },
    { from = "iam_backup_operator", to = "backup_relational_pitr", relationship = "AUTHORIZES" },
    { from = "iam_backup_operator", to = "backup_object_versions", relationship = "AUTHORIZES" },
    { from = "iam_backup_operator", to = "backup_configuration", relationship = "AUTHORIZES" },
    { from = "iam_restore_operator", to = "backup_relational_pitr", relationship = "AUTHORIZES" },
    { from = "iam_restore_operator", to = "backup_object_versions", relationship = "AUTHORIZES" },
    { from = "iam_restore_operator", to = "backup_configuration", relationship = "AUTHORIZES" },
  ]

  iam_permissions = {
    iam_db_workload            = toset(["database.connect", "database.read", "database.write"])
    iam_object_writer          = toset(["object.create", "object.version.read"])
    iam_object_reader          = toset(["object.read", "object.version.read"])
    iam_queue_producer         = toset(["queue.send"])
    iam_queue_consumer         = toset(["queue.receive", "queue.delete", "queue.visibility.change"])
    iam_queue_redrive_operator = toset(["queue.redrive"])
    iam_secret_reader          = toset(["secret.metadata.read", "secret.value.resolve_by_workload"])
    iam_backup_operator        = toset(["backup.create", "backup.verify"])
    iam_restore_operator       = toset(["restore.isolated", "restore.verify"])
  }

  selected_configuration = {
    provider_schema          = var.selected_provider_schema
    provider_plugin          = var.selected_provider_plugin
    account_or_project       = var.selected_account_or_project
    primary_region           = var.selected_primary_region
    backup_region            = var.selected_backup_region
    state_backend            = var.selected_state_backend
    credential_source        = var.credential_source
    network_segments         = var.network_segment_ids
    security_policy_bindings = var.security_policy_bindings
    retention_policy_id      = var.selected_retention_policy_id
  }

  successor_activation_port = {
    classification                       = "CLOSED_PHYSICAL_RESOURCE_ACTIVATION_PORT"
    current_revision_activation          = "FORBIDDEN"
    successor_contract_revision_required = true
    required_gate_evidence = toset([
      "OD-013_RESOLVED_REGION_RESIDENCY",
      "OD-014_RESOLVED_RETENTION_DELETION",
      "OD-015_PROVIDER_CREDENTIAL_EVIDENCE",
      "TST-026_FORMAL_SECURITY_EVIDENCE",
      "TST-029_ISOLATED_RESTORE_EVIDENCE",
      "PROVIDER_SCHEMA_AND_PLUGIN_PROVENANCE",
      "PRIVATE_NETWORK_AND_ACCOUNT_ISOLATION",
      "LEAST_PRIVILEGE_POLICY_REVIEW",
      "BACKUP_RESTORE_AND_KEY_RECOVERY",
      "HUMAN_APPROVED_RELEASE_AND_ROLLBACK"
    ])
    supplied_gate_evidence   = var.supplied_gate_evidence
    complete_gate_evidence   = false
    provider_binding         = "FORBIDDEN_IN_CURRENT_REVISION"
    resource_materialization = "FORBIDDEN_IN_CURRENT_REVISION"
    infrastructure_plan      = "FORBIDDEN"
    infrastructure_apply     = "FORBIDDEN"
  }

  execution_boundary = {
    activation_enabled          = var.activation_enabled
    production_apply_authorized = var.production_apply_authorized
    provider_calls              = "FORBIDDEN"
    external_writes             = "FORBIDDEN"
    planned_actions = {
      create  = 0
      update  = 0
      delete  = 0
      migrate = 0
      backup  = 0
      restore = 0
      redrive = 0
      rotate  = 0
    }
  }
}
