# Generated by repo://scripts/build_st1502_data_services.py; do not edit.
output "reference_architecture" {
  description = "Canonical AWS reference metadata; never a selected provider binding."
  value       = local.reference_architecture
}

output "logical_resources" {
  description = "Provider-schema-free logical resource declarations."
  value       = local.logical_resources
}

output "logical_edges" {
  description = "Deterministic dependency, recovery, redrive, encryption, and authorization edges."
  value       = local.logical_edges
}

output "iam_permissions" {
  description = "Wildcard-free logical permission sets."
  value       = local.iam_permissions
}

output "activation_boundary" {
  description = "Closed successor activation port and zero-action execution boundary."
  value = {
    successor = local.successor_activation_port
    execution = local.execution_boundary
  }
}
