# Generated by repo://scripts/build_st1502_data_services.py; do not edit.
variable "activation_enabled" {
  description = "Current ST-1502 revision keeps this successor binding unset."
  type        = bool
  default     = false

  validation {
    condition     = var.activation_enabled == false
    error_message = "Physical activation requires a successor contract and external evidence."
  }
}

variable "production_apply_authorized" {
  description = "Current ST-1502 revision keeps this successor binding unset."
  type        = bool
  default     = false

  validation {
    condition     = var.production_apply_authorized == false
    error_message = "Physical activation requires a successor contract and external evidence."
  }
}

variable "selected_provider_schema" {
  description = "Current ST-1502 revision keeps this successor binding unset."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition     = var.selected_provider_schema == null
    error_message = "Physical activation requires a successor contract and external evidence."
  }
}

variable "selected_provider_plugin" {
  description = "Current ST-1502 revision keeps this successor binding unset."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition     = var.selected_provider_plugin == null
    error_message = "Physical activation requires a successor contract and external evidence."
  }
}

variable "selected_account_or_project" {
  description = "Current ST-1502 revision keeps this successor binding unset."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition     = var.selected_account_or_project == null
    error_message = "Physical activation requires a successor contract and external evidence."
  }
}

variable "selected_primary_region" {
  description = "Current ST-1502 revision keeps this successor binding unset."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition     = var.selected_primary_region == null
    error_message = "Physical activation requires a successor contract and external evidence."
  }
}

variable "selected_backup_region" {
  description = "Current ST-1502 revision keeps this successor binding unset."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition     = var.selected_backup_region == null
    error_message = "Physical activation requires a successor contract and external evidence."
  }
}

variable "selected_state_backend" {
  description = "Current ST-1502 revision keeps this successor binding unset."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition     = var.selected_state_backend == null
    error_message = "Physical activation requires a successor contract and external evidence."
  }
}

variable "credential_source" {
  description = "Current ST-1502 revision keeps this successor binding unset."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition     = var.credential_source == null
    error_message = "Physical activation requires a successor contract and external evidence."
  }
}

variable "network_segment_ids" {
  description = "Current ST-1502 revision keeps this successor binding unset."
  type        = list(string)
  default     = []

  validation {
    condition     = length(var.network_segment_ids) == 0
    error_message = "Physical activation requires a successor contract and external evidence."
  }
}

variable "security_policy_bindings" {
  description = "Current ST-1502 revision keeps this successor binding unset."
  type        = list(string)
  default     = []

  validation {
    condition     = length(var.security_policy_bindings) == 0
    error_message = "Physical activation requires a successor contract and external evidence."
  }
}

variable "selected_retention_policy_id" {
  description = "Current ST-1502 revision keeps this successor binding unset."
  type        = string
  default     = null
  nullable    = true

  validation {
    condition     = var.selected_retention_policy_id == null
    error_message = "Physical activation requires a successor contract and external evidence."
  }
}

variable "supplied_gate_evidence" {
  description = "Current ST-1502 revision keeps this successor binding unset."
  type        = set(string)
  default     = []

  validation {
    condition     = length(var.supplied_gate_evidence) == 0
    error_message = "Physical activation requires a successor contract and external evidence."
  }
}
