-- Generated by scripts/build_st0305_publication_analytics_finance.py; do not edit.
-- Story ST-0305 local candidate validation for exact PostgreSQL 18.4.
SET search_path = pg_catalog;
SET TIME ZONE 'UTC';

DO $raos_st0305_validation$
DECLARE
    mismatch_count bigint;
    inventory record;
BEGIN
    IF pg_catalog.current_setting('server_version_num') <> '180004' THEN
        RAISE EXCEPTION 'ST0305_SERVER_VERSION_MISMATCH';
    END IF;
    IF (SELECT pg_catalog.count(*) FROM public.raos_migration_version) <> 1
       OR (SELECT pg_catalog.max(version_num) FROM public.raos_migration_version)
          IS DISTINCT FROM '202608030005' THEN
        RAISE EXCEPTION 'ST0305_REVISION_MISMATCH';
    END IF;
    IF NOT EXISTS (
        SELECT 1 FROM public.raos_migration_history
        WHERE revision_id = '202608030005' AND story_id = 'ST-0305'
          AND direction = 'UPGRADE' AND status = 'SUCCEEDED'
          AND runner_version = '1.4.0'
          AND server_version_num = 180004
          AND source_sha256 = '08e7f75a005e960dca0af9a7fe7cacbe90040aaafeea01d1f5a279a84bcdf38b'
    ) THEN
        RAISE EXCEPTION 'ST0305_HISTORY_MISMATCH';
    END IF;

    WITH selected AS (
        SELECT oid FROM pg_catalog.pg_namespace
        WHERE nspname = ANY(ARRAY['publishing', 'freshness', 'analytics', 'finance', 'readmodel'])
    )
    SELECT
        (SELECT pg_catalog.count(*) FROM pg_catalog.pg_class
         WHERE relnamespace IN (SELECT oid FROM selected) AND relkind = 'r'),
        (SELECT pg_catalog.count(*) FROM pg_catalog.pg_attribute AS attribute
         JOIN pg_catalog.pg_class AS relation ON relation.oid = attribute.attrelid
         WHERE relation.relnamespace IN (SELECT oid FROM selected)
           AND relation.relkind = 'r' AND attribute.attnum > 0
           AND attribute.attisdropped IS FALSE),
        (SELECT pg_catalog.count(*) FROM pg_catalog.pg_attribute AS attribute
         JOIN pg_catalog.pg_class AS relation ON relation.oid = attribute.attrelid
         WHERE relation.relnamespace IN (SELECT oid FROM selected)
           AND relation.relkind = 'r' AND attribute.attnum > 0
           AND attribute.attisdropped IS FALSE AND attribute.attnotnull IS TRUE),
        (SELECT pg_catalog.count(*) FROM pg_catalog.pg_constraint
         WHERE connamespace IN (SELECT oid FROM selected) AND contype = 'p'),
        (SELECT pg_catalog.count(*) FROM pg_catalog.pg_constraint
         WHERE connamespace IN (SELECT oid FROM selected) AND contype = 'u'),
        (SELECT pg_catalog.count(*) FROM pg_catalog.pg_constraint
         WHERE connamespace IN (SELECT oid FROM selected) AND contype = 'c'),
        (SELECT pg_catalog.count(*) FROM pg_catalog.pg_constraint
         WHERE connamespace IN (SELECT oid FROM selected) AND contype = 'f'),
        (SELECT pg_catalog.count(*) FROM pg_catalog.pg_index AS index_record
         JOIN pg_catalog.pg_class AS relation ON relation.oid = index_record.indrelid
         WHERE relation.relnamespace IN (SELECT oid FROM selected)
           AND NOT EXISTS (SELECT 1 FROM pg_catalog.pg_constraint
                           WHERE conindid = index_record.indexrelid)),
        (SELECT pg_catalog.count(*) FROM pg_catalog.pg_index AS index_record
         JOIN pg_catalog.pg_class AS relation ON relation.oid = index_record.indrelid
         WHERE relation.relnamespace IN (SELECT oid FROM selected)),
        (SELECT pg_catalog.count(*) FROM pg_catalog.pg_proc
         WHERE pronamespace IN (SELECT oid FROM selected) AND prokind = 'f'),
        (SELECT pg_catalog.count(*) FROM pg_catalog.pg_trigger AS trigger_record
         JOIN pg_catalog.pg_class AS relation ON relation.oid = trigger_record.tgrelid
         WHERE relation.relnamespace IN (SELECT oid FROM selected)
           AND trigger_record.tgisinternal IS FALSE)
    INTO inventory;
    IF inventory <> ROW(39::bigint, 629::bigint, 447::bigint, 39::bigint,
                         47::bigint, 172::bigint, 150::bigint, 153::bigint,
                         239::bigint, 3::bigint, 17::bigint) THEN
        RAISE EXCEPTION 'ST0305_INVENTORY_MISMATCH';
    END IF;


    WITH selected(schema_name) AS (
        SELECT pg_catalog.unnest(ARRAY[
            'publishing', 'freshness', 'analytics', 'finance', 'readmodel'
        ]::pg_catalog.text[])
    ),
    relation_rows AS (
        SELECT pg_catalog.concat_ws(
                   E'\x1f', namespace.nspname, relation.relname,
                   relation.relkind, relation.relpersistence,
                   relation.relreplident, relation.relrowsecurity,
                   relation.relforcerowsecurity,
                   COALESCE(
                       pg_catalog.array_to_string(relation.reloptions, E'\x1d'),
                       '<NULL>'
                   ),
                   COALESCE(
                       pg_catalog.obj_description(relation.oid, 'pg_class'),
                       '<NULL>'
                   )
               ) AS row_value
        FROM pg_catalog.pg_class AS relation
        JOIN pg_catalog.pg_namespace AS namespace
          ON namespace.oid = relation.relnamespace
        JOIN selected ON selected.schema_name = namespace.nspname
        WHERE relation.relkind IN ('r', 'v')
    ),
    column_rows AS (
        SELECT pg_catalog.concat_ws(
                   E'\x1f', namespace.nspname, relation.relname,
                   attribute.attnum, attribute.attname,
                   pg_catalog.format_type(attribute.atttypid, attribute.atttypmod),
                   attribute.attnotnull, attribute.attidentity,
                   attribute.attgenerated, attribute.attisdropped,
                   COALESCE(
                       pg_catalog.pg_get_expr(
                           attribute_default.adbin,
                           attribute_default.adrelid,
                           false
                       ),
                       '<NULL>'
                   ),
                   COALESCE(
                       collation_namespace.nspname || '.'
                       || collation_record.collname,
                       '<NULL>'
                   ),
                   attribute.attstorage, attribute.attcompression,
                   attribute.attstattarget,
                   COALESCE(
                       pg_catalog.col_description(
                           relation.oid, attribute.attnum
                       ),
                       '<NULL>'
                   )
               ) AS row_value
        FROM pg_catalog.pg_class AS relation
        JOIN pg_catalog.pg_namespace AS namespace
          ON namespace.oid = relation.relnamespace
        JOIN selected ON selected.schema_name = namespace.nspname
        JOIN pg_catalog.pg_attribute AS attribute
          ON attribute.attrelid = relation.oid AND attribute.attnum > 0
        LEFT JOIN pg_catalog.pg_attrdef AS attribute_default
          ON attribute_default.adrelid = relation.oid
         AND attribute_default.adnum = attribute.attnum
        LEFT JOIN pg_catalog.pg_collation AS collation_record
          ON collation_record.oid = attribute.attcollation
        LEFT JOIN pg_catalog.pg_namespace AS collation_namespace
          ON collation_namespace.oid = collation_record.collnamespace
        WHERE relation.relkind = 'r'
    ),
    constraint_rows AS (
        SELECT pg_catalog.concat_ws(
                   E'\x1f', namespace.nspname, relation.relname,
                   constraint_record.conname, constraint_record.contype,
                   constraint_record.condeferrable,
                   constraint_record.condeferred,
                   constraint_record.convalidated,
                   constraint_record.connoinherit,
                   constraint_record.confmatchtype,
                   constraint_record.confupdtype,
                   constraint_record.confdeltype,
                   COALESCE(
                       pg_catalog.pg_get_constraintdef(
                           constraint_record.oid, false
                       ),
                       '<NULL>'
                   )
               ) AS row_value
        FROM pg_catalog.pg_constraint AS constraint_record
        JOIN pg_catalog.pg_class AS relation
          ON relation.oid = constraint_record.conrelid
        JOIN pg_catalog.pg_namespace AS namespace
          ON namespace.oid = relation.relnamespace
        JOIN selected ON selected.schema_name = namespace.nspname
        WHERE constraint_record.contype IN ('c', 'f', 'n', 'p', 'u')
    ),
    index_rows AS (
        SELECT pg_catalog.concat_ws(
                   E'\x1f', namespace.nspname, table_record.relname,
                   index_record.relname, index_catalog.indisunique,
                   index_catalog.indisprimary, index_catalog.indisexclusion,
                   index_catalog.indimmediate, index_catalog.indisclustered,
                   index_catalog.indisvalid, index_catalog.indisready,
                   index_catalog.indislive, index_catalog.indisreplident,
                   index_catalog.indnullsnotdistinct,
                   index_catalog.indnkeyatts, index_catalog.indnatts,
                   index_catalog.indkey::pg_catalog.text,
                   index_catalog.indcollation::pg_catalog.text,
                   index_catalog.indclass::pg_catalog.text,
                   index_catalog.indoption::pg_catalog.text,
                   pg_catalog.pg_get_indexdef(index_record.oid, 0, false),
                   COALESCE(
                       pg_catalog.pg_get_expr(
                           index_catalog.indpred, index_catalog.indrelid, false
                       ),
                       '<NULL>'
                   ),
                   COALESCE(
                       pg_catalog.pg_get_expr(
                           index_catalog.indexprs, index_catalog.indrelid, false
                       ),
                       '<NULL>'
                   ),
                   COALESCE(
                       pg_catalog.obj_description(index_record.oid, 'pg_class'),
                       '<NULL>'
                   )
               ) AS row_value
        FROM pg_catalog.pg_index AS index_catalog
        JOIN pg_catalog.pg_class AS index_record
          ON index_record.oid = index_catalog.indexrelid
        JOIN pg_catalog.pg_class AS table_record
          ON table_record.oid = index_catalog.indrelid
        JOIN pg_catalog.pg_namespace AS namespace
          ON namespace.oid = table_record.relnamespace
        JOIN selected ON selected.schema_name = namespace.nspname
    ),
    function_rows AS (
        SELECT pg_catalog.concat_ws(
                   E'\x1f', namespace.nspname, routine.proname,
                   pg_catalog.pg_get_function_identity_arguments(routine.oid),
                   pg_catalog.pg_get_function_result(routine.oid),
                   language_record.lanname, routine.provolatile,
                   routine.proisstrict, routine.prosecdef,
                   routine.proleakproof, routine.proparallel,
                   COALESCE(
                       pg_catalog.array_to_string(routine.proconfig, E'\x1d'),
                       '<NULL>'
                   ),
                   pg_catalog.pg_get_functiondef(routine.oid),
                   COALESCE(
                       pg_catalog.obj_description(routine.oid, 'pg_proc'),
                       '<NULL>'
                   )
               ) AS row_value
        FROM pg_catalog.pg_proc AS routine
        JOIN pg_catalog.pg_namespace AS namespace
          ON namespace.oid = routine.pronamespace
        JOIN selected ON selected.schema_name = namespace.nspname
        JOIN pg_catalog.pg_language AS language_record
          ON language_record.oid = routine.prolang
        WHERE routine.prokind = 'f'
    ),
    trigger_rows AS (
        SELECT pg_catalog.concat_ws(
                   E'\x1f', namespace.nspname, relation.relname,
                   trigger_record.tgname, trigger_record.tgtype,
                   trigger_record.tgenabled, trigger_record.tgisinternal,
                   routine_namespace.nspname, routine.proname,
                   pg_catalog.pg_get_function_identity_arguments(routine.oid),
                   pg_catalog.pg_get_triggerdef(trigger_record.oid, false),
                   COALESCE(
                       pg_catalog.pg_get_expr(
                           trigger_record.tgqual,
                           trigger_record.tgrelid,
                           false
                       ),
                       '<NULL>'
                   ),
                   COALESCE(
                       pg_catalog.obj_description(
                           trigger_record.oid, 'pg_trigger'
                       ),
                       '<NULL>'
                   )
               ) AS row_value
        FROM pg_catalog.pg_trigger AS trigger_record
        JOIN pg_catalog.pg_class AS relation
          ON relation.oid = trigger_record.tgrelid
        JOIN pg_catalog.pg_namespace AS namespace
          ON namespace.oid = relation.relnamespace
        JOIN selected ON selected.schema_name = namespace.nspname
        JOIN pg_catalog.pg_proc AS routine
          ON routine.oid = trigger_record.tgfoid
        JOIN pg_catalog.pg_namespace AS routine_namespace
          ON routine_namespace.oid = routine.pronamespace
        WHERE trigger_record.tgisinternal IS FALSE
    ),
    observed(kind, object_count, digest) AS (
        SELECT 'relations', pg_catalog.count(*),
               pg_catalog.md5(pg_catalog.string_agg(
                   row_value, E'\x1e' ORDER BY row_value
               ))
        FROM relation_rows
        UNION ALL
        SELECT 'columns', pg_catalog.count(*),
               pg_catalog.md5(pg_catalog.string_agg(
                   row_value, E'\x1e' ORDER BY row_value
               ))
        FROM column_rows
        UNION ALL
        SELECT 'constraints', pg_catalog.count(*),
               pg_catalog.md5(pg_catalog.string_agg(
                   row_value, E'\x1e' ORDER BY row_value
               ))
        FROM constraint_rows
        UNION ALL
        SELECT 'indexes', pg_catalog.count(*),
               pg_catalog.md5(pg_catalog.string_agg(
                   row_value, E'\x1e' ORDER BY row_value
               ))
        FROM index_rows
        UNION ALL
        SELECT 'functions', pg_catalog.count(*),
               pg_catalog.md5(pg_catalog.string_agg(
                   row_value, E'\x1e' ORDER BY row_value
               ))
        FROM function_rows
        UNION ALL
        SELECT 'triggers', pg_catalog.count(*),
               pg_catalog.md5(pg_catalog.string_agg(
                   row_value, E'\x1e' ORDER BY row_value
               ))
        FROM trigger_rows
    ),
    expected(kind, object_count, digest) AS (VALUES
        ('relations', 39, '8b7c92be0f2fd5402a424d95eea5233a'),
        ('columns', 629, '5b45839a79986b7f09e97d9c18ab2ebb'),
        ('constraints', 855, '486df24518366f36689d83135245b0fa'),
        ('indexes', 239, 'caa0c0ba455c58af334ea02bd0afa319'),
        ('functions', 3, '92c2ea81850bf9cb5357e173476705f7'),
        ('triggers', 17, 'abbe0bced5705576cfce1a2dc2e0e615')
    )
    SELECT pg_catalog.count(*) INTO mismatch_count
    FROM expected
    FULL JOIN observed USING (kind)
    WHERE observed.kind IS NULL OR expected.kind IS NULL
       OR observed.object_count IS DISTINCT FROM expected.object_count
       OR observed.digest IS DISTINCT FROM expected.digest;
    IF mismatch_count <> 0 THEN
        RAISE EXCEPTION 'ST0305_CATALOG_FINGERPRINT_MISMATCH';
    END IF;


    WITH expected(schema_name, description) AS (VALUES
        ('publishing', '人間Review、Approval、Publication Snapshot、公開状態、Route、Rollback'),
        ('freshness', '鮮度SLA、Refresh、Staleness、Affiliate Link検査、影響分析'),
        ('analytics', '匿名行動、楽天クリック、GSC・GA4取込、帰属推定、日次指標'),
        ('finance', '成果原本取込、発生・確定・取消、費用配賦、確定ユニットエコノミクス'),
        ('readmodel', '公開Rendererが読む安全な再生成可能Projection')
    )
    SELECT pg_catalog.count(*) INTO mismatch_count
    FROM expected
    LEFT JOIN pg_catalog.pg_namespace AS namespace
      ON namespace.nspname = expected.schema_name
    WHERE namespace.oid IS NULL
       OR pg_catalog.pg_get_userbyid(namespace.nspowner)
          IS DISTINCT FROM current_user
       OR pg_catalog.obj_description(namespace.oid, 'pg_namespace')
          IS DISTINCT FROM expected.description
       OR EXISTS (
           SELECT 1
           FROM pg_catalog.aclexplode(
               COALESCE(
                   namespace.nspacl,
                   pg_catalog.acldefault('n', namespace.nspowner)
               )
           ) AS acl
           WHERE acl.grantee <> namespace.nspowner
       );
    IF mismatch_count <> 0 THEN
        RAISE EXCEPTION 'ST0305_SCHEMA_COMMENT_MISMATCH';
    END IF;

    WITH expected(schema_name, table_name, description) AS (VALUES
        ('publishing', 'review_assignment', '記事Versionに対する編集・Fact・Compliance等のHuman Review担当、期限、進行状態を管理する。'),
        ('publishing', 'review_decision', 'Human Reviewerが特定Assignment・記事Versionへ下したDecisionを追記し、後から上書きしない。'),
        ('publishing', 'approval', '記事Versionに対するEditorial・Compliance・Final approval/revocationを独立した監査事実として追記する。'),
        ('publishing', 'publication_candidate', '公開要求の冪等受付、最終Approval、Quality Run、Snapshot build状態、Block理由を管理する。'),
        ('publishing', 'publication_snapshot', '承認済みArticle Versionから生成した公開内容・Product Card・Structured Dataの不変Snapshot manifest。'),
        ('publishing', 'publication', 'サイト・記事・Channel単位の現在公開状態とCurrent Snapshotを保持する制御Record。公開内容自体はSnapshotを正本とする。'),
        ('publishing', 'publication_event', 'Publish・Unpublish・Suspend・Resume・Rollback・Projection完了を時系列で追記する監査Event。'),
        ('publishing', 'public_route', 'Canonical path、Redirect、Noindex、Route ownerを管理し、同一Siteで同時に同じPathを所有させない。'),
        ('publishing', 'rollback_record', '誤公開・不具合時に、対象Publicationを以前の不変Snapshotへ戻した事実、検証、承認を保存する。'),
        ('freshness', 'freshness_policy', 'カテゴリ・記事種別・Fact種別ごとの最大Age、Warning、Critical、再取得CadenceをVersion管理する。'),
        ('freshness', 'refresh_schedule', 'Product・Offer・Article・Link等の次回Refresh due、Lease、連続失敗、優先度を一元管理する。'),
        ('freshness', 'refresh_run', 'Scheduleまたは手動要求に基づくRefresh batchの範囲、Job、結果件数、Cursor、Errorを管理する。'),
        ('freshness', 'staleness_assessment', '特定対象のObservation age・Policy・Fresh/Warning/Critical判定と推奨Actionを追記する。'),
        ('freshness', 'link_check', '楽天Affiliate URLを経由せず検査し、HTTP・Destination host・API再取得一致・Riskを履歴化する。'),
        ('freshness', 'impact_assessment', 'Source/Product/Offer変更がClaim・記事・公開Snapshotへ与える影響と必要Actionを追記する。'),
        ('analytics', 'anonymous_event', '個人識別情報を保存せず、Consent状態付きでPage view・CTA表示・Click等を受け付ける短期Event。'),
        ('analytics', 'affiliate_click_event', '楽天URLへ直接遷移させつつsendBeacon等で取得したクリック文脈を追記する。Redirect gatewayには使用しない。'),
        ('analytics', 'import_run', 'Search Console・GA4等の集計取込範囲、Watermark、原本Artifact、件数、再実行状態を管理する。'),
        ('analytics', 'gsc_observation', 'Search Console APIから取得した日・query・page等の集計値。Queryはsanitizeし、低Volume抑制を維持する。'),
        ('analytics', 'ga4_observation', 'GA4 Data APIの集計Grainをdimension/metric schema versionとhashで保存する。Event raw exportはMVP対象外。'),
        ('analytics', 'attribution_estimate', 'Provider Factと自サイト観測を混同せず、Direct・Estimated・Unattributedの配賦候補とConfidenceをVersion化する。'),
        ('analytics', 'data_quality_finding', 'Analytics取込の欠損、重複、集計不一致、Privacy violation、遅延をSource/Run/Dateへ紐付ける。'),
        ('analytics', 'daily_article_metric', '日次・記事単位のPV、Session、検索表示、楽天Click等を再生成可能なProjectionとして保持する。'),
        ('finance', 'parser_version', '楽天成果CSV等のProvider・FormatごとのParser code/schema/test fixture versionを不変登録する。'),
        ('finance', 'revenue_import', '成果原本UploadからMalware/形式検査、Dry Run、人間確認、Canonical import、突合までの状態を管理する。'),
        ('finance', 'revenue_import_row', '成果原本の各行をLine hashとParser resultで追跡するStaging。原文全体はArtifact、DBは必要最小限の正規化値のみ。'),
        ('finance', 'commission', '楽天側の発生・確定・取消をCanonical provider factとして保持する。記事帰属や推定値をこのRecordへ上書きしない。'),
        ('finance', 'commission_event', 'Commissionの発生・確定・取消・金額変更をProvider event順に追記し、現在状態の根拠にする。'),
        ('finance', 'external_cost', 'LLM・API・Hosting・Tool等の外部費用をInvoice/Usage根拠付きでJPYへ正規化して追記する。'),
        ('finance', 'human_work_log', '制作・編集・Review・更新等の人間作業時間と原価を記事・カテゴリへ配賦可能な形で記録する。'),
        ('finance', 'allocation_rule', '外部費用・人件費をSite/Category/Articleへ配賦するMethod、Weight、Scope、Versionを不変管理する。'),
        ('finance', 'cost_allocation', '特定原価をArticle/Category/SiteへRuleに従って配賦した不変結果。Source総額との合計一致をDQで検証する。'),
        ('finance', 'unit_economics_snapshot', 'Site/Category/Article単位の確定報酬、変動費、人件費、確定EPC/RPM、貢献利益を月次Versionとして凍結する。'),
        ('readmodel', 'public_article', '公開Rendererが読む現在記事Projection。承認済みPublication Snapshotからのみ再生成し、編集DBを直接参照させない。'),
        ('readmodel', 'public_article_block', '公開Snapshotの表示順Block、Sanitize済みHTML/JSON、Block hashを保持するProjection。'),
        ('readmodel', 'public_product_card', '公開記事内のProduct表示名、比較属性、Badge、画像参照をSnapshot単位で保持する。報酬率は含めない。'),
        ('readmodel', 'public_offer', '公開Product Cardに紐づく価格・在庫・楽天Affiliate URL・観測時刻を保持する安全Projection。料率・収益情報は禁止。'),
        ('readmodel', 'public_route', 'Public WebのPath解決に必要なArticle/Redirect/Gone Projection。公開RoleはこのSchema以外を読まない。'),
        ('readmodel', 'runtime_control', 'Public Rendererが低Latencyで参照するPublication/Affiliate Link Kill Switchの安全Projection。障害時は停止側へ倒す。')
    )
    SELECT pg_catalog.count(*) INTO mismatch_count
    FROM expected
    LEFT JOIN pg_catalog.pg_namespace AS namespace
      ON namespace.nspname = expected.schema_name
    LEFT JOIN pg_catalog.pg_class AS relation
      ON relation.relnamespace = namespace.oid
     AND relation.relname = expected.table_name AND relation.relkind = 'r'
    WHERE relation.oid IS NULL
       OR pg_catalog.obj_description(relation.oid, 'pg_class')
          IS DISTINCT FROM expected.description;
    IF mismatch_count <> 0 THEN
        RAISE EXCEPTION 'ST0305_TABLE_COMMENT_MISMATCH';
    END IF;

    WITH expected(schema_name, table_name, column_name, description) AS (VALUES
        ('publishing', 'review_assignment', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('publishing', 'review_assignment', 'display_id', 'RVA-接頭辞を持つアプリケーション生成の不変表示ID。'),
        ('publishing', 'review_assignment', 'article_version_id', '記事の特定Version。'),
        ('publishing', 'review_assignment', 'review_type', 'review type'),
        ('publishing', 'review_assignment', 'assigned_to_principal_id', 'assigned to principal id'),
        ('publishing', 'review_assignment', 'assigned_by_principal_id', 'assigned by principal id'),
        ('publishing', 'review_assignment', 'status', '業務状態を示す安定Enum文字列。'),
        ('publishing', 'review_assignment', 'priority', 'priority'),
        ('publishing', 'review_assignment', 'due_at', 'due at'),
        ('publishing', 'review_assignment', 'started_at', 'started at'),
        ('publishing', 'review_assignment', 'completed_at', 'completed at'),
        ('publishing', 'review_assignment', 'cancelled_at', 'cancelled at'),
        ('publishing', 'review_assignment', 'instructions', 'instructions'),
        ('publishing', 'review_assignment', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('publishing', 'review_assignment', 'updated_at', '最終更新時刻。UTCのtimestamptz。'),
        ('publishing', 'review_assignment', 'lock_version', '楽観的排他制御用の単調増加Version。'),
        ('publishing', 'review_decision', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('publishing', 'review_decision', 'display_id', 'RVD-接頭辞を持つアプリケーション生成の不変表示ID。'),
        ('publishing', 'review_decision', 'review_assignment_id', 'review assignment id'),
        ('publishing', 'review_decision', 'article_version_id', '記事の特定Version。'),
        ('publishing', 'review_decision', 'decision', 'decision'),
        ('publishing', 'review_decision', 'summary', 'summary'),
        ('publishing', 'review_decision', 'checklist_results', 'Review checklist項目・結果・Evidence locator。'),
        ('publishing', 'review_decision', 'decision_artifact_id', 'decision artifact id'),
        ('publishing', 'review_decision', 'decided_by_principal_id', 'decided by principal id'),
        ('publishing', 'review_decision', 'decided_at', 'decided at'),
        ('publishing', 'review_decision', 'supersedes_decision_id', 'supersedes decision id'),
        ('publishing', 'review_decision', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('publishing', 'approval', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('publishing', 'approval', 'display_id', 'APR-接頭辞を持つアプリケーション生成の不変表示ID。'),
        ('publishing', 'approval', 'article_version_id', '記事の特定Version。'),
        ('publishing', 'approval', 'approval_type', 'approval type'),
        ('publishing', 'approval', 'decision', 'decision'),
        ('publishing', 'approval', 'quality_check_run_id', 'quality check run id'),
        ('publishing', 'approval', 'policy_bundle_id', 'policy bundle id'),
        ('publishing', 'approval', 'decision_reason', 'decision reason'),
        ('publishing', 'approval', 'approved_by_principal_id', 'approved by principal id'),
        ('publishing', 'approval', 'approved_at', 'approved at'),
        ('publishing', 'approval', 'valid_until', 'valid until'),
        ('publishing', 'approval', 'revoked_at', 'revoked at'),
        ('publishing', 'approval', 'revoked_by_principal_id', 'revoked by principal id'),
        ('publishing', 'approval', 'revocation_reason', 'revocation reason'),
        ('publishing', 'approval', 'supersedes_approval_id', 'supersedes approval id'),
        ('publishing', 'approval', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('publishing', 'publication_candidate', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('publishing', 'publication_candidate', 'display_id', 'PBC-接頭辞を持つアプリケーション生成の不変表示ID。'),
        ('publishing', 'publication_candidate', 'site_id', '対象サイト。MVPは1サイトだが将来の複数サイトを識別可能にする。'),
        ('publishing', 'publication_candidate', 'article_version_id', '記事の特定Version。'),
        ('publishing', 'publication_candidate', 'final_approval_id', 'final approval id'),
        ('publishing', 'publication_candidate', 'quality_check_run_id', 'quality check run id'),
        ('publishing', 'publication_candidate', 'requested_by_principal_id', 'requested by principal id'),
        ('publishing', 'publication_candidate', 'request_idempotency_key', 'request idempotency key'),
        ('publishing', 'publication_candidate', 'status', '業務状態を示す安定Enum文字列。'),
        ('publishing', 'publication_candidate', 'snapshot_build_job_id', 'snapshot build job id'),
        ('publishing', 'publication_candidate', 'publication_snapshot_id', 'publication snapshot id'),
        ('publishing', 'publication_candidate', 'blocked_reason_code', 'blocked reason code'),
        ('publishing', 'publication_candidate', 'blocked_detail', 'blocked detail'),
        ('publishing', 'publication_candidate', 'requested_at', 'requested at'),
        ('publishing', 'publication_candidate', 'completed_at', 'completed at'),
        ('publishing', 'publication_candidate', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('publishing', 'publication_candidate', 'updated_at', '最終更新時刻。UTCのtimestamptz。'),
        ('publishing', 'publication_candidate', 'lock_version', '楽観的排他制御用の単調増加Version。'),
        ('publishing', 'publication_snapshot', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('publishing', 'publication_snapshot', 'display_id', 'PBS-接頭辞を持つアプリケーション生成の不変表示ID。'),
        ('publishing', 'publication_snapshot', 'site_id', '対象サイト。MVPは1サイトだが将来の複数サイトを識別可能にする。'),
        ('publishing', 'publication_snapshot', 'article_id', '論理記事ID。'),
        ('publishing', 'publication_snapshot', 'article_version_id', '記事の特定Version。'),
        ('publishing', 'publication_snapshot', 'publication_candidate_id', 'publication candidate id'),
        ('publishing', 'publication_snapshot', 'artifact_id', 'S3互換Object Storage上の不変Artifactレジストリ。'),
        ('publishing', 'publication_snapshot', 'schema_version', 'schema version'),
        ('publishing', 'publication_snapshot', 'content_sha256', 'content sha256'),
        ('publishing', 'publication_snapshot', 'source_packet_version_id', 'source packet version id'),
        ('publishing', 'publication_snapshot', 'policy_bundle_id', 'policy bundle id'),
        ('publishing', 'publication_snapshot', 'quality_check_run_id', 'quality check run id'),
        ('publishing', 'publication_snapshot', 'final_approval_id', 'final approval id'),
        ('publishing', 'publication_snapshot', 'canonical_path', 'canonical path'),
        ('publishing', 'publication_snapshot', 'title', 'title'),
        ('publishing', 'publication_snapshot', 'meta_title', 'meta title'),
        ('publishing', 'publication_snapshot', 'meta_description', 'meta description'),
        ('publishing', 'publication_snapshot', 'disclosure_text', 'disclosure text'),
        ('publishing', 'publication_snapshot', 'manifest', '公開Block、Product/Card refs、Structured Data、Asset hash、Freshness metadata。'),
        ('publishing', 'publication_snapshot', 'built_by_job_id', 'built by job id'),
        ('publishing', 'publication_snapshot', 'built_at', 'built at'),
        ('publishing', 'publication_snapshot', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('publishing', 'publication', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('publishing', 'publication', 'display_id', 'PUB-接頭辞を持つアプリケーション生成の不変表示ID。'),
        ('publishing', 'publication', 'site_id', '対象サイト。MVPは1サイトだが将来の複数サイトを識別可能にする。'),
        ('publishing', 'publication', 'article_id', '論理記事ID。'),
        ('publishing', 'publication', 'channel', 'channel'),
        ('publishing', 'publication', 'state', 'state'),
        ('publishing', 'publication', 'current_snapshot_id', 'current snapshot id'),
        ('publishing', 'publication', 'current_route_id', 'current route id'),
        ('publishing', 'publication', 'first_published_at', 'first published at'),
        ('publishing', 'publication', 'last_published_at', 'last published at'),
        ('publishing', 'publication', 'unpublished_at', 'unpublished at'),
        ('publishing', 'publication', 'etag', 'etag'),
        ('publishing', 'publication', 'projection_generation', 'projection generation'),
        ('publishing', 'publication', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('publishing', 'publication', 'updated_at', '最終更新時刻。UTCのtimestamptz。'),
        ('publishing', 'publication', 'lock_version', '楽観的排他制御用の単調増加Version。'),
        ('publishing', 'publication_event', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('publishing', 'publication_event', 'display_id', 'PUE-接頭辞を持つアプリケーション生成の不変表示ID。'),
        ('publishing', 'publication_event', 'publication_id', 'publication id'),
        ('publishing', 'publication_event', 'event_type', 'event type'),
        ('publishing', 'publication_event', 'from_snapshot_id', 'from snapshot id'),
        ('publishing', 'publication_event', 'to_snapshot_id', 'to snapshot id'),
        ('publishing', 'publication_event', 'publication_candidate_id', 'publication candidate id'),
        ('publishing', 'publication_event', 'release_id', 'release id'),
        ('publishing', 'publication_event', 'actor_type', 'actor type'),
        ('publishing', 'publication_event', 'actor_id', 'actor id'),
        ('publishing', 'publication_event', 'reason_code', 'reason code'),
        ('publishing', 'publication_event', 'reason_detail', 'reason detail'),
        ('publishing', 'publication_event', 'correlation_id', '要求・Job・Eventを横断して追跡するCorrelation ID。'),
        ('publishing', 'publication_event', 'occurred_at', 'occurred at'),
        ('publishing', 'publication_event', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('publishing', 'public_route', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('publishing', 'public_route', 'display_id', 'RTE-接頭辞を持つアプリケーション生成の不変表示ID。'),
        ('publishing', 'public_route', 'site_id', '対象サイト。MVPは1サイトだが将来の複数サイトを識別可能にする。'),
        ('publishing', 'public_route', 'path', 'path'),
        ('publishing', 'public_route', 'route_type', 'route type'),
        ('publishing', 'public_route', 'article_id', '論理記事ID。'),
        ('publishing', 'public_route', 'publication_id', 'publication id'),
        ('publishing', 'public_route', 'redirect_target_route_id', 'redirect target route id'),
        ('publishing', 'public_route', 'http_status', 'http status'),
        ('publishing', 'public_route', 'is_indexable', 'is indexable'),
        ('publishing', 'public_route', 'status', '業務状態を示す安定Enum文字列。'),
        ('publishing', 'public_route', 'activated_at', 'activated at'),
        ('publishing', 'public_route', 'deactivated_at', 'deactivated at'),
        ('publishing', 'public_route', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('publishing', 'public_route', 'updated_at', '最終更新時刻。UTCのtimestamptz。'),
        ('publishing', 'public_route', 'lock_version', '楽観的排他制御用の単調増加Version。'),
        ('publishing', 'rollback_record', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('publishing', 'rollback_record', 'display_id', 'RBK-接頭辞を持つアプリケーション生成の不変表示ID。'),
        ('publishing', 'rollback_record', 'publication_id', 'publication id'),
        ('publishing', 'rollback_record', 'from_snapshot_id', 'from snapshot id'),
        ('publishing', 'rollback_record', 'to_snapshot_id', 'to snapshot id'),
        ('publishing', 'rollback_record', 'incident_id', 'incident id'),
        ('publishing', 'rollback_record', 'requested_by_principal_id', 'requested by principal id'),
        ('publishing', 'rollback_record', 'approved_by_principal_id', 'approved by principal id'),
        ('publishing', 'rollback_record', 'executed_by_principal_id', 'executed by principal id'),
        ('publishing', 'rollback_record', 'status', '業務状態を示す安定Enum文字列。'),
        ('publishing', 'rollback_record', 'reason', 'reason'),
        ('publishing', 'rollback_record', 'verification_result', 'verification result'),
        ('publishing', 'rollback_record', 'requested_at', 'requested at'),
        ('publishing', 'rollback_record', 'executed_at', 'executed at'),
        ('publishing', 'rollback_record', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('freshness', 'freshness_policy', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('freshness', 'freshness_policy', 'display_id', 'FPL-接頭辞を持つアプリケーション生成の不変表示ID。'),
        ('freshness', 'freshness_policy', 'site_id', '対象サイト。MVPは1サイトだが将来の複数サイトを識別可能にする。'),
        ('freshness', 'freshness_policy', 'category_id', '対象カテゴリ。'),
        ('freshness', 'freshness_policy', 'article_type', 'article type'),
        ('freshness', 'freshness_policy', 'fact_type', 'fact type'),
        ('freshness', 'freshness_policy', 'version_no', 'Aggregate内で1から増加する不変Version番号。'),
        ('freshness', 'freshness_policy', 'warning_after', 'warning after'),
        ('freshness', 'freshness_policy', 'critical_after', 'critical after'),
        ('freshness', 'freshness_policy', 'refresh_interval', 'refresh interval'),
        ('freshness', 'freshness_policy', 'on_critical_action', 'on critical action'),
        ('freshness', 'freshness_policy', 'effective_from', '設定・関係が有効になる時刻。'),
        ('freshness', 'freshness_policy', 'effective_to', '設定・関係の有効終了時刻。NULLは終了未定。'),
        ('freshness', 'freshness_policy', 'created_by_principal_id', '作成操作を行ったIAM Principal。'),
        ('freshness', 'freshness_policy', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('freshness', 'refresh_schedule', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('freshness', 'refresh_schedule', 'site_id', '対象サイト。MVPは1サイトだが将来の複数サイトを識別可能にする。'),
        ('freshness', 'refresh_schedule', 'target_type', 'target type'),
        ('freshness', 'refresh_schedule', 'target_id', 'target id'),
        ('freshness', 'refresh_schedule', 'freshness_policy_id', 'freshness policy id'),
        ('freshness', 'refresh_schedule', 'status', '業務状態を示す安定Enum文字列。'),
        ('freshness', 'refresh_schedule', 'priority', 'priority'),
        ('freshness', 'refresh_schedule', 'next_due_at', 'next due at'),
        ('freshness', 'refresh_schedule', 'last_started_at', 'last started at'),
        ('freshness', 'refresh_schedule', 'last_succeeded_at', 'last succeeded at'),
        ('freshness', 'refresh_schedule', 'consecutive_failure_count', 'consecutive failure count'),
        ('freshness', 'refresh_schedule', 'lease_owner', 'lease owner'),
        ('freshness', 'refresh_schedule', 'lease_until', 'lease until'),
        ('freshness', 'refresh_schedule', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('freshness', 'refresh_schedule', 'updated_at', '最終更新時刻。UTCのtimestamptz。'),
        ('freshness', 'refresh_schedule', 'lock_version', '楽観的排他制御用の単調増加Version。'),
        ('freshness', 'refresh_run', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('freshness', 'refresh_run', 'display_id', 'RFR-接頭辞を持つアプリケーション生成の不変表示ID。'),
        ('freshness', 'refresh_run', 'site_id', '対象サイト。MVPは1サイトだが将来の複数サイトを識別可能にする。'),
        ('freshness', 'refresh_run', 'ops_job_id', 'ops job id'),
        ('freshness', 'refresh_run', 'run_type', 'run type'),
        ('freshness', 'refresh_run', 'scope_type', 'scope type'),
        ('freshness', 'refresh_run', 'scope_id', 'scope id'),
        ('freshness', 'refresh_run', 'status', '業務状態を示す安定Enum文字列。'),
        ('freshness', 'refresh_run', 'started_at', 'started at'),
        ('freshness', 'refresh_run', 'completed_at', 'completed at'),
        ('freshness', 'refresh_run', 'target_count', 'target count'),
        ('freshness', 'refresh_run', 'success_count', 'success count'),
        ('freshness', 'refresh_run', 'failure_count', 'failure count'),
        ('freshness', 'refresh_run', 'continuation', 'Provider cursor・page・resume token。'),
        ('freshness', 'refresh_run', 'report_artifact_id', 'report artifact id'),
        ('freshness', 'refresh_run', 'error_summary', 'error summary'),
        ('freshness', 'refresh_run', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('freshness', 'staleness_assessment', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('freshness', 'staleness_assessment', 'site_id', '対象サイト。MVPは1サイトだが将来の複数サイトを識別可能にする。'),
        ('freshness', 'staleness_assessment', 'target_type', 'target type'),
        ('freshness', 'staleness_assessment', 'target_id', 'target id'),
        ('freshness', 'staleness_assessment', 'freshness_policy_id', 'freshness policy id'),
        ('freshness', 'staleness_assessment', 'observation_id', 'observation id'),
        ('freshness', 'staleness_assessment', 'observation_at', 'observation at'),
        ('freshness', 'staleness_assessment', 'assessed_at', 'assessed at'),
        ('freshness', 'staleness_assessment', 'age_seconds', 'age seconds'),
        ('freshness', 'staleness_assessment', 'freshness_status', 'freshness status'),
        ('freshness', 'staleness_assessment', 'recommended_action', 'recommended action'),
        ('freshness', 'staleness_assessment', 'reason_code', 'reason code'),
        ('freshness', 'staleness_assessment', 'refresh_run_id', 'refresh run id'),
        ('freshness', 'staleness_assessment', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('freshness', 'link_check', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('freshness', 'link_check', 'site_id', '対象サイト。MVPは1サイトだが将来の複数サイトを識別可能にする。'),
        ('freshness', 'link_check', 'offer_id', 'ショップ単位の販売Offer。'),
        ('freshness', 'link_check', 'affiliate_link_observation_id', 'affiliate link observation id'),
        ('freshness', 'link_check', 'refresh_run_id', 'refresh run id'),
        ('freshness', 'link_check', 'checked_at', 'checked at'),
        ('freshness', 'link_check', 'check_method', 'check method'),
        ('freshness', 'link_check', 'result', 'result'),
        ('freshness', 'link_check', 'http_status', 'http status'),
        ('freshness', 'link_check', 'destination_host', 'destination host'),
        ('freshness', 'link_check', 'destination_url_sha256', 'destination url sha256'),
        ('freshness', 'link_check', 'latency_ms', 'latency ms'),
        ('freshness', 'link_check', 'risk_code', 'risk code'),
        ('freshness', 'link_check', 'response_artifact_id', 'response artifact id'),
        ('freshness', 'link_check', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('freshness', 'impact_assessment', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('freshness', 'impact_assessment', 'change_type', 'change type'),
        ('freshness', 'impact_assessment', 'changed_entity_type', 'changed entity type'),
        ('freshness', 'impact_assessment', 'changed_entity_id', 'changed entity id'),
        ('freshness', 'impact_assessment', 'article_id', '論理記事ID。'),
        ('freshness', 'impact_assessment', 'article_version_id', '記事の特定Version。'),
        ('freshness', 'impact_assessment', 'claim_id', 'claim id'),
        ('freshness', 'impact_assessment', 'publication_id', 'publication id'),
        ('freshness', 'impact_assessment', 'impact_level', 'impact level'),
        ('freshness', 'impact_assessment', 'required_action', 'required action'),
        ('freshness', 'impact_assessment', 'reason', 'reason'),
        ('freshness', 'impact_assessment', 'detected_at', 'detected at'),
        ('freshness', 'impact_assessment', 'resolved_at', 'resolved at'),
        ('freshness', 'impact_assessment', 'resolved_by_job_id', 'resolved by job id'),
        ('freshness', 'impact_assessment', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('analytics', 'anonymous_event', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('analytics', 'anonymous_event', 'event_id', 'event id'),
        ('analytics', 'anonymous_event', 'site_id', '対象サイト。MVPは1サイトだが将来の複数サイトを識別可能にする。'),
        ('analytics', 'anonymous_event', 'event_type', 'event type'),
        ('analytics', 'anonymous_event', 'occurred_at', 'occurred at'),
        ('analytics', 'anonymous_event', 'received_at', 'received at'),
        ('analytics', 'anonymous_event', 'business_date', 'business date'),
        ('analytics', 'anonymous_event', 'session_pseudonym_sha256', 'session pseudonym sha256'),
        ('analytics', 'anonymous_event', 'visitor_pseudonym_sha256', 'visitor pseudonym sha256'),
        ('analytics', 'anonymous_event', 'consent_state', 'consent state'),
        ('analytics', 'anonymous_event', 'privacy_mode', 'privacy mode'),
        ('analytics', 'anonymous_event', 'article_id', '論理記事ID。'),
        ('analytics', 'anonymous_event', 'article_version_id', '記事の特定Version。'),
        ('analytics', 'anonymous_event', 'publication_snapshot_id', 'publication snapshot id'),
        ('analytics', 'anonymous_event', 'product_id', '正規化されたCanonical Product。'),
        ('analytics', 'anonymous_event', 'offer_id', 'ショップ単位の販売Offer。'),
        ('analytics', 'anonymous_event', 'page_path', 'page path'),
        ('analytics', 'anonymous_event', 'referrer_host', 'referrer host'),
        ('analytics', 'anonymous_event', 'device_class', 'device class'),
        ('analytics', 'anonymous_event', 'country_code', 'country code'),
        ('analytics', 'anonymous_event', 'event_properties', 'Allowlist済み低Cardinality属性のみ。URL query、IP、raw UA、email等は禁止。'),
        ('analytics', 'anonymous_event', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('analytics', 'affiliate_click_event', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('analytics', 'affiliate_click_event', 'anonymous_event_id', 'anonymous event id'),
        ('analytics', 'affiliate_click_event', 'site_id', '対象サイト。MVPは1サイトだが将来の複数サイトを識別可能にする。'),
        ('analytics', 'affiliate_click_event', 'article_id', '論理記事ID。'),
        ('analytics', 'affiliate_click_event', 'article_version_id', '記事の特定Version。'),
        ('analytics', 'affiliate_click_event', 'publication_snapshot_id', 'publication snapshot id'),
        ('analytics', 'affiliate_click_event', 'product_id', '正規化されたCanonical Product。'),
        ('analytics', 'affiliate_click_event', 'offer_id', 'ショップ単位の販売Offer。'),
        ('analytics', 'affiliate_click_event', 'affiliate_link_observation_id', 'affiliate link observation id'),
        ('analytics', 'affiliate_click_event', 'destination_host', 'destination host'),
        ('analytics', 'affiliate_click_event', 'destination_url_sha256', 'destination url sha256'),
        ('analytics', 'affiliate_click_event', 'cta_key', 'cta key'),
        ('analytics', 'affiliate_click_event', 'block_key', 'block key'),
        ('analytics', 'affiliate_click_event', 'position_index', 'position index'),
        ('analytics', 'affiliate_click_event', 'occurred_at', 'occurred at'),
        ('analytics', 'affiliate_click_event', 'business_date', 'business date'),
        ('analytics', 'affiliate_click_event', 'delivery_state', 'delivery state'),
        ('analytics', 'affiliate_click_event', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('analytics', 'import_run', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('analytics', 'import_run', 'display_id', 'AIR-接頭辞を持つアプリケーション生成の不変表示ID。'),
        ('analytics', 'import_run', 'site_id', '対象サイト。MVPは1サイトだが将来の複数サイトを識別可能にする。'),
        ('analytics', 'import_run', 'source_type', 'source type'),
        ('analytics', 'import_run', 'ops_job_id', 'ops job id'),
        ('analytics', 'import_run', 'source_artifact_id', 'source artifact id'),
        ('analytics', 'import_run', 'status', '業務状態を示す安定Enum文字列。'),
        ('analytics', 'import_run', 'date_from', 'date from'),
        ('analytics', 'import_run', 'date_to', 'date to'),
        ('analytics', 'import_run', 'dimensions', '要求したdimension・filter・property等。'),
        ('analytics', 'import_run', 'watermark', 'watermark'),
        ('analytics', 'import_run', 'row_count', 'row count'),
        ('analytics', 'import_run', 'inserted_count', 'inserted count'),
        ('analytics', 'import_run', 'rejected_count', 'rejected count'),
        ('analytics', 'import_run', 'started_at', 'started at'),
        ('analytics', 'import_run', 'completed_at', 'completed at'),
        ('analytics', 'import_run', 'error_summary', 'error summary'),
        ('analytics', 'import_run', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('analytics', 'gsc_observation', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('analytics', 'gsc_observation', 'import_run_id', 'import run id'),
        ('analytics', 'gsc_observation', 'site_id', '対象サイト。MVPは1サイトだが将来の複数サイトを識別可能にする。'),
        ('analytics', 'gsc_observation', 'metric_date', 'metric date'),
        ('analytics', 'gsc_observation', 'query_text', 'query text'),
        ('analytics', 'gsc_observation', 'query_sha256', 'query sha256'),
        ('analytics', 'gsc_observation', 'page_path', 'page path'),
        ('analytics', 'gsc_observation', 'country_code', 'country code'),
        ('analytics', 'gsc_observation', 'device', 'device'),
        ('analytics', 'gsc_observation', 'search_appearance', 'search appearance'),
        ('analytics', 'gsc_observation', 'clicks', 'clicks'),
        ('analytics', 'gsc_observation', 'impressions', 'impressions'),
        ('analytics', 'gsc_observation', 'ctr', 'ctr'),
        ('analytics', 'gsc_observation', 'average_position', 'average position'),
        ('analytics', 'gsc_observation', 'is_privacy_suppressed', 'is privacy suppressed'),
        ('analytics', 'gsc_observation', 'dimension_key_sha256', 'dimension key sha256'),
        ('analytics', 'gsc_observation', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('analytics', 'ga4_observation', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('analytics', 'ga4_observation', 'import_run_id', 'import run id'),
        ('analytics', 'ga4_observation', 'site_id', '対象サイト。MVPは1サイトだが将来の複数サイトを識別可能にする。'),
        ('analytics', 'ga4_observation', 'metric_date', 'metric date'),
        ('analytics', 'ga4_observation', 'dimension_schema_version', 'dimension schema version'),
        ('analytics', 'ga4_observation', 'dimensions', 'pagePath、deviceCategory等のAllowlist dimension。'),
        ('analytics', 'ga4_observation', 'metrics', 'sessions、views、engagedSessions等の非負集計値。'),
        ('analytics', 'ga4_observation', 'grain_key_sha256', 'grain key sha256'),
        ('analytics', 'ga4_observation', 'is_thresholded', 'is thresholded'),
        ('analytics', 'ga4_observation', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('analytics', 'attribution_estimate', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('analytics', 'attribution_estimate', 'display_id', 'ATE-接頭辞を持つアプリケーション生成の不変表示ID。'),
        ('analytics', 'attribution_estimate', 'site_id', '対象サイト。MVPは1サイトだが将来の複数サイトを識別可能にする。'),
        ('analytics', 'attribution_estimate', 'commission_id', 'commission id'),
        ('analytics', 'attribution_estimate', 'article_id', '論理記事ID。'),
        ('analytics', 'attribution_estimate', 'publication_snapshot_id', 'publication snapshot id'),
        ('analytics', 'attribution_estimate', 'attribution_type', 'attribution type'),
        ('analytics', 'attribution_estimate', 'method_version', 'method version'),
        ('analytics', 'attribution_estimate', 'allocation_ratio', 'allocation ratio'),
        ('analytics', 'attribution_estimate', 'confidence_score', 'confidence score'),
        ('analytics', 'attribution_estimate', 'signals', 'Time window、click count、direct provider fields等。Raw identifierは不可。'),
        ('analytics', 'attribution_estimate', 'status', '業務状態を示す安定Enum文字列。'),
        ('analytics', 'attribution_estimate', 'approved_by_principal_id', 'approved by principal id'),
        ('analytics', 'attribution_estimate', 'approved_at', 'approved at'),
        ('analytics', 'attribution_estimate', 'calculated_by_job_id', 'calculated by job id'),
        ('analytics', 'attribution_estimate', 'calculated_at', 'calculated at'),
        ('analytics', 'attribution_estimate', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('analytics', 'data_quality_finding', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('analytics', 'data_quality_finding', 'site_id', '対象サイト。MVPは1サイトだが将来の複数サイトを識別可能にする。'),
        ('analytics', 'data_quality_finding', 'import_run_id', 'import run id'),
        ('analytics', 'data_quality_finding', 'finding_code', 'finding code'),
        ('analytics', 'data_quality_finding', 'severity', 'severity'),
        ('analytics', 'data_quality_finding', 'status', '業務状態を示す安定Enum文字列。'),
        ('analytics', 'data_quality_finding', 'metric_date', 'metric date'),
        ('analytics', 'data_quality_finding', 'message', 'message'),
        ('analytics', 'data_quality_finding', 'evidence', 'Expected/actual/count/hashのみ。PIIは格納しない。'),
        ('analytics', 'data_quality_finding', 'detected_at', 'detected at'),
        ('analytics', 'data_quality_finding', 'resolved_at', 'resolved at'),
        ('analytics', 'data_quality_finding', 'resolved_by_principal_id', 'resolved by principal id'),
        ('analytics', 'data_quality_finding', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('analytics', 'daily_article_metric', 'site_id', '対象サイト。MVPは1サイトだが将来の複数サイトを識別可能にする。'),
        ('analytics', 'daily_article_metric', 'article_id', '論理記事ID。'),
        ('analytics', 'daily_article_metric', 'metric_date', 'metric date'),
        ('analytics', 'daily_article_metric', 'publication_snapshot_id', 'publication snapshot id'),
        ('analytics', 'daily_article_metric', 'page_views', 'page views'),
        ('analytics', 'daily_article_metric', 'sessions', 'sessions'),
        ('analytics', 'daily_article_metric', 'engaged_sessions', 'engaged sessions'),
        ('analytics', 'daily_article_metric', 'affiliate_clicks', 'affiliate clicks'),
        ('analytics', 'daily_article_metric', 'gsc_clicks', 'gsc clicks'),
        ('analytics', 'daily_article_metric', 'gsc_impressions', 'gsc impressions'),
        ('analytics', 'daily_article_metric', 'average_position', 'average position'),
        ('analytics', 'daily_article_metric', 'affiliate_click_rate', 'affiliate click rate'),
        ('analytics', 'daily_article_metric', 'source_watermark', 'source watermark'),
        ('analytics', 'daily_article_metric', 'projection_version', 'projection version'),
        ('analytics', 'daily_article_metric', 'updated_at', '最終更新時刻。UTCのtimestamptz。'),
        ('finance', 'parser_version', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('finance', 'parser_version', 'provider_code', 'provider code'),
        ('finance', 'parser_version', 'format_code', 'format code'),
        ('finance', 'parser_version', 'version', 'version'),
        ('finance', 'parser_version', 'code_sha256', 'code sha256'),
        ('finance', 'parser_version', 'schema_artifact_id', 'schema artifact id'),
        ('finance', 'parser_version', 'fixture_artifact_id', 'fixture artifact id'),
        ('finance', 'parser_version', 'status', '業務状態を示す安定Enum文字列。'),
        ('finance', 'parser_version', 'released_at', 'released at'),
        ('finance', 'parser_version', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('finance', 'revenue_import', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('finance', 'revenue_import', 'display_id', 'RVI-接頭辞を持つアプリケーション生成の不変表示ID。'),
        ('finance', 'revenue_import', 'site_id', '対象サイト。MVPは1サイトだが将来の複数サイトを識別可能にする。'),
        ('finance', 'revenue_import', 'provider_code', 'provider code'),
        ('finance', 'revenue_import', 'source_artifact_id', 'source artifact id'),
        ('finance', 'revenue_import', 'source_sha256', 'source sha256'),
        ('finance', 'revenue_import', 'parser_version_id', 'parser version id'),
        ('finance', 'revenue_import', 'ops_job_id', 'ops job id'),
        ('finance', 'revenue_import', 'status', '業務状態を示す安定Enum文字列。'),
        ('finance', 'revenue_import', 'is_dry_run', 'is dry run'),
        ('finance', 'revenue_import', 'period_from', 'period from'),
        ('finance', 'revenue_import', 'period_to', 'period to'),
        ('finance', 'revenue_import', 'row_count', 'row count'),
        ('finance', 'revenue_import', 'accepted_count', 'accepted count'),
        ('finance', 'revenue_import', 'rejected_count', 'rejected count'),
        ('finance', 'revenue_import', 'gross_order_amount_jpy', 'gross order amount jpy'),
        ('finance', 'revenue_import', 'commission_amount_jpy', 'commission amount jpy'),
        ('finance', 'revenue_import', 'confirmed_by_principal_id', 'confirmed by principal id'),
        ('finance', 'revenue_import', 'confirmed_at', 'confirmed at'),
        ('finance', 'revenue_import', 'reconciliation_status', 'reconciliation status'),
        ('finance', 'revenue_import', 'report_artifact_id', 'report artifact id'),
        ('finance', 'revenue_import', 'error_summary', 'error summary'),
        ('finance', 'revenue_import', 'uploaded_at', 'uploaded at'),
        ('finance', 'revenue_import', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('finance', 'revenue_import', 'updated_at', '最終更新時刻。UTCのtimestamptz。'),
        ('finance', 'revenue_import', 'lock_version', '楽観的排他制御用の単調増加Version。'),
        ('finance', 'revenue_import_row', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('finance', 'revenue_import_row', 'revenue_import_id', 'revenue import id'),
        ('finance', 'revenue_import_row', 'row_no', 'row no'),
        ('finance', 'revenue_import_row', 'row_sha256', 'row sha256'),
        ('finance', 'revenue_import_row', 'parse_status', 'parse status'),
        ('finance', 'revenue_import_row', 'provider_event_id', 'provider event id'),
        ('finance', 'revenue_import_row', 'provider_order_id_sha256', 'provider order id sha256'),
        ('finance', 'revenue_import_row', 'event_type', 'event type'),
        ('finance', 'revenue_import_row', 'occurred_at', 'occurred at'),
        ('finance', 'revenue_import_row', 'business_date', 'business date'),
        ('finance', 'revenue_import_row', 'gross_order_amount_jpy', 'gross order amount jpy'),
        ('finance', 'revenue_import_row', 'commission_amount_jpy', 'commission amount jpy'),
        ('finance', 'revenue_import_row', 'currency', 'currency'),
        ('finance', 'revenue_import_row', 'error_code', 'error code'),
        ('finance', 'revenue_import_row', 'error_detail', 'error detail'),
        ('finance', 'revenue_import_row', 'normalized_extra', 'Allowlist済みProvider固有field。'),
        ('finance', 'revenue_import_row', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('finance', 'commission', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('finance', 'commission', 'display_id', 'COM-接頭辞を持つアプリケーション生成の不変表示ID。'),
        ('finance', 'commission', 'site_id', '対象サイト。MVPは1サイトだが将来の複数サイトを識別可能にする。'),
        ('finance', 'commission', 'provider_code', 'provider code'),
        ('finance', 'commission', 'provider_event_id', 'provider event id'),
        ('finance', 'commission', 'provider_order_id_sha256', 'provider order id sha256'),
        ('finance', 'commission', 'source_import_row_id', 'source import row id'),
        ('finance', 'commission', 'status', '業務状態を示す安定Enum文字列。'),
        ('finance', 'commission', 'ordered_at', 'ordered at'),
        ('finance', 'commission', 'confirmed_at', 'confirmed at'),
        ('finance', 'commission', 'cancelled_at', 'cancelled at'),
        ('finance', 'commission', 'business_month', 'business month'),
        ('finance', 'commission', 'gross_order_amount_jpy', 'gross order amount jpy'),
        ('finance', 'commission', 'confirmed_order_amount_jpy', 'confirmed order amount jpy'),
        ('finance', 'commission', 'generated_commission_jpy', 'generated commission jpy'),
        ('finance', 'commission', 'confirmed_commission_jpy', 'confirmed commission jpy'),
        ('finance', 'commission', 'currency', 'currency'),
        ('finance', 'commission', 'provider_category_code', 'provider category code'),
        ('finance', 'commission', 'provider_shop_code', 'provider shop code'),
        ('finance', 'commission', 'provider_item_code', 'provider item code'),
        ('finance', 'commission', 'last_event_at', 'last event at'),
        ('finance', 'commission', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('finance', 'commission', 'updated_at', '最終更新時刻。UTCのtimestamptz。'),
        ('finance', 'commission', 'lock_version', '楽観的排他制御用の単調増加Version。'),
        ('finance', 'commission_event', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('finance', 'commission_event', 'commission_id', 'commission id'),
        ('finance', 'commission_event', 'source_import_row_id', 'source import row id'),
        ('finance', 'commission_event', 'event_sequence', 'event sequence'),
        ('finance', 'commission_event', 'event_type', 'event type'),
        ('finance', 'commission_event', 'from_status', 'from status'),
        ('finance', 'commission_event', 'to_status', 'to status'),
        ('finance', 'commission_event', 'gross_order_amount_jpy', 'gross order amount jpy'),
        ('finance', 'commission_event', 'commission_amount_jpy', 'commission amount jpy'),
        ('finance', 'commission_event', 'provider_occurred_at', 'provider occurred at'),
        ('finance', 'commission_event', 'recorded_at', 'recorded at'),
        ('finance', 'commission_event', 'event_sha256', 'event sha256'),
        ('finance', 'commission_event', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('finance', 'external_cost', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('finance', 'external_cost', 'display_id', 'CST-接頭辞を持つアプリケーション生成の不変表示ID。'),
        ('finance', 'external_cost', 'site_id', '対象サイト。MVPは1サイトだが将来の複数サイトを識別可能にする。'),
        ('finance', 'external_cost', 'cost_type', 'cost type'),
        ('finance', 'external_cost', 'vendor_code', 'vendor code'),
        ('finance', 'external_cost', 'service_code', 'service code'),
        ('finance', 'external_cost', 'occurred_on', 'occurred on'),
        ('finance', 'external_cost', 'amount_original', 'amount original'),
        ('finance', 'external_cost', 'currency_original', 'currency original'),
        ('finance', 'external_cost', 'fx_rate_to_jpy', 'fx rate to jpy'),
        ('finance', 'external_cost', 'amount_jpy', 'amount jpy'),
        ('finance', 'external_cost', 'article_id', '論理記事ID。'),
        ('finance', 'external_cost', 'category_id', '対象カテゴリ。'),
        ('finance', 'external_cost', 'ai_job_id', 'ai job id'),
        ('finance', 'external_cost', 'source_artifact_id', 'source artifact id'),
        ('finance', 'external_cost', 'source_record_key', 'source record key'),
        ('finance', 'external_cost', 'recorded_by_actor_type', 'recorded by actor type'),
        ('finance', 'external_cost', 'recorded_by_actor_id', 'recorded by actor id'),
        ('finance', 'external_cost', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('finance', 'human_work_log', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('finance', 'human_work_log', 'display_id', 'HWL-接頭辞を持つアプリケーション生成の不変表示ID。'),
        ('finance', 'human_work_log', 'site_id', '対象サイト。MVPは1サイトだが将来の複数サイトを識別可能にする。'),
        ('finance', 'human_work_log', 'principal_id', 'principal id'),
        ('finance', 'human_work_log', 'work_date', 'work date'),
        ('finance', 'human_work_log', 'work_type', 'work type'),
        ('finance', 'human_work_log', 'minutes', 'minutes'),
        ('finance', 'human_work_log', 'hourly_cost_jpy', 'hourly cost jpy'),
        ('finance', 'human_work_log', 'computed_cost_jpy', 'computed cost jpy'),
        ('finance', 'human_work_log', 'article_id', '論理記事ID。'),
        ('finance', 'human_work_log', 'category_id', '対象カテゴリ。'),
        ('finance', 'human_work_log', 'article_version_id', '記事の特定Version。'),
        ('finance', 'human_work_log', 'note', 'note'),
        ('finance', 'human_work_log', 'approved_by_principal_id', 'approved by principal id'),
        ('finance', 'human_work_log', 'approved_at', 'approved at'),
        ('finance', 'human_work_log', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('finance', 'allocation_rule', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('finance', 'allocation_rule', 'display_id', 'ALR-接頭辞を持つアプリケーション生成の不変表示ID。'),
        ('finance', 'allocation_rule', 'site_id', '対象サイト。MVPは1サイトだが将来の複数サイトを識別可能にする。'),
        ('finance', 'allocation_rule', 'rule_code', 'rule code'),
        ('finance', 'allocation_rule', 'version_no', 'Aggregate内で1から増加する不変Version番号。'),
        ('finance', 'allocation_rule', 'cost_source_type', 'cost source type'),
        ('finance', 'allocation_rule', 'method', 'method'),
        ('finance', 'allocation_rule', 'parameters', 'equal、session weight、token usage、manual weights等。'),
        ('finance', 'allocation_rule', 'effective_from', '設定・関係が有効になる時刻。'),
        ('finance', 'allocation_rule', 'effective_to', '設定・関係の有効終了時刻。NULLは終了未定。'),
        ('finance', 'allocation_rule', 'status', '業務状態を示す安定Enum文字列。'),
        ('finance', 'allocation_rule', 'approved_by_principal_id', 'approved by principal id'),
        ('finance', 'allocation_rule', 'approved_at', 'approved at'),
        ('finance', 'allocation_rule', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('finance', 'cost_allocation', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('finance', 'cost_allocation', 'allocation_rule_id', 'allocation rule id'),
        ('finance', 'cost_allocation', 'source_type', 'source type'),
        ('finance', 'cost_allocation', 'source_id', 'source id'),
        ('finance', 'cost_allocation', 'target_type', 'target type'),
        ('finance', 'cost_allocation', 'target_id', 'target id'),
        ('finance', 'cost_allocation', 'period_month', 'period month'),
        ('finance', 'cost_allocation', 'allocation_ratio', 'allocation ratio'),
        ('finance', 'cost_allocation', 'allocated_amount_jpy', 'allocated amount jpy'),
        ('finance', 'cost_allocation', 'calculated_by_job_id', 'calculated by job id'),
        ('finance', 'cost_allocation', 'calculated_at', 'calculated at'),
        ('finance', 'cost_allocation', 'calculation_sha256', 'calculation sha256'),
        ('finance', 'cost_allocation', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('finance', 'unit_economics_snapshot', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('finance', 'unit_economics_snapshot', 'display_id', 'UES-接頭辞を持つアプリケーション生成の不変表示ID。'),
        ('finance', 'unit_economics_snapshot', 'site_id', '対象サイト。MVPは1サイトだが将来の複数サイトを識別可能にする。'),
        ('finance', 'unit_economics_snapshot', 'scope_type', 'scope type'),
        ('finance', 'unit_economics_snapshot', 'scope_id', 'scope id'),
        ('finance', 'unit_economics_snapshot', 'period_month', 'period month'),
        ('finance', 'unit_economics_snapshot', 'calculation_version', 'calculation version'),
        ('finance', 'unit_economics_snapshot', 'status', '業務状態を示す安定Enum文字列。'),
        ('finance', 'unit_economics_snapshot', 'confirmed_commission_jpy', 'confirmed commission jpy'),
        ('finance', 'unit_economics_snapshot', 'generated_commission_jpy', 'generated commission jpy'),
        ('finance', 'unit_economics_snapshot', 'external_cost_jpy', 'external cost jpy'),
        ('finance', 'unit_economics_snapshot', 'human_cost_jpy', 'human cost jpy'),
        ('finance', 'unit_economics_snapshot', 'contribution_profit_jpy', 'contribution profit jpy'),
        ('finance', 'unit_economics_snapshot', 'eligible_sessions', 'eligible sessions'),
        ('finance', 'unit_economics_snapshot', 'affiliate_clicks', 'affiliate clicks'),
        ('finance', 'unit_economics_snapshot', 'confirmed_orders', 'confirmed orders'),
        ('finance', 'unit_economics_snapshot', 'confirmed_epc_jpy', 'confirmed epc jpy'),
        ('finance', 'unit_economics_snapshot', 'confirmed_rpm_jpy', 'confirmed rpm jpy'),
        ('finance', 'unit_economics_snapshot', 'confirmation_rate', 'confirmation rate'),
        ('finance', 'unit_economics_snapshot', 'cost_recovery_months', 'cost recovery months'),
        ('finance', 'unit_economics_snapshot', 'source_watermark', 'source watermark'),
        ('finance', 'unit_economics_snapshot', 'report_artifact_id', 'report artifact id'),
        ('finance', 'unit_economics_snapshot', 'calculated_by_job_id', 'calculated by job id'),
        ('finance', 'unit_economics_snapshot', 'calculated_at', 'calculated at'),
        ('finance', 'unit_economics_snapshot', 'approved_by_principal_id', 'approved by principal id'),
        ('finance', 'unit_economics_snapshot', 'approved_at', 'approved at'),
        ('finance', 'unit_economics_snapshot', 'created_at', 'レコード作成時刻。UTCのtimestamptz。'),
        ('readmodel', 'public_article', 'article_id', '論理記事ID。'),
        ('readmodel', 'public_article', 'site_id', '対象サイト。MVPは1サイトだが将来の複数サイトを識別可能にする。'),
        ('readmodel', 'public_article', 'publication_id', 'publication id'),
        ('readmodel', 'public_article', 'publication_snapshot_id', 'publication snapshot id'),
        ('readmodel', 'public_article', 'canonical_path', 'canonical path'),
        ('readmodel', 'public_article', 'title', 'title'),
        ('readmodel', 'public_article', 'meta_title', 'meta title'),
        ('readmodel', 'public_article', 'meta_description', 'meta description'),
        ('readmodel', 'public_article', 'excerpt', 'excerpt'),
        ('readmodel', 'public_article', 'disclosure_text', 'disclosure text'),
        ('readmodel', 'public_article', 'article_type', 'article type'),
        ('readmodel', 'public_article', 'language_tag', 'language tag'),
        ('readmodel', 'public_article', 'content_sha256', 'content sha256'),
        ('readmodel', 'public_article', 'structured_data', 'Sanitize済みJSON-LD payload。'),
        ('readmodel', 'public_article', 'freshness_status', 'freshness status'),
        ('readmodel', 'public_article', 'published_at', 'published at'),
        ('readmodel', 'public_article', 'updated_public_at', 'updated public at'),
        ('readmodel', 'public_article', 'projection_generation', 'projection generation'),
        ('readmodel', 'public_article', 'is_indexable', 'is indexable'),
        ('readmodel', 'public_article_block', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('readmodel', 'public_article_block', 'article_id', '論理記事ID。'),
        ('readmodel', 'public_article_block', 'publication_snapshot_id', 'publication snapshot id'),
        ('readmodel', 'public_article_block', 'block_key', 'block key'),
        ('readmodel', 'public_article_block', 'block_type', 'block type'),
        ('readmodel', 'public_article_block', 'position', 'position'),
        ('readmodel', 'public_article_block', 'heading_level', 'heading level'),
        ('readmodel', 'public_article_block', 'heading_text', 'heading text'),
        ('readmodel', 'public_article_block', 'rendered_html', 'rendered html'),
        ('readmodel', 'public_article_block', 'render_payload', 'Component renderer用Allowlist payload。'),
        ('readmodel', 'public_article_block', 'block_sha256', 'block sha256'),
        ('readmodel', 'public_article_block', 'is_visible', 'is visible'),
        ('readmodel', 'public_product_card', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('readmodel', 'public_product_card', 'article_id', '論理記事ID。'),
        ('readmodel', 'public_product_card', 'publication_snapshot_id', 'publication snapshot id'),
        ('readmodel', 'public_product_card', 'product_id', '正規化されたCanonical Product。'),
        ('readmodel', 'public_product_card', 'card_key', 'card key'),
        ('readmodel', 'public_product_card', 'display_name', 'display name'),
        ('readmodel', 'public_product_card', 'short_description', 'short description'),
        ('readmodel', 'public_product_card', 'image_url', 'image url'),
        ('readmodel', 'public_product_card', 'image_alt', 'image alt'),
        ('readmodel', 'public_product_card', 'badges', '根拠付き表示Badge。'),
        ('readmodel', 'public_product_card', 'comparison_attributes', '公開可能FactのみをSnapshot化。'),
        ('readmodel', 'public_product_card', 'position', 'position'),
        ('readmodel', 'public_product_card', 'product_freshness_status', 'product freshness status'),
        ('readmodel', 'public_product_card', 'content_sha256', 'content sha256'),
        ('readmodel', 'public_offer', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('readmodel', 'public_offer', 'public_product_card_id', 'public product card id'),
        ('readmodel', 'public_offer', 'offer_id', 'ショップ単位の販売Offer。'),
        ('readmodel', 'public_offer', 'shop_id', 'shop id'),
        ('readmodel', 'public_offer', 'shop_name', 'shop name'),
        ('readmodel', 'public_offer', 'price_jpy', 'price jpy'),
        ('readmodel', 'public_offer', 'shipping_fee_jpy', 'shipping fee jpy'),
        ('readmodel', 'public_offer', 'availability', 'availability'),
        ('readmodel', 'public_offer', 'affiliate_url', 'affiliate url'),
        ('readmodel', 'public_offer', 'destination_host', 'destination host'),
        ('readmodel', 'public_offer', 'price_observed_at', 'price observed at'),
        ('readmodel', 'public_offer', 'availability_observed_at', 'availability observed at'),
        ('readmodel', 'public_offer', 'link_observed_at', 'link observed at'),
        ('readmodel', 'public_offer', 'freshness_status', 'freshness status'),
        ('readmodel', 'public_offer', 'is_cta_enabled', 'is cta enabled'),
        ('readmodel', 'public_offer', 'cta_disabled_reason', 'cta disabled reason'),
        ('readmodel', 'public_offer', 'position', 'position'),
        ('readmodel', 'public_offer', 'projection_generation', 'projection generation'),
        ('readmodel', 'public_route', 'site_id', '対象サイト。MVPは1サイトだが将来の複数サイトを識別可能にする。'),
        ('readmodel', 'public_route', 'path', 'path'),
        ('readmodel', 'public_route', 'route_type', 'route type'),
        ('readmodel', 'public_route', 'article_id', '論理記事ID。'),
        ('readmodel', 'public_route', 'redirect_path', 'redirect path'),
        ('readmodel', 'public_route', 'http_status', 'http status'),
        ('readmodel', 'public_route', 'is_indexable', 'is indexable'),
        ('readmodel', 'public_route', 'projection_generation', 'projection generation'),
        ('readmodel', 'public_route', 'updated_at', '最終更新時刻。UTCのtimestamptz。'),
        ('readmodel', 'runtime_control', 'id', '内部主キー。PostgreSQL 18のuuidv7()で生成する時系列順UUID。'),
        ('readmodel', 'runtime_control', 'site_id', '対象サイト。MVPは1サイトだが将来の複数サイトを識別可能にする。'),
        ('readmodel', 'runtime_control', 'scope_type', 'scope type'),
        ('readmodel', 'runtime_control', 'scope_id', 'scope id'),
        ('readmodel', 'runtime_control', 'publication_enabled', 'publication enabled'),
        ('readmodel', 'runtime_control', 'affiliate_links_enabled', 'affiliate links enabled'),
        ('readmodel', 'runtime_control', 'generation', 'generation'),
        ('readmodel', 'runtime_control', 'reason_code', 'reason code'),
        ('readmodel', 'runtime_control', 'expires_at', 'expires at'),
        ('readmodel', 'runtime_control', 'projected_at', 'projected at')
    )
    SELECT pg_catalog.count(*) INTO mismatch_count
    FROM expected
    LEFT JOIN pg_catalog.pg_namespace AS namespace
      ON namespace.nspname = expected.schema_name
    LEFT JOIN pg_catalog.pg_class AS relation
      ON relation.relnamespace = namespace.oid
     AND relation.relname = expected.table_name AND relation.relkind = 'r'
    LEFT JOIN pg_catalog.pg_attribute AS attribute
      ON attribute.attrelid = relation.oid
     AND attribute.attname = expected.column_name
     AND attribute.attnum > 0 AND attribute.attisdropped IS FALSE
    WHERE attribute.attnum IS NULL
       OR pg_catalog.col_description(relation.oid, attribute.attnum)
          IS DISTINCT FROM expected.description;
    IF mismatch_count <> 0 THEN
        RAISE EXCEPTION 'ST0305_COLUMN_COMMENT_MISMATCH';
    END IF;

    IF EXISTS (
        SELECT 1 FROM pg_catalog.pg_constraint
        WHERE conname = ANY(ARRAY['fk_iam_break_glass_record_incident_id', 'fk_publishing_publication_event_release_id', 'fk_publishing_rollback_record_incident_id'])
    ) THEN
        RAISE EXCEPTION 'ST0305_DEFERRED_FOREIGN_KEY_MISMATCH';
    END IF;
    IF (
        SELECT pg_catalog.count(*) FROM pg_catalog.pg_constraint
        WHERE conname = ANY(ARRAY['fk_publishing_public_route_publication_id', 'fk_publishing_publication_candidate_publication_snapshot_id', 'fk_publishing_publication_current_route_id', 'fk_publishing_publication_snapshot_publication_candidate_id'])
          AND contype = 'f' AND condeferrable IS TRUE AND condeferred IS TRUE
    ) <> 4 THEN
        RAISE EXCEPTION 'ST0305_CYCLIC_FOREIGN_KEY_MISMATCH';
    END IF;

    IF EXISTS (
        SELECT 1 FROM pg_catalog.pg_class AS relation
        JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid = relation.relnamespace
        CROSS JOIN LATERAL pg_catalog.aclexplode(
            COALESCE(relation.relacl, pg_catalog.acldefault('r', relation.relowner))
        ) AS acl
        WHERE namespace.nspname = ANY(ARRAY['publishing', 'freshness', 'analytics', 'finance', 'readmodel'])
          AND relation.relkind IN ('r','v') AND acl.grantee <> relation.relowner
    ) OR EXISTS (
        SELECT 1 FROM pg_catalog.pg_proc AS routine
        JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid = routine.pronamespace
        CROSS JOIN LATERAL pg_catalog.aclexplode(
            COALESCE(routine.proacl, pg_catalog.acldefault('f', routine.proowner))
        ) AS acl
        WHERE namespace.nspname = ANY(ARRAY['publishing', 'freshness', 'analytics', 'finance', 'readmodel'])
          AND acl.grantee <> routine.proowner
    ) OR EXISTS (
        SELECT 1 FROM pg_catalog.pg_default_acl AS default_acl
        LEFT JOIN pg_catalog.pg_namespace AS namespace
          ON namespace.oid = default_acl.defaclnamespace
        WHERE default_acl.defaclnamespace = 0
           OR namespace.nspname = ANY(ARRAY['publishing', 'freshness', 'analytics', 'finance', 'readmodel'])
    ) THEN
        RAISE EXCEPTION 'ST0305_PUBLIC_OR_DEFAULT_ACL_MISMATCH';
    END IF;

    IF EXISTS (
        SELECT 1 FROM pg_catalog.pg_class AS relation
        JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid = relation.relnamespace
        WHERE namespace.nspname = ANY(ARRAY['publishing', 'freshness', 'analytics', 'finance', 'readmodel'])
          AND relation.relkind = 'r'
          AND (relation.relrowsecurity IS TRUE OR relation.relforcerowsecurity IS TRUE)
    ) OR EXISTS (
        SELECT 1 FROM pg_catalog.pg_policy AS policy_record
        JOIN pg_catalog.pg_class AS relation ON relation.oid = policy_record.polrelid
        JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid = relation.relnamespace
        WHERE namespace.nspname = ANY(ARRAY['publishing', 'freshness', 'analytics', 'finance', 'readmodel'])
    ) THEN
        RAISE EXCEPTION 'ST0305_RLS_BOUNDARY_MISMATCH';
    END IF;

    IF (SELECT pg_catalog.count(*) FROM pg_catalog.pg_trigger
        WHERE tgname = ANY(ARRAY['trg_publishing_approval_guard', 'trg_publishing_candidate_guard', 'trg_publishing_publication_guard', 'trg_publishing_review_assignment_touch', 'trg_publishing_publication_candidate_touch', 'trg_publishing_publication_touch', 'trg_publishing_public_route_touch', 'trg_freshness_refresh_schedule_touch', 'trg_finance_revenue_import_touch', 'trg_finance_commission_touch', 'trg_publishing_review_decision_immutable', 'trg_publishing_publication_snapshot_immutable', 'trg_publishing_publication_event_immutable', 'trg_analytics_anonymous_event_immutable', 'trg_analytics_affiliate_click_event_immutable', 'trg_finance_commission_event_immutable', 'trg_finance_cost_allocation_immutable'])
          AND tgisinternal IS FALSE) <> 17 THEN
        RAISE EXCEPTION 'ST0305_TRIGGER_IDENTITY_MISMATCH';
    END IF;
END
$raos_st0305_validation$;

SELECT 'PASS'::pg_catalog.text AS status,
       39::pg_catalog.int4 AS tables,
       629::pg_catalog.int4 AS columns,
       150::pg_catalog.int4 AS installed_foreign_keys,
       17::pg_catalog.int4 AS triggers;
