-- Generated by scripts/build_st0306_database_roles.py; do not edit.
-- Story ST-0306 local candidate validation for exact PostgreSQL 18.4.
SET search_path = pg_catalog;
SET TIME ZONE 'UTC';

DO $raos_st0306_revision_validation$
BEGIN
    IF (SELECT pg_catalog.array_agg(
                   version_num::pg_catalog.text ORDER BY version_num
               )
        FROM public.raos_migration_version)
       IS DISTINCT FROM ARRAY['202608030006']::pg_catalog.text[] THEN
        RAISE EXCEPTION 'ST0306_REVISION_MISMATCH';
    END IF;
END
$raos_st0306_revision_validation$;

DO $raos_st0306_security_validation$
DECLARE
    mismatch_count bigint;
BEGIN
    IF pg_catalog.current_setting('server_version_num') <> '180004' THEN
        RAISE EXCEPTION 'ST0306_SERVER_VERSION_MISMATCH';
    END IF;
    IF (SELECT pg_catalog.count(*) FROM pg_catalog.pg_roles
        WHERE rolname = ANY(ARRAY['raos_migrator', 'raos_api_rw', 'raos_worker_rw', 'raos_dispatcher_rw', 'raos_projection_rw', 'raos_public_ro', 'raos_reporting_ro', 'raos_auditor_ro']::pg_catalog.text[])) <> 8
       OR EXISTS (
            SELECT 1 FROM pg_catalog.pg_roles
            WHERE rolname = ANY(ARRAY['raos_migrator', 'raos_api_rw', 'raos_worker_rw', 'raos_dispatcher_rw', 'raos_projection_rw', 'raos_public_ro', 'raos_reporting_ro', 'raos_auditor_ro']::pg_catalog.text[])
              AND (rolcanlogin OR rolsuper OR NOT rolinherit OR rolcreatedb
                   OR rolcreaterole OR rolreplication OR rolbypassrls
                   OR rolconnlimit <> -1 OR rolvaliduntil IS NOT NULL
                   OR rolconfig IS NOT NULL)
       ) OR EXISTS (
            SELECT 1 FROM pg_catalog.pg_auth_members AS membership
            JOIN pg_catalog.pg_roles AS member_role
              ON member_role.oid = membership.member
            WHERE member_role.rolname = ANY(ARRAY['raos_migrator', 'raos_api_rw', 'raos_worker_rw', 'raos_dispatcher_rw', 'raos_projection_rw', 'raos_public_ro', 'raos_reporting_ro', 'raos_auditor_ro']::pg_catalog.text[])
       ) THEN
        RAISE EXCEPTION 'ST0306_ROLE_SHAPE_MISMATCH';
    END IF;
    IF EXISTS (
        SELECT 1 FROM pg_catalog.pg_database AS object_record
        JOIN pg_catalog.pg_roles AS owner_role ON owner_role.oid = object_record.datdba
        WHERE object_record.datname = pg_catalog.current_database()
          AND owner_role.rolname = ANY(ARRAY['raos_migrator', 'raos_api_rw', 'raos_worker_rw', 'raos_dispatcher_rw', 'raos_projection_rw', 'raos_public_ro', 'raos_reporting_ro', 'raos_auditor_ro']::pg_catalog.text[])
    ) OR EXISTS (
        SELECT 1 FROM pg_catalog.pg_namespace AS object_record
        JOIN pg_catalog.pg_roles AS owner_role ON owner_role.oid = object_record.nspowner
        WHERE object_record.nspname = ANY(ARRAY['ops', 'iam', 'portfolio', 'catalog', 'evidence', 'editorial', 'ai', 'policy', 'publishing', 'freshness', 'analytics', 'finance', 'readmodel']::pg_catalog.text[])
          AND owner_role.rolname = ANY(ARRAY['raos_migrator', 'raos_api_rw', 'raos_worker_rw', 'raos_dispatcher_rw', 'raos_projection_rw', 'raos_public_ro', 'raos_reporting_ro', 'raos_auditor_ro']::pg_catalog.text[])
    ) OR EXISTS (
        SELECT 1 FROM pg_catalog.pg_class AS object_record
        JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid = object_record.relnamespace
        JOIN pg_catalog.pg_roles AS owner_role ON owner_role.oid = object_record.relowner
        WHERE namespace.nspname = ANY(ARRAY['ops', 'iam', 'portfolio', 'catalog', 'evidence', 'editorial', 'ai', 'policy', 'publishing', 'freshness', 'analytics', 'finance', 'readmodel']::pg_catalog.text[])
          AND owner_role.rolname = ANY(ARRAY['raos_migrator', 'raos_api_rw', 'raos_worker_rw', 'raos_dispatcher_rw', 'raos_projection_rw', 'raos_public_ro', 'raos_reporting_ro', 'raos_auditor_ro']::pg_catalog.text[])
    ) OR EXISTS (
        SELECT 1 FROM pg_catalog.pg_proc AS object_record
        JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid = object_record.pronamespace
        JOIN pg_catalog.pg_roles AS owner_role ON owner_role.oid = object_record.proowner
        WHERE namespace.nspname = ANY(ARRAY['ops', 'iam', 'portfolio', 'catalog', 'evidence', 'editorial', 'ai', 'policy', 'publishing', 'freshness', 'analytics', 'finance', 'readmodel']::pg_catalog.text[])
          AND owner_role.rolname = ANY(ARRAY['raos_migrator', 'raos_api_rw', 'raos_worker_rw', 'raos_dispatcher_rw', 'raos_projection_rw', 'raos_public_ro', 'raos_reporting_ro', 'raos_auditor_ro']::pg_catalog.text[])
    ) OR EXISTS (
        SELECT 1 FROM pg_catalog.pg_type AS object_record
        JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid = object_record.typnamespace
        JOIN pg_catalog.pg_roles AS owner_role ON owner_role.oid = object_record.typowner
        WHERE namespace.nspname = ANY(ARRAY['ops', 'iam', 'portfolio', 'catalog', 'evidence', 'editorial', 'ai', 'policy', 'publishing', 'freshness', 'analytics', 'finance', 'readmodel']::pg_catalog.text[])
          AND object_record.typrelid = 0
          AND owner_role.rolname = ANY(ARRAY['raos_migrator', 'raos_api_rw', 'raos_worker_rw', 'raos_dispatcher_rw', 'raos_projection_rw', 'raos_public_ro', 'raos_reporting_ro', 'raos_auditor_ro']::pg_catalog.text[])
    ) THEN
        RAISE EXCEPTION 'ST0306_WORKLOAD_ROLE_OWNS_OBJECT';
    END IF;

    WITH expected(role_name, schema_name, privilege_type, is_grantable) AS (
        VALUES ('raos_api_rw', 'ai', 'USAGE', false),
                ('raos_api_rw', 'analytics', 'USAGE', false),
                ('raos_api_rw', 'catalog', 'USAGE', false),
                ('raos_api_rw', 'editorial', 'USAGE', false),
                ('raos_api_rw', 'evidence', 'USAGE', false),
                ('raos_api_rw', 'finance', 'USAGE', false),
                ('raos_api_rw', 'freshness', 'USAGE', false),
                ('raos_api_rw', 'iam', 'USAGE', false),
                ('raos_api_rw', 'ops', 'USAGE', false),
                ('raos_api_rw', 'policy', 'USAGE', false),
                ('raos_api_rw', 'portfolio', 'USAGE', false),
                ('raos_api_rw', 'publishing', 'USAGE', false),
                ('raos_auditor_ro', 'editorial', 'USAGE', false),
                ('raos_auditor_ro', 'evidence', 'USAGE', false),
                ('raos_auditor_ro', 'iam', 'USAGE', false),
                ('raos_auditor_ro', 'ops', 'USAGE', false),
                ('raos_auditor_ro', 'policy', 'USAGE', false),
                ('raos_auditor_ro', 'publishing', 'USAGE', false),
                ('raos_dispatcher_rw', 'ops', 'USAGE', false),
                ('raos_projection_rw', 'ai', 'USAGE', false),
                ('raos_projection_rw', 'analytics', 'USAGE', false),
                ('raos_projection_rw', 'catalog', 'USAGE', false),
                ('raos_projection_rw', 'editorial', 'USAGE', false),
                ('raos_projection_rw', 'evidence', 'USAGE', false),
                ('raos_projection_rw', 'finance', 'USAGE', false),
                ('raos_projection_rw', 'freshness', 'USAGE', false),
                ('raos_projection_rw', 'iam', 'USAGE', false),
                ('raos_projection_rw', 'ops', 'USAGE', false),
                ('raos_projection_rw', 'policy', 'USAGE', false),
                ('raos_projection_rw', 'portfolio', 'USAGE', false),
                ('raos_projection_rw', 'publishing', 'USAGE', false),
                ('raos_projection_rw', 'readmodel', 'USAGE', false),
                ('raos_public_ro', 'readmodel', 'USAGE', false),
                ('raos_reporting_ro', 'analytics', 'USAGE', false),
                ('raos_reporting_ro', 'editorial', 'USAGE', false),
                ('raos_reporting_ro', 'finance', 'USAGE', false),
                ('raos_reporting_ro', 'portfolio', 'USAGE', false),
                ('raos_reporting_ro', 'publishing', 'USAGE', false),
                ('raos_reporting_ro', 'readmodel', 'USAGE', false),
                ('raos_worker_rw', 'ai', 'USAGE', false),
                ('raos_worker_rw', 'analytics', 'USAGE', false),
                ('raos_worker_rw', 'catalog', 'USAGE', false),
                ('raos_worker_rw', 'editorial', 'USAGE', false),
                ('raos_worker_rw', 'evidence', 'USAGE', false),
                ('raos_worker_rw', 'finance', 'USAGE', false),
                ('raos_worker_rw', 'freshness', 'USAGE', false),
                ('raos_worker_rw', 'ops', 'USAGE', false),
                ('raos_worker_rw', 'policy', 'USAGE', false),
                ('raos_worker_rw', 'portfolio', 'USAGE', false),
                ('raos_worker_rw', 'publishing', 'USAGE', false)
    ), observed AS (
        SELECT COALESCE(grantee.rolname, 'PUBLIC'), namespace.nspname,
               acl.privilege_type, acl.is_grantable
        FROM pg_catalog.pg_namespace AS namespace
        CROSS JOIN LATERAL pg_catalog.aclexplode(
            COALESCE(namespace.nspacl, pg_catalog.acldefault('n', namespace.nspowner))
        ) AS acl
        LEFT JOIN pg_catalog.pg_roles AS grantee ON grantee.oid = acl.grantee
        WHERE namespace.nspname = ANY(ARRAY['ops', 'iam', 'portfolio', 'catalog', 'evidence', 'editorial', 'ai', 'policy', 'publishing', 'freshness', 'analytics', 'finance', 'readmodel']::pg_catalog.text[])
          AND acl.grantee <> namespace.nspowner
    ), mismatches AS (
        (SELECT * FROM expected EXCEPT SELECT * FROM observed)
        UNION ALL
        (SELECT * FROM observed EXCEPT SELECT * FROM expected)
    )
    SELECT pg_catalog.count(*) INTO mismatch_count FROM mismatches;
    IF mismatch_count <> 0 THEN
        RAISE EXCEPTION 'ST0306_SCHEMA_ACL_MISMATCH';
    END IF;

    WITH objects AS (
        SELECT namespace.nspname AS schema_name, relation.relname AS table_name,
               namespace.nspname || '.' || relation.relname AS identity
        FROM pg_catalog.pg_class AS relation
        JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid = relation.relnamespace
        WHERE namespace.nspname = ANY(ARRAY['ops', 'iam', 'portfolio', 'catalog', 'evidence', 'editorial', 'ai', 'policy', 'publishing', 'freshness', 'analytics', 'finance', 'readmodel']::pg_catalog.text[])
          AND relation.relkind IN ('r', 'v')
    ), auditor_targets(schema_name, table_name) AS (
        VALUES ('editorial', 'article_disclosure_context'),
                ('editorial', 'article_methodology_binding'),
                ('editorial', 'article_template_version'),
                ('editorial', 'article_type_version'),
                ('editorial', 'content_schema_version'),
                ('editorial', 'editorial_methodology_version'),
                ('editorial', 'media_asset'),
                ('editorial', 'seo_metadata_version'),
                ('editorial', 'structured_data_manifest'),
                ('evidence', 'claim'),
                ('evidence', 'claim_evidence_link'),
                ('evidence', 'first_hand_experience_asset'),
                ('evidence', 'first_hand_experience_record'),
                ('evidence', 'source_packet_version'),
                ('iam', 'break_glass_record'),
                ('iam', 'principal'),
                ('iam', 'principal_role_assignment'),
                ('ops', 'audit_event'),
                ('policy', 'finding'),
                ('policy', 'gate_decision'),
                ('policy', 'policy_bundle'),
                ('policy', 'quality_check_run'),
                ('policy', 'quality_score'),
                ('policy', 'rule_version'),
                ('policy', 'waiver'),
                ('publishing', 'approval'),
                ('publishing', 'publication_event'),
                ('publishing', 'publication_snapshot'),
                ('publishing', 'review_assignment'),
                ('publishing', 'review_decision'),
                ('publishing', 'rollback_record')
    ), expected(role_name, schema_name, table_name, privilege_type, is_grantable) AS (
        SELECT 'raos_api_rw', schema_name, table_name, privilege_type, false
        FROM objects
        CROSS JOIN LATERAL pg_catalog.unnest(
            ARRAY['INSERT','SELECT','UPDATE']::pg_catalog.text[]
        ) AS privilege_type
        WHERE schema_name <> 'readmodel'
        UNION ALL
        SELECT 'raos_worker_rw', schema_name, table_name, privilege_type, false
        FROM objects
        CROSS JOIN LATERAL pg_catalog.unnest(
            CASE WHEN identity = ANY(ARRAY['editorial.article_disclosure_context', 'editorial.article_methodology_binding', 'editorial.article_template_version', 'editorial.article_type_version', 'editorial.content_schema_version', 'editorial.editorial_methodology_version', 'editorial.media_asset', 'editorial.seo_metadata_version', 'editorial.structured_data_manifest', 'evidence.first_hand_experience_asset', 'evidence.first_hand_experience_record']::pg_catalog.text[])
                 THEN ARRAY['SELECT']::pg_catalog.text[]
                 ELSE ARRAY['INSERT','SELECT','UPDATE']::pg_catalog.text[] END
        ) AS privilege_type
        WHERE schema_name NOT IN ('iam', 'readmodel')
        UNION ALL
        SELECT 'raos_dispatcher_rw', schema_name, table_name, privilege_type, false
        FROM (VALUES
            ('ops','outbox_event','SELECT'), ('ops','outbox_event','UPDATE'),
            ('ops','job','SELECT'), ('ops','job','UPDATE'),
            ('ops','inbox_receipt','SELECT'), ('ops','inbox_receipt','INSERT'),
            ('ops','job_attempt','SELECT'), ('ops','job_attempt','INSERT'),
            ('ops','audit_event','SELECT'), ('ops','audit_event','INSERT')
        ) AS dispatcher(schema_name, table_name, privilege_type)
        UNION ALL
        SELECT 'raos_projection_rw', schema_name, table_name, privilege_type, false
        FROM objects
        CROSS JOIN LATERAL pg_catalog.unnest(
            CASE WHEN schema_name = 'readmodel'
                 THEN ARRAY['DELETE','INSERT','SELECT','UPDATE']::pg_catalog.text[]
                 ELSE ARRAY['SELECT']::pg_catalog.text[] END
        ) AS privilege_type
        UNION ALL
        SELECT 'raos_public_ro', schema_name, table_name, 'SELECT', false
        FROM objects WHERE schema_name = 'readmodel'
        UNION ALL
        SELECT 'raos_reporting_ro', schema_name, table_name, 'SELECT', false
        FROM objects
        WHERE schema_name IN ('analytics','finance','readmodel','portfolio','editorial','publishing')
        UNION ALL
        SELECT 'raos_auditor_ro', objects.schema_name, objects.table_name, 'SELECT', false
        FROM objects JOIN auditor_targets USING (schema_name, table_name)
    ), observed AS (
        SELECT COALESCE(grantee.rolname, 'PUBLIC'), namespace.nspname,
               relation.relname, acl.privilege_type, acl.is_grantable
        FROM pg_catalog.pg_class AS relation
        JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid = relation.relnamespace
        CROSS JOIN LATERAL pg_catalog.aclexplode(
            COALESCE(relation.relacl, pg_catalog.acldefault('r', relation.relowner))
        ) AS acl
        LEFT JOIN pg_catalog.pg_roles AS grantee ON grantee.oid = acl.grantee
        WHERE namespace.nspname = ANY(ARRAY['ops', 'iam', 'portfolio', 'catalog', 'evidence', 'editorial', 'ai', 'policy', 'publishing', 'freshness', 'analytics', 'finance', 'readmodel']::pg_catalog.text[])
          AND relation.relkind IN ('r', 'v') AND acl.grantee <> relation.relowner
    ), mismatches AS (
        (SELECT * FROM expected EXCEPT SELECT * FROM observed)
        UNION ALL
        (SELECT * FROM observed EXCEPT SELECT * FROM expected)
    )
    SELECT pg_catalog.count(*) INTO mismatch_count FROM mismatches;
    IF mismatch_count <> 0 THEN
        RAISE EXCEPTION 'ST0306_TABLE_ACL_MISMATCH';
    END IF;

    WITH expected(role_name, function_name, privilege_type, is_grantable) AS (
        VALUES
            ('raos_api_rw','ai.guard_approved_source_packet()','EXECUTE',false),
            ('raos_api_rw','publishing.guard_final_approval()','EXECUTE',false),
            ('raos_api_rw','publishing.guard_publication_candidate()','EXECUTE',false),
            ('raos_api_rw','publishing.guard_publication_transition()','EXECUTE',false)
    ), observed AS (
        SELECT COALESCE(grantee.rolname, 'PUBLIC'),
               namespace.nspname || '.' || routine.proname || '(' ||
               pg_catalog.pg_get_function_identity_arguments(routine.oid) || ')',
               acl.privilege_type, acl.is_grantable
        FROM pg_catalog.pg_proc AS routine
        JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid = routine.pronamespace
        CROSS JOIN LATERAL pg_catalog.aclexplode(
            COALESCE(routine.proacl, pg_catalog.acldefault('f', routine.proowner))
        ) AS acl
        LEFT JOIN pg_catalog.pg_roles AS grantee ON grantee.oid = acl.grantee
        WHERE namespace.nspname = ANY(ARRAY['ops', 'iam', 'portfolio', 'catalog', 'evidence', 'editorial', 'ai', 'policy', 'publishing', 'freshness', 'analytics', 'finance', 'readmodel']::pg_catalog.text[])
          AND acl.grantee <> routine.proowner
    ), mismatches AS (
        (SELECT * FROM expected EXCEPT SELECT * FROM observed)
        UNION ALL
        (SELECT * FROM observed EXCEPT SELECT * FROM expected)
    )
    SELECT pg_catalog.count(*) INTO mismatch_count FROM mismatches;
    IF mismatch_count <> 0 OR EXISTS (
        SELECT 1 FROM pg_catalog.pg_class AS relation
        JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid = relation.relnamespace
        CROSS JOIN LATERAL pg_catalog.aclexplode(
            COALESCE(relation.relacl, pg_catalog.acldefault('S', relation.relowner))
        ) AS acl
        WHERE namespace.nspname = ANY(ARRAY['ops', 'iam', 'portfolio', 'catalog', 'evidence', 'editorial', 'ai', 'policy', 'publishing', 'freshness', 'analytics', 'finance', 'readmodel']::pg_catalog.text[])
          AND relation.relkind = 'S' AND acl.grantee <> relation.relowner
    ) OR EXISTS (
        SELECT 1 FROM pg_catalog.pg_attribute AS attribute
        JOIN pg_catalog.pg_class AS relation ON relation.oid = attribute.attrelid
        JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid = relation.relnamespace
        WHERE namespace.nspname = ANY(ARRAY['ops', 'iam', 'portfolio', 'catalog', 'evidence', 'editorial', 'ai', 'policy', 'publishing', 'freshness', 'analytics', 'finance', 'readmodel']::pg_catalog.text[])
          AND attribute.attnum > 0 AND attribute.attacl IS NOT NULL
    ) THEN
        RAISE EXCEPTION 'ST0306_FUNCTION_SEQUENCE_OR_COLUMN_ACL_MISMATCH';
    END IF;

    WITH schema_names(schema_name) AS (
        SELECT pg_catalog.unnest(ARRAY['ops', 'iam', 'portfolio', 'catalog', 'evidence', 'editorial', 'ai', 'policy', 'publishing', 'freshness', 'analytics', 'finance', 'readmodel']::pg_catalog.text[])
    ), expected(schema_name, object_type, role_name, privilege_type, is_grantable) AS (
        SELECT '<GLOBAL>', 'f', current_user, 'EXECUTE', false
        UNION ALL
        SELECT schema_name, 'r', 'raos_projection_rw', 'SELECT', false
        FROM schema_names WHERE schema_name <> 'readmodel'
        UNION ALL SELECT 'readmodel','r','raos_public_ro','SELECT',false
        UNION ALL SELECT 'readmodel','r','raos_projection_rw','DELETE',false
        UNION ALL SELECT 'readmodel','r','raos_projection_rw','INSERT',false
        UNION ALL SELECT 'readmodel','r','raos_projection_rw','SELECT',false
        UNION ALL SELECT 'readmodel','r','raos_projection_rw','UPDATE',false
    ), observed AS (
        SELECT COALESCE(namespace.nspname, '<GLOBAL>'),
               defaults.defaclobjtype::pg_catalog.text,
               COALESCE(grantee.rolname, 'PUBLIC'), acl.privilege_type,
               acl.is_grantable
        FROM pg_catalog.pg_default_acl AS defaults
        LEFT JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid = defaults.defaclnamespace
        CROSS JOIN LATERAL pg_catalog.aclexplode(defaults.defaclacl) AS acl
        LEFT JOIN pg_catalog.pg_roles AS grantee ON grantee.oid = acl.grantee
        WHERE (defaults.defaclnamespace = 0
               OR namespace.nspname = ANY(ARRAY['ops', 'iam', 'portfolio', 'catalog', 'evidence', 'editorial', 'ai', 'policy', 'publishing', 'freshness', 'analytics', 'finance', 'readmodel']::pg_catalog.text[]))
          AND defaults.defaclrole = (SELECT oid FROM pg_catalog.pg_roles WHERE rolname = current_user)
    ), mismatches AS (
        (SELECT * FROM expected EXCEPT SELECT * FROM observed)
        UNION ALL
        (SELECT * FROM observed EXCEPT SELECT * FROM expected)
    )
    SELECT pg_catalog.count(*) INTO mismatch_count FROM mismatches;
    IF mismatch_count <> 0 OR (
        SELECT pg_catalog.count(*) FROM pg_catalog.pg_default_acl AS defaults
        LEFT JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid = defaults.defaclnamespace
        WHERE defaults.defaclnamespace = 0
           OR namespace.nspname = ANY(ARRAY['ops', 'iam', 'portfolio', 'catalog', 'evidence', 'editorial', 'ai', 'policy', 'publishing', 'freshness', 'analytics', 'finance', 'readmodel']::pg_catalog.text[])
    ) <> 14 THEN
        RAISE EXCEPTION 'ST0306_DEFAULT_ACL_MISMATCH';
    END IF;

    WITH expected(
        table_name, policy_name, command, permissive, roles, qual,
        with_check, rls_enabled, rls_forced
    ) AS (VALUES
        ('editorial.content_schema_version', 'pl_content_schema_api', '*', true, 'raos_api_rw', 'true', 'true', true, true),
                ('editorial.content_schema_version', 'pl_content_schema_read', 'r', true, 'raos_auditor_ro,raos_projection_rw,raos_reporting_ro,raos_worker_rw', 'true', NULL, true, true),
                ('editorial.article_type_version', 'pl_article_type_api', '*', true, 'raos_api_rw', 'true', 'true', true, true),
                ('editorial.article_type_version', 'pl_article_type_read', 'r', true, 'raos_auditor_ro,raos_projection_rw,raos_reporting_ro,raos_worker_rw', 'true', NULL, true, true),
                ('editorial.article_template_version', 'pl_article_template_api', '*', true, 'raos_api_rw', 'true', 'true', true, true),
                ('editorial.article_template_version', 'pl_article_template_read', 'r', true, 'raos_auditor_ro,raos_projection_rw,raos_reporting_ro,raos_worker_rw', 'true', NULL, true, true),
                ('editorial.editorial_methodology_version', 'pl_methodology_api', '*', true, 'raos_api_rw', 'true', 'true', true, true),
                ('editorial.editorial_methodology_version', 'pl_methodology_read', 'r', true, 'raos_auditor_ro,raos_projection_rw,raos_reporting_ro,raos_worker_rw', 'true', NULL, true, true),
                ('editorial.article_methodology_binding', 'pl_article_methodology_api', '*', true, 'raos_api_rw', 'true', 'true', true, true),
                ('editorial.article_methodology_binding', 'pl_article_methodology_read', 'r', true, 'raos_auditor_ro,raos_projection_rw,raos_reporting_ro,raos_worker_rw', 'true', NULL, true, true),
                ('editorial.seo_metadata_version', 'pl_seo_metadata_api', '*', true, 'raos_api_rw', 'true', 'true', true, true),
                ('editorial.seo_metadata_version', 'pl_seo_metadata_read', 'r', true, 'raos_auditor_ro,raos_projection_rw,raos_reporting_ro,raos_worker_rw', 'true', NULL, true, true),
                ('editorial.structured_data_manifest', 'pl_structured_data_api', '*', true, 'raos_api_rw', 'true', 'true', true, true),
                ('editorial.structured_data_manifest', 'pl_structured_data_read', 'r', true, 'raos_auditor_ro,raos_projection_rw,raos_reporting_ro,raos_worker_rw', 'true', NULL, true, true),
                ('editorial.media_asset', 'pl_media_asset_api', '*', true, 'raos_api_rw', 'true', 'true', true, true),
                ('editorial.media_asset', 'pl_media_asset_read', 'r', true, 'raos_auditor_ro,raos_projection_rw,raos_reporting_ro,raos_worker_rw', 'true', NULL, true, true),
                ('evidence.first_hand_experience_record', 'pl_first_hand_record_api', '*', true, 'raos_api_rw', 'true', 'true', true, true),
                ('evidence.first_hand_experience_record', 'pl_first_hand_record_read', 'r', true, 'raos_auditor_ro,raos_projection_rw,raos_reporting_ro,raos_worker_rw', 'true', NULL, true, true),
                ('evidence.first_hand_experience_asset', 'pl_first_hand_asset_api', '*', true, 'raos_api_rw', 'true', 'true', true, true),
                ('evidence.first_hand_experience_asset', 'pl_first_hand_asset_read', 'r', true, 'raos_auditor_ro,raos_projection_rw,raos_reporting_ro,raos_worker_rw', 'true', NULL, true, true),
                ('editorial.article_disclosure_context', 'pl_disclosure_context_api', '*', true, 'raos_api_rw', 'true', 'true', true, true),
                ('editorial.article_disclosure_context', 'pl_disclosure_context_read', 'r', true, 'raos_auditor_ro,raos_projection_rw,raos_reporting_ro,raos_worker_rw', 'true', NULL, true, true)
    ), observed AS (
        SELECT namespace.nspname || '.' || relation.relname,
               policy_record.polname, policy_record.polcmd::pg_catalog.text,
               policy_record.polpermissive,
               (SELECT pg_catalog.string_agg(role_record.rolname, ',' ORDER BY role_record.rolname)
                FROM pg_catalog.unnest(policy_record.polroles) AS role_oid
                JOIN pg_catalog.pg_roles AS role_record ON role_record.oid = role_oid),
               pg_catalog.pg_get_expr(policy_record.polqual, policy_record.polrelid, false),
               pg_catalog.pg_get_expr(policy_record.polwithcheck, policy_record.polrelid, false),
               relation.relrowsecurity, relation.relforcerowsecurity
        FROM pg_catalog.pg_policy AS policy_record
        JOIN pg_catalog.pg_class AS relation ON relation.oid = policy_record.polrelid
        JOIN pg_catalog.pg_namespace AS namespace ON namespace.oid = relation.relnamespace
        WHERE namespace.nspname || '.' || relation.relname = ANY(
            ARRAY['editorial.article_disclosure_context', 'editorial.article_methodology_binding', 'editorial.article_template_version', 'editorial.article_type_version', 'editorial.content_schema_version', 'editorial.editorial_methodology_version', 'editorial.media_asset', 'editorial.seo_metadata_version', 'editorial.structured_data_manifest', 'evidence.first_hand_experience_asset', 'evidence.first_hand_experience_record']::pg_catalog.text[]
        )
    ), mismatches AS (
        (SELECT * FROM expected EXCEPT SELECT * FROM observed)
        UNION ALL
        (SELECT * FROM observed EXCEPT SELECT * FROM expected)
    )
    SELECT pg_catalog.count(*) INTO mismatch_count FROM mismatches;
    IF mismatch_count <> 0 THEN
        RAISE EXCEPTION 'ST0306_RLS_POLICY_MISMATCH';
    END IF;
END
$raos_st0306_security_validation$;

SELECT '202608030006'::pg_catalog.text AS revision,
       '472690c8ca8080e3e3c0e294e40ea31b30c7d9314daa4cd5ee83a4841d439825'::pg_catalog.text AS revision_sha256,
       8::pg_catalog.int4 AS role_count,
       22::pg_catalog.int4 AS rls_policy_count;
