-- Generated by scripts/build_st0307_migration_fixtures.py; do not edit.
-- Source: changes/st-0307/contracts/migration-upgrade-fixtures.v1.yaml
-- Command: uv run --locked --no-sync --no-env-file python scripts/build_st0307_migration_fixtures.py
-- Fixture: ST0307-V03-CONTENT-ALIGNMENT
-- Apply boundary: {"completed_forward_checkpoints":["202607300001","202607300002","202607300003","202607300004","202607300005","202607300007","202607300008","202607300009","202607300010","202607300011"],"production_revision":null,"source_kind":"FINALIZED_ALIGNMENT_CHECKPOINT_STATE","source_ref":"changes/st-0003/manifest.yaml"}
-- Synthetic test data only. Disposable PostgreSQL 18.4 database only.
-- This file is not an Alembic revision and must never enter the production runner.

BEGIN;
DO $st0307$
BEGIN
    IF current_setting('server_version_num')::integer <> 180004 THEN
        RAISE EXCEPTION 'ST-0307 requires PostgreSQL server_version_num 180004';
    END IF;
END
$st0307$;

SET LOCAL session_replication_role = replica;

INSERT INTO editorial.article_version (
    display_id, article_id, version_no, content_schema_version,
    title, body_sha256, status, source_packet_version_id,
    created_by_actor_type
)
VALUES (
    'ARV-ST0307-NO-GUESS', uuidv7(), 1, 1,
    'Synthetic migration fixture', repeat('a', 64), 'DRAFT', uuidv7(),
    'SYSTEM'
);

SET LOCAL session_replication_role = origin;
COMMIT;
