-- Generated by scripts/build_st0307_migration_fixtures.py; do not edit.
-- Source: changes/st-0307/contracts/migration-upgrade-fixtures.v1.yaml
-- Command: uv run --locked --no-sync --no-env-file python scripts/build_st0307_migration_fixtures.py
-- Fixture: ST0307-202608030005-PREDECESSOR
-- Apply boundary: {"completed_forward_checkpoints":[],"completed_production_revisions":["202608030001","202608030002","202608030003","202608030004","202608030005"],"production_revision":"202608030005","source_kind":"PRODUCTION_REVISION_GRAPH","source_ref":"changes/st-0305/manifest.yaml"}
-- Synthetic test data only. Disposable PostgreSQL 18.4 database only.
-- This file is not an Alembic revision and must never enter the production runner.

BEGIN;
DO $st0307$
BEGIN
    IF current_setting('server_version_num')::integer <> 180004 THEN
        RAISE EXCEPTION 'ST-0307 requires PostgreSQL server_version_num 180004';
    END IF;
END
$st0307$;

INSERT INTO ops.object_artifact (
    id, display_id, artifact_kind, bucket_name, object_key,
    content_type, byte_size, sha256, encryption_state,
    retention_class, source_system
)
VALUES (
    '00000000-0000-0000-0000-000000000060',
    'ART-ST0307-PREDECESSOR', 'other', 'fixture',
    'migration/st0307-predecessor.json', 'application/json', 2,
    repeat('6', 64), 'LOCAL_DEV', 'TEST', 'ST0307_FIXTURE'
);

COMMIT;
